### ISSUE TITLE
Data Page 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#100]
https://pp.opendevelopmentmekong.net/data/

I think the data page is really unattractive compared to the other pages - Could I suggest just putting titles up (so you have more of them on the page) Getting rid of descriptions which can be long and unwieldy with such narrow margins and replacing the descriptions with - 1) The Document Type -OR- An indication its a Data Visualization, The Language, and the little colorful icons for PDF, CSV, JSON, etc... 

![data](https://cloud.githubusercontent.com/assets/16559612/16899287/cbd2f4ee-4bcc-11e6-809d-7efc930d529e.JPG)

**Comment by acorbi** [comment]
@jpeizer1 this issue is being discussed over https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/50. im closing this one for reducing duplication
