### ISSUE TITLE
Extra  ","

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#101]
https://pp.opendevelopmentmekong.net/dataset/?id=hectare-forest-cover-by-province-in-cambodia-1973-2014

I notice some records have a "," starting at the beginning of a bunch of fields. This is a good example.  

![comma](https://cloud.githubusercontent.com/assets/16559612/16899299/2337370e-4bcd-11e6-8500-73b07f2cae7b.JPG)

**Comment by acorbi** [comment]
Fixed. Was a wpckan config issue. please report if you see more of those
