### ISSUE TITLE
Embedded maps not displaying

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#1014]
After the recent changes on the logic of the embed.php file, embedded maps are not displaying either base layer or the enabled layers.

https://opendevelopmentmekong.net/topics/aid-and-development-assistance/
![screenshot from 2017-06-12 00-07-32](https://user-images.githubusercontent.com/384894/27014954-38debe4e-4f03-11e7-97bb-1c7d75a75541.png)

Same happens on http://laos.opendevelopmentmekong.net/

@Huyeng can you please take a look at this issue? It might be related to the latest changes you did for supporting the categories hierarchy.

**Comment by Huyeng** [comment]
No worry, I will fix it soon.
