### ISSUE TITLE
Color Consistancy RSS Feed Labels

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#102]
https://pp.opendevelopmentmekong.net/profiles
https://cambodia.pp.opendevelopmentmekong.net/profiles

I think the  label backgrounds (example: RSS FEED, GET JEOSON, DOWNLOAD)
should consistently be the background color behind the logo (at page top) for each area. In the example below OD Cambodia has this right while OD Mekong has it wrong (it should be dark blue not green)

![rss-feed-cambodia](https://cloud.githubusercontent.com/assets/16559612/16899334/68880116-4bce-11e6-9372-d464dcbbc5eb.JPG)

![rssfeed-mekong](https://cloud.githubusercontent.com/assets/16559612/16899337/704a1de4-4bce-11e6-9bad-0fd7f4eb7ae8.JPG)

**Comment by acorbi** [comment]
@jpeizer1 The buttons should get their colour based on their functionality and not based on the country site. RSS Feed, geojson and  Download buttons are meant to be green ( we can agree on different colours later since changing it is super quick). 

So Im chaning those on cambodia site to be green

**Comment by jpeizer1** [comment]
@acorbi this works for me - as long as we have consistency of rules that determine size, color, etc...
