### ISSUE TITLE
Embedded map layers on topic pages not displaying properly

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1020]
Issue found on topic pages and home page of country sites. Browsers used are Chrome and Safari.
See: https://opendevelopmentmekong.net/topics/hydropower/
And: https://opendevelopmentmekong.net/topics/aid-and-development-assistance/

<img width="1032" alt="screen shot 2017-06-13 at 9 52 28 am" src="https://user-images.githubusercontent.com/6489398/27088871-82f12c58-501e-11e7-9f21-75a8f819d087.png">
<img width="707" alt="screen shot 2017-06-13 at 9 53 38 am" src="https://user-images.githubusercontent.com/6489398/27088878-85e7a2ac-501e-11e7-80b3-7df9a31e0488.png">

The map layer embed seems to work fine on the homepage of vacant country sites where we embed a map layer. 
See: https://laos.opendevelopmentmekong.net/
<img width="1173" alt="screen shot 2017-06-13 at 9 58 12 am" src="https://user-images.githubusercontent.com/6489398/27089032-e9b6eb94-501e-11e7-85db-b7e0158a50fc.png">

**Comment by gimmemochi** [comment]
@acorbi Okay, so I found that this is the cache issue. So I'll close it. But it happens so often. Is it possible for us to give some guidance to users somewhere on the site to clear cache if the maps are not displaying properly?

**Comment by acorbi** [comment]
@gimmemochi :+1: jup, always make sure it is not a caching issue. 

>  Is it possible for us to give some guidance to users somewhere on the site to clear cache if the maps are not displaying properly?

I would not do this. In general, normal users should not experience these issues and if they do, it would just be temporary...
