### ISSUE TITLE
The basemap is not working on the map explorer

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1029]
When click on any basemap, no map is shown up, but blank map.

**Comment by acorbi** [comment]
Hi @Huyeng I tested and indeed they baselayers are not showing up on ODC's map explorer:

Looking at the console, I see geoserver is returning 400s for those tiles

![Uploading Screenshot from 2017-06-21 12-25-03.png…]()

I tested on ODM and it works fine there:

![screenshot from 2017-06-21 12-26-07](https://user-images.githubusercontent.com/384894/27379751-d3240cea-567c-11e7-9fa3-91325c974bb6.png)

Can you maybe check if there is something wrong with those layers on geoserver?

**Comment by Huyeng** [comment]
Yes, I got the same error, 400s.  I already requested the mapper to check those layers.

**Comment by acorbi** [comment]
@Huyeng this is now fixed, right? im closing the issue

**Comment by Huyeng** [comment]
Fixed.
