### ISSUE TITLE
Dataset detail page: Back to search page from the breadcrumbs

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#1060]
![screenshot from 2017-07-05 13-53-22](https://user-images.githubusercontent.com/384894/27863217-5adfbc80-6189-11e7-9b09-53cdd8d44a16.png)

Make it part of the Breadcrumb menu. I think all the site architecture should go from breadcrumb menu. 

- If it come from main search, it will be **Home / Search Results for “Myanmar”/ Dataset-title** etc…
- If it does not come from a search on the search page **Home / Dataset / Dataset-title**

**Comment by Huyeng** [comment]
I would like to suggest as below:
If it come from data search it will be Home /Search Results/Data/ Dataset-title
If it come from main search, it will be Home/Search Results/Dataset-title 

I'm think about adding the keywords into the breadcrumb, it will fine for a few keywords, but let think about more keywords are used for searching, how will it look?
For example, the keywords got from Google Analytic that has been used to search "coalition of apparel workers democratic union cambodia". Including with the title of dataset, the breadcrumb will show in two lines.

**Comment by acorbi** [comment]
@Huyeng @DragonVirus The implementation for **data page** is a bit more complex since there can be several instances of the **Search page** content type. I have created another issue https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1064 to coordinate the implementation overthere. Also I am pasting Huyeng's comment over there for the record.

Now, to answer your question @Huyeng :

I do not think it is going to be a big problem, see the following screenshots:

![screenshot from 2017-07-05 17-34-21](https://user-images.githubusercontent.com/384894/27872215-55e10a08-61a8-11e7-94d5-737722529bab.png)
![screenshot from 2017-07-05 17-35-08](https://user-images.githubusercontent.com/384894/27872214-55dfaa00-61a8-11e7-83c3-3ec99694f125.png)

**Comment by Huyeng** [comment]
@acorbi, It will be fine on the main search as your screenshot. I also like the idea of adding the using the keywords in breadcrumb.
However, my question referred to the breadcrumb on detail page which has the format as below:

> If it come from main search, it will be **Home / Data / Search Results for “Myanmar” / Dataset-title** etc…

Then it will look like the screenshot below: 
- Keywords "Strategic Environmental Assessment Hydropower Dams"
<img width="1199" alt="screenshot at jul 05 22-55-19" src="https://user-images.githubusercontent.com/6613530/27872926-a157d2ba-61d4-11e7-8438-338faa51fd88.png">

**Comment by acorbi** [comment]
@Huyeng True! I did not counted with a long **dataset title** after a long **search term**.

I have one idea for a solution though. If the dataset title or the search term are longer than, let's say 30 characters, we trim them and add "..." so we ensure it does not get that long. What do you think?
