### ISSUE TITLE
Print: Can't print the content, the page is blank

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1068]
Open any page of the topic or other other, then click print view, you will see the page is blank. It means that no content is available to print.
<img width="1265" alt="screenshot at jul 06 17-19-35" src="https://user-images.githubusercontent.com/6613530/27906960-cbeb58d0-626f-11e7-87fe-9405c5ec7e35.png">

Page tested: https://opendevelopmentcambodia.net/topics/groundwater/

**Comment by acorbi** [comment]
True, I can reproduce the issue on my machine, only the small orange button for the contact us function is shown on the "printed" page.

[test.pdf](https://github.com/OpenDevelopmentMekong/wp-odm_theme/files/1128464/test.pdf)
