### ISSUE TITLE
Wrap khmer texts to fit their container

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#107]
![screenshot from 2016-07-17 17-17-05](https://cloud.githubusercontent.com/assets/384894/16901379/57a23dd4-4c42-11e6-9b89-80d843f9e2a6.png)

![647ab69a-4c5f-11e6-894f-6c481a78226d](https://cloud.githubusercontent.com/assets/384894/16906785/2a40513e-4cbd-11e6-84f6-e8fa93846080.JPG)

@Huyeng do you remember what we used to wrap long khmer strings on the frontend? @DragonVirus any CSS tricks you know about to fix this?

**Comment by S-mardii** [comment]
is it on Firefox?

**Comment by S-mardii** [comment]
if it work fine on Chrome, check this out #897

**Comment by Huyeng** [comment]
The issue still exist: https://cambodia.pp.opendevelopmentmekong.net/km/
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/17854056/3e179408-689a-11e6-81d2-6af53bf2388e.png)

**Comment by Huyeng** [comment]
The error was showed on Firefox V, 46.0.1

**Comment by acorbi** [comment]
Fixed
