### ISSUE TITLE
Time stamp

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1070]
![image](https://user-images.githubusercontent.com/14996905/27925567-8b512028-6285-11e7-8a59-4b18a4266eaa.png)

Don't get what these data formats are and why some show and some don't?

**Comment by acorbi** [comment]
@prustar please provide a URL for me to be able to reproduce the error

**Comment by Huyeng** [comment]
It looks like on the the All tab of search.

**Comment by acorbi** [comment]
this is fixed now
