### ISSUE TITLE
Dataset detail pages failing to render

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#1078]
Currently no content renders when accessing dataset detail pages, e.g. 

https://opendevelopmentmekong.net/dataset/?id=2a90f0a5-fa49-48b3-943c-e3a0a2875f14&search_query=dHlwZT1kYXRhc2V0JnBhZ2U9MA==

![image](https://user-images.githubusercontent.com/1206387/28004249-979ae932-656d-11e7-9f35-23064cf7a937.png)

https://opendevelopmentmekong.net/dataset/?id=47c87d40-2153-42c1-abed-3d9fafc53223&search_query=dHlwZT1saWJyYXJ5X3JlY29yZCZ0YXhvbm9teT1hbGwmc29ydGluZz1zY29yZSZxdWVyeT1UaGUrTGVnYWwrRnJhbWV3b3JrK29mK1N0YXRlK0xhbmQrTGVhc2VzK2FuZCtDb25jZXNzaW9ucytpbit0aGUrTGFvK1BEUiZwYWdlPTA=

**Comment by acorbi** [comment]
Fixed.
