### ISSUE TITLE
Automate how CKAN content appears on social sharing including Facebook

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1086]
@acorbi I don't know where to appropriately log this, but please have a look.
We've been notified by MLIKE that when they share resource from our datahub, from the data detail page (see [this for example](https://opendevelopmentcambodia.net/dataset/?id=1ee1c8e3-b828-4958-89a4-fb929543bccd)), the presentation is strange.
<img width="516" alt="screen shot 2017-07-11 at 10 00 22 pm" src="https://user-images.githubusercontent.com/6489398/28100065-855486fc-6685-11e7-8a19-885fadf5ece9.png">

I tried to re-produce it below:
I got the same text before I click enter.
<img width="499" alt="screen shot 2017-07-11 at 10 11 21 pm" src="https://user-images.githubusercontent.com/6489398/28100212-5d2d7fd4-6686-11e7-9d12-c29783398ecb.png">

When I click enter, the result is lightly different.
<img width="513" alt="screen shot 2017-07-11 at 10 10 19 pm" src="https://user-images.githubusercontent.com/6489398/28100146-0ccee6ea-6686-11e7-8276-1a95829ec75f.png">

cc: @Huyeng ODC official logo is cutoff in this display. A square logo might be better. 

Could we *do magic things* so that when people share our resource from our CKAN, in their social media snippet they will see the title and description of the dataset? In this particular example, can we program it to display: 
**Sub-decree on Phnom Penh Land Use Master Plan for 2035**
The objective and strategy-oriented development goal of Phnom Penh urbanization aim to: -	Orient land usage and ensure the existing potential value of the Phnom Penh capital city in sustainable, efficient and equitable ways, in order to support the socio-economic development, ensure food security, pulchritude and environmental quality. -	Orient the development with equality, equity and correspondence between Phnom Penh capital city, city, provinces of the country and other states’ cities. -	Ensure the promotion of Phnom Penh’s identity in order to integrate it into the region and compete with other cities in the region for the development of larger context, which offers the possibility on both technical and financial supports.

**Comment by acorbi** [comment]
@gimmemochi I'll take care of this today. I have already assigned it to me

**Comment by acorbi** [comment]
@gimmemochi this is now being deployed on PROD, can you please do some testing?

**Comment by gimmemochi** [comment]
@acorbi It works. I understand that the organization logo is not presented but can be added.
<img width="514" alt="screen shot 2017-07-19 at 6 06 25 am" src="https://user-images.githubusercontent.com/6489398/28364240-369581a0-6c49-11e7-9a83-6fa79b0effe4.png">
