### ISSUE TITLE
Error on post type page in Khmer site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1093]
<img width="1014" alt="screenshot at jul 12 23-41-08" src="https://user-images.githubusercontent.com/6613530/28128752-090cad64-675b-11e7-95ef-65649f66410f.png">
https://opendevelopmentcambodia.net/km/profiles

**Comment by acorbi** [comment]
@Huyeng i cannot reproduce this issue, is it still pending or should we close it?

**Comment by Huyeng** [comment]
I got it randomly. Let close it for now. I will reopen it if it is still available.
