### ISSUE TITLE
Formatting of Blog

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1100]
@Huyeng - I like the blog glad you introduced it again. 
Just noticed some issues with the formatting. 

![image](https://user-images.githubusercontent.com/14996905/28169910-97768308-6798-11e7-890d-5b17b1b82180.png)

**Comment by acorbi** [comment]
@Huyeng one suggestion I would do would be to add an icon to the menu item on the header

![screenshot from 2017-07-13 19-20-41](https://user-images.githubusercontent.com/384894/28178906-6a462a6a-6800-11e7-9cd7-53a3fee60bb0.png)

Concretely I would use:

http://fontawesome.io/icon/rss/

**Comment by Huyeng** [comment]
Thanks prustar. Well that's Catching issue, i think. I have already tested various broswers, Firefox, Chrome, Safari and IE, it looks as below: 
![screenshot_4](https://user-images.githubusercontent.com/6613530/28196306-fe25642a-6879-11e7-9eb5-aa1ef36b6964.jpg)
Anyways, please let me know if the problem still exists at your side by providing the browser and OS information. it would be helpful for me to fix it.

@acorbi, Yes, the icon should be added. I will do it now.

**Comment by acorbi** [comment]
@Huyeng thanks for adding the icon.

@prustar can you still reproduce this? if not, please close

**Comment by acorbi** [comment]
@prustar ping

**Comment by prustar** [comment]
It is corrected now. I was using Chrome.
