### ISSUE TITLE
Modify format of search results to display as one instead of two columns

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#1102]
With two columns there is an issue of flow and priority…
 
**Flow:** We have the drop down search boxes and they go horizontally across the page. Immediately under them are the links to the various data types people can select and they go horizontally across as well.  Neither of these rows is aligned  by column with each other. Then we have the actual search results in two columns –where should my eyes go? Should I be looking at the horizontal or vertical alignment?  The search results are  not what I immediately concentrate on. It’s not clear what’s more important to focus on,  the filters or the results? By contrast the results this was modeled on: UN Search Page (https://search.un.org/results.php?tpl=dist_search&SS=GS&query=Cambodia&Submit=Search&citrix_ns_id__un_org_%2F_wlf=V1NFU0VTU0lE%3FbLuGH424xwCGJsdrwpb6OhPrbNkA%26TlNDX2pfeGctYnFiZGlmX2l1dXFfbWNfd3Rf%3FMddKY54XOercQQ5UXFecB0GnJxQA%26&citrix_ns_id=FDeh9RzlbnoxHk2PO2otYmtMUaoA000&_gat_TrackerTPL=1&_ga=GA1.2.1829110673.1483586588&_gid=GA1.2.1661154388.1497250932)   looks much less “busy”  with one column of search results. My eye concentrates immediately on the results rather than the filtering 

**Priority:** The priority of the search results in this configuration is also a question. Which is most important? Are Column 1 and 2 equal? See my attached example where I selected LAND as a search and then used the LAWS subtype to filter. My perception is immediately that the second column of data is more important because the descriptions are more filled out – (the two columns also look a bit awkward and unaligned). 

![2csearch](https://user-images.githubusercontent.com/16559612/28177041-7b716266-67c7-11e7-83a2-ac2b752b1bfd.JPG)

Current state of play with this discussion:

**JP:** thinks one column search more clear for reasons mentioned above.  

**Alex:** I do not have a strong preference of one option or another. To summarize my position I would say that I prefer the 1-col layout for the reasons JP already mentioned BUT, in case of implementing the change, I would Change the layout on other parts of the system as well in order to keep consistency. If I am not forgetting anything this would only be the archive pages for some of the WP content types (news, announcements, site-updates) which currently have the 2-col layout. Example: http://opendevelopmentcambodia.net/news

**Huy Eng**
Search page is very important for everyone. We would like to have the search page which is not only having the effective functionality but also the easy to use for all different kind of our use
As I said before,  the two columns of the search page was proposed to be consistent with other page. If ODM and other OD country team agree with changing the two columns to one columns as the sending screenshot in the attached file, ODC team is happy with that. Anyways, our team is open to consider and discussion on improvement of the search page.  Note: Huy Eng feels search results should not go completely across the page but 75%-80% of it like google has,

![search-page full width of result](https://user-images.githubusercontent.com/16559612/28177070-9de29090-67c7-11e7-96d1-54ca258f7187.jpg)

**Comment by jpeizer1** [comment]
Email discussion: July 14 (in reference to Alex suggesting changes to Search format would necessitate changes to other function formats at the same time for consistency sake. 

Huy Eng: I would like to suggest to change the layout from the 2 cols to the 1 cols for search page only.  Keep the archive pages as currently the same. We don't want to get the comment from the users who frequently said that ODC site always changes the feature, but no content update. 
Regards,

JP: I tend to agree with Huy Eng on this -- and to a pretty strong degree.  We can either treat Search as one of a few functions that are similarly formatted or we can treat it as a discreet function with its own format because the ability to search find and prioritize is so important – this idea of single row results is not about aesthetics – it’s about strengthening the functionality of search to make getting results more intuitive to the user. So I think search is discreet. 

I also think that if we really wanted to relate it to other functionality with the same formatting we could just as easily make a strong case for having a single row form similar to DATA on opendevelopmentmekong.net  -- https://opendevelopmentmekong.net/search/data/?type=library_record&page=0

So i’d treat search and search format as a discreet function additionally because I don’t see a need to open up other technical issues in a tight schedule by modifying other functionality unrelated to search simply because the format happened to be similar -- underscoring once again that the revision to search suggested is not about aesthetics but increased functionality and more intuitive results.

**Comment by acorbi** [comment]
Thanks for leading this discussion @Huyeng and @jpeizer1

> So i’d treat search and search format as a discreet function additionally because I don’t see a need to open up other technical issues in a tight schedule by modifying other functionality unrelated to search simply because the format happened to be similar -- underscoring once again that the revision to search suggested is not about aesthetics but increased functionality and more intuitive results.

Ok, agreed. I am going to change the layout from 2 rows to 1 row. Let's test it on PP and decide whether we want to roll this out to prod after the team plays around with it.

**Comment by acorbi** [comment]
@Huyeng  @jpeizer1 @DBishton @prustar @gimmemochi @thetaung2 @DragonVirus can you please test the current implementation on PP ODM (example https://pp.opendevelopmentmekong.net/?s=land) ,PP ODC (example: https://pp.opendevelopmentcambodia.net/km/?s=social) and PP ODMm (example: https://pp.opendevelopmentmyanmar.net/my/?s=elections )

My personal opinion is that, the overall layout when using the full-width variant for the results is OK but seems to let a lot of blank space, and it kind of "asks" for having a sidebar with the filters reducing the result's width to that  75%-80% width which @Huyeng mentions.

![screenshot from 2017-07-17 13-28-44](https://user-images.githubusercontent.com/384894/28266191-dfa3d46a-6af3-11e7-8f4f-828c0e270f76.png)

**Comment by acorbi** [comment]
Implemented via https://github.com/OpenDevelopmentMekong/wp-odm_solr/pull/188

**Comment by Huyeng** [comment]
@acorbi - I would like to suggest to show the result in fourteen columns (about 85%) instead the sixteen columns (full width) without adding any sidebar. Google shows the result only about <60% of the screen without sidebar.

**Comment by acorbi** [comment]
@Huyeng Thanks for your suggestion. I am not so sure whether that would work fine but let me try changing the layout on my machine and taking a screenshot to discuss here whether is a good option.

I would not do it just because Google does. Google does not have the horizontal filter box on top of the search field

**Comment by acorbi** [comment]
@Huyeng @jpeizer1 this is how 1-col layout which takes about 85% of the width would look like

![screenshot from 2017-07-18 17-31-44](https://user-images.githubusercontent.com/384894/28325787-109afbfc-6bdf-11e7-851d-b5d9e0c21f42.png)

here with zoom at 50%

![screenshot from 2017-07-18 17-32-42](https://user-images.githubusercontent.com/384894/28325810-2441771c-6bdf-11e7-9c79-c9cf30b78072.png)

in my opinion, this does not work at all.

**Comment by jpeizer1** [comment]
@acorbi  Can I get a sense form you of why it doesn't work at all -- that would help in the solution. If the issue is white space only I can offer multiple suggestions:

1. Reduce the image size  to the left which allows for fewer rows. 
2. Determine if there is more information  you can add to fill those spaces and make the returning info even more useful.
3. Add a side box related to the search to reduce width - How about previewing the first selection in a preview -- or -- if a map exists of whats selected put that in the sidebar, or a profile. I know ODC is not crazy about data types being in the vertical but that would be an obvious option too.
