### ISSUE TITLE
Harmonize date representation on front-end

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#1108]
Currently, the format of the **creation** and **last modification dates** of WP and CKAN contents presented on the front-end is specified on https://github.com/OpenDevelopmentMekong/wp-odm_theme/blob/master/inc/utils/content.php#L416 and on https://github.com/OpenDevelopmentMekong/wp-odm_solr/blob/master/templates/odc/partials/ckan_result_template.php#L73 ( for CKAN records shown on the search results)

The format is currently **'j F Y'** (example: 13 June 2015), which is right.
https://pp.opendevelopmentmekong.net/?s=land&type=news-article&page=0
![screenshot from 2017-07-17 10-21-05](https://user-images.githubusercontent.com/384894/28260073-b7121ed6-6ad9-11e7-89b3-226e56ee35d5.png)
![screenshot from 2017-07-17 10-21-23](https://user-images.githubusercontent.com/384894/28260074-b7129a82-6ad9-11e7-8c56-e5435d847d32.png)

However on the archive and single pages of WP contents such as News, another date is shown:
https://pp.opendevelopmentmekong.net/news#!/story=post-5627589&loc=16.647565,96.1129218,7
![screenshot from 2017-07-17 10-22-11](https://user-images.githubusercontent.com/384894/28260104-cf3bd452-6ad9-11e7-8428-c7c2c5dd255e.png)

https://pp.opendevelopmentmekong.net/news/water-transport-to-begin-operation-in-early-june/
![screenshot from 2017-07-17 10-22-39](https://user-images.githubusercontent.com/384894/28260122-dfaac91a-6ad9-11e7-8acd-ae4f2440e652.png)

Which corresponds to the format **'l, F j, Y'**

**Comment by acorbi** [comment]
@Huyeng @DragonVirus Do not understand it completelly because we are specifying the format directly on code but I found a fix for this issue which consists on changing the site's default date (under **Settings > General**) and set **d M Y** format as pictured below:

![screenshot from 2017-07-18 11-18-56](https://user-images.githubusercontent.com/384894/28310040-7888a356-6bab-11e7-802d-6915bed4ed9f.png)

I noticed that ODC was displaying the dates properly and then checked that config, the rest of the sites had a different value.

Also note that I have updated the corresponding wiki guide: https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0

**Comment by Huyeng** [comment]
The problem with the add_apply_filter of the qtraslation plugin. Fixed them all now.

**Comment by acorbi** [comment]
@Huyeng I see, can we fix this with code somehow so we do not need to specify that configuration on the WP dashboard (thus reducing human error)?

**Comment by Huyeng** [comment]
No. We don't need to configure on the WP dashboard. The format is displayed based on the format in code. 
I just disable the Qt function. Moreover, it won't change any more, just once.

**Comment by acorbi** [comment]
> I just disable the Qt function

How did you do that?
