### ISSUE TITLE
Review "Popup a poll, survey, quiz..." plugin on ODM PP

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#1124]
@gimmemochi I have been researching for a while trying to find the best option for implementing the popup surveys we have been discussing for a while. After trying http://mare.io/ and http://surveymonkey.com/ without getting satisfied at all, I have installed another solution, a WP plugin, on ODM PP which is called "Popup a poll, survey, quiz..."

In a nutshell, the plugin serves as an interface with their online service, which means that the configuration section within the WP dashboard just provides with a couple of links that then take you to https://www.opinionstage.com/dashboard/. The good thing is that it also lets you couple the plugin with an account (which I did) so you do not need to login everytime.

![screenshot from 2017-07-18 18-56-36](https://user-images.githubusercontent.com/384894/28329651-d838c09e-6bea-11e7-9020-f99d1c008fca.png)

On opinionstage.com, you can create several contents (polls, surveys, forms, etc...) that you can then expose as pop-up on the front-end.

I have done a small test which you can see when you go to http://pp.opendevelopmentmekong.net/

![screenshot from 2017-07-18 18-45-21](https://user-images.githubusercontent.com/384894/28329658-da833226-6bea-11e7-9404-39e091ead290.png)

What I would need you to do now is to check whether this would be enough for the short pop-up survey you intend to integrate. Things to check would be:

- Wether the look-and-feel is ok
- whether it let's you add the type of questions you want
- whether the results are stored properly so we can analyze them later
- whether we can configure how often the pop up is shown and whether it can be hidden for users that already filled it out

**Comment by gimmemochi** [comment]
How do I edit the survey? Could you share login credential for Opinion
Stage with me via Lastpass?

**Comment by Huyeng** [comment]
I have a questions regarding to implement this. 
- When will the POPUP will be shown? Every time the page load or depends on the session? It will be annoy if it shows every time of loading.

**Comment by acorbi** [comment]
@gimmemochi the login credentials are the same as those for the opendevelopmentmekong@gmail.com account. I have shared the password with you over lastpass right now

@Huyeng there should be the possibility to coonfigure how often that pop-up appears. Optimally I would define the following behaviour:

- Present the pop always to users that haven't seen it
- If those users dismiss it, then reduce the frequency  and show at most once or twice again (to those users)
- Do not show anymore for those users that have filled it out.

The solution I tried first mare.io allowed for that level of configuration, not sure about opinionstage. @gimmemochi  can you please research?

**Comment by gimmemochi** [comment]
@acorbi I edit the popup survey to add questions based on the draft here. I can't preview the updated pop-up (not sure I should reconfig anything on WP). Since I can't see the preview, I'm not sure if users will have a choice to opt-out of the survey (the survey question template doesn't show that). 

The survey placement is very limiting. With the free version, we can introduce the survey to all users who visits the site. See the advanced config attached.

I agree with your placement criteria above but we can't do that with OpinionStage. 
<img width="1000" alt="screen shot 2017-07-19 at 3 34 13 pm" src="https://user-images.githubusercontent.com/6489398/28388434-55f6343c-6c98-11e7-97f5-b78a05ae47f6.png">

**Comment by gimmemochi** [comment]
@acorbi As you mentioned earlier, Mare.io does offer more placement options and behavioral survey options. 
<img width="1143" alt="screen shot 2017-07-19 at 3 50 00 pm" src="https://user-images.githubusercontent.com/6489398/28388995-13e9f13a-6c9a-11e7-9d5e-9791d5ad1888.png">
Should we give this a try?

**Comment by acorbi** [comment]
@gimmemochi 

> I can't preview the updated pop-up (not sure I should reconfig anything on WP). Since I can't see the preview, I'm not sure if users will have a choice to opt-out of the survey (the survey question template doesn't show that).

I believe there is a bug on their side that breaks the whole thing. I believe also, it has to do with the questions you have created. Maybe you specified a combination which triggers the bug. The (very basic) tests I did were successful and both previewing on opinionstage.com or by visiting https://pp.opendevelopmentmekong.net on incognito mode was working. See https://www.opinionstage.com/odm/survey_20-Jul-17_12-54-54/edit

- Can you please try to create the form again question-by-question in order to identify which settings breaks it?

> The survey placement is very limiting. With the free version, we can introduce the survey to all users who visits the site. See the advanced config attached. I agree with your placement criteria above but we can't do that with OpinionStage.

the only requirement which is not fullfiled is "If those users dismiss it, then reduce the frequency and show at most once or twice again (to those users)" which I would not consider that critical.

> @acorbi As you mentioned earlier, Mare.io does offer more placement options and behavioral survey options.

It seems indeed a better option, unfortunately there was some kind of conflict while integrating the code and could not make it work. I would like to suggest trying to fix the issue with opinionstage.com and if not I will put some more time on researching mare.io

**Comment by gimmemochi** [comment]
@acorbi I fixed a few questions, but the survey still doesn't preview. Could you check and see if we can resolve the conflict with Mare.io?

**Comment by acorbi** [comment]
@gimmemochi I have been working on integrating mare.io instead of opinionstage.com. Currently, the current implementation deployed on https://pp.opendevelopmentmekong.net/ should show a test pop-up survey on the bottom right corner.

Bad news is that there is currently an incompatibility between Firefox and the code that needs to be embedded on the site for the survey to appear. It should work fine on Chrome and Safari though.

Can you please test? If it works, We can proceed as following:

- You create the final survey with your OWN account on mare.io and provide me with the embed code ( under My Sites)
- I will then embed it on PP so we can do some testing. 
- I will see how can I fix that FF issue
- Once all is working fine, we stage to PROD.

Sounds good?

**Comment by gimmemochi** [comment]
@acorbi This is the embed code for pp.opendevelopmentmekong.net

<script>
  var _mare_pk = '1e34dd25f7b430a1a7cb09454576b4612162fc56cff1ba7b4648e6fc9eacb7c4'; 
  var _mare_sc = 'ee0c15de450f47a43b0070298881dc21';
  (function() {
    var mare = document.createElement('script'); mare.type = "text/javascript"; mare.async = true;
    mare.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'mare.io/API/script.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(mare, s);
  })();
</script>
                    
If this is not what you're looking for, I have shared my log in with you via Lastpass some weeks ago.

**Comment by acorbi** [comment]
@gimmemochi thanks. Just integrated it on PP.

![screenshot from 2017-09-12 09-00-03](https://user-images.githubusercontent.com/384894/30312240-e39a6792-9798-11e7-9565-f8f906a214b2.png)

**Comment by acorbi** [comment]
@gimmemochi please make sure that the PRODUCTION site is not configured yet on mare.io so the survey does not appear on PROD. The code is only deployed on PP at the moment but we should avoid this being shown in prod before we are sure that it works as expected

**Comment by gimmemochi** [comment]
@acorbi The survey is only displayed on pp.opendevelopmentmekong.net. Display after 2 page views. We can modify this. 
<img width="1071" alt="screen shot 2017-09-12 at 4 09 41 pm" src="https://user-images.githubusercontent.com/6489398/30317644-e4b859f4-97d4-11e7-9d70-faa0096b1a96.png">
