### ISSUE TITLE
Map Explorer: Fix cartodb layers not showing in map explorer and thematic maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#114]
@Huyeng I have continued the work you did on branch impl-62. I was able to include the js files and integrate the map explorer logic into the new theme so it does not produce any errors. However, I have noticed that the cartodb layers are not loading. The wms layers do load. See https://cambodia.pp.opendevelopmentmekong.net/map-explorer.

The same applies to the thematic maps. See https://cambodia.pp.opendevelopmentmekong.net/maps/mining-licenses/

Can you please pull the latest changes I did from master and work on this Issue to leave the mapping functionalities finally integrated in the new theme?

**Comment by jpeizer1** [comment]
I have tested all the Cambodia Layers and the following are not showing up (although the key is)

https://cambodia.pp.opendevelopmentmekong.net/map-explorer/#

INFRASTRUCTURE
Airports
Economis Cooridors
Radio Networks
Radio WMC
Railway Lines
Seaports
Special Economic Zones

ENVIRONMENT
Mangroves of Cambodia
Rivers
Soils

HYDROLOGY
Aqeuduct Atlas
Aqueduct Atlas - available blue water
Aqueduct Atlas - Baseline Water Stress
Aqueduct Atlas - Baseline Water Stress
Aqueduct Atlas - Flood Occurrence
Aqueduct Atlas - Total Blue Water
Aqueduct Atlas - Upstream Protected Lands
Aqueduct Atlas Withdrawal Rates
Hydro-Basins (Level 3)

ENERGY
Hydropower Dams 2014
Substations
Transmission Lines

AGRICULTURE
Community fisheries
Economic Land Concessions
Fish production and consumption rates
Flooded forest

**Comment by acorbi** [comment]
@Huyeng @jpeizer1 those are all cartodb layers, i believe.

**Comment by Huyeng** [comment]
Fixed.
