### ISSUE TITLE
Proper import of control_* scripts

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#1141]
Under **/inc/jeo-scripts** the following JS files can be found which add controls to the leaflet-based map:

- control_fullscreen.js
- control_clearscreen.js
- control_layers.js
- control_printmap.js

These are currently being loaded via the **wp_enqueue_scripts** function on https://github.com/OpenDevelopmentMekong/wp-odm_theme/blob/impl-2.4.0/functions.php#L235 (note this code is currently on the branch impl-2.4.0, not master)

A couple of lines above it, the lines https://github.com/OpenDevelopmentMekong/wp-odm_theme/blob/impl-2.4.0/functions.php#L227-L233 previously unloads (via wp_deregister_script function).

- do we need to de-register those scripts first?
- my assumption was that those files where loaded by the parent theme (jeo) and, in order to avoid duplications, they needed to be disabled before loading them again. @Huyeng is this also your understanding?
- the problem is that these will be only unloaded if `file_exists( STYLESHEETPATH . '/inc/jeo-scripts/fullscreen.js')` and/or `file_exists( STYLESHEETPATH . '/inc/jeo-scripts/clearscreen.js')` are true, however on the jeo parent I can only see the **fullscreen.js** file under **/inc/js/** (and not /inc/jeo-scripts).

Also, the **control_clearscreen.js** file should only be loaded on desktop. On mobile the map layers box is already hidden and can only be shown by clicking the layers button

**Comment by acorbi** [comment]
For reference see https://knowthecode.io/docx/wordpress/stylesheetpath

**Comment by Huyeng** [comment]
The script or condition should be: 
- if the fullscreen.js/control_fullscreen.js exists on the child theme "wp-odm_theme", the wp_deregister_script() is called to unload the parent's script through the its name " jeo.fullscreen" , and then load the child's script instead. 

This line code should be in IF file_exists condition under the wp_deregister_script() function like the jeo.js below:
`wp_enqueue_script('jeo.fullscreen', get_stylesheet_directory_uri() . '/inc/jeo-scripts/control_fullscreen.js',array('jeo'), '0.2.0');`

See this:
 `if ( file_exists( STYLESHEETPATH . '/inc/jeo-scripts/jeo.js')):
       wp_deregister_script('jeo');
       wp_enqueue_script('jeo', get_stylesheet_directory_uri() . '/inc/jeo-scripts/jeo.js', array('mapbox-js', 'underscore', 'jquery'), '0.5.0');
    endif;`

It is the same for the clearscreen.js/control_clearscreen.js.

Yes, the control_clearscreen.js file should only be loaded on desktop. The condition of detected mobile and desktop will be used as well. 

Is it ok, if I update these while i'm working on the issue #1057?

**Comment by acorbi** [comment]
ok @Huyeng  sounds good.

> Is it ok, if I update these while i'm working on the issue #1057?

Yes, please. Just add a commit with the message "Fixes #1141" so this Issue gets close when the PR is merged

**Comment by Huyeng** [comment]
Can i close this?

**Comment by acorbi** [comment]
yes, please close.

Am 28.07.2017 05:00 schrieb "Huy Eng" <notifications@github.com>:

Can i close this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1141#issuecomment-318543499>,
or mute the thread
