### ISSUE TITLE
MAP Explorer  -- Indent and Inability to select layers

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#115]
The Following Layers are formatted incorrectly on the Map Explorer (left Indent) and cannot even be chosen

https://cambodia.pp.opendevelopmentmekong.net/map-explorer/#

(Environment layer Theme)

![can tselect](https://cloud.githubusercontent.com/assets/16559612/16903856/a8b1844a-4c57-11e6-9f10-aa0db2acff27.JPG)

**Comment by acorbi** [comment]
@Huyeng can you please check this?

**Comment by Huyeng** [comment]
The issue was fixed. The same issue: #154.
