### ISSUE TITLE
Icomon icons won't show as before

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1152]
<img width="1201" alt="screenshot at jul 27 23-04-02" src="https://user-images.githubusercontent.com/6613530/28680026-40e3bf46-731f-11e7-86a6-57472dfadb85.png">

It should display like this:
<img width="1196" alt="screenshot at jul 27 23-04-42" src="https://user-images.githubusercontent.com/6613530/28680040-5035340c-731f-11e7-8b5a-438e76ca4b65.png">

**Comment by acorbi** [comment]
The error causing the issue

![screenshot from 2017-07-27 22-34-09](https://user-images.githubusercontent.com/384894/28691030-bcc41ae2-731b-11e7-9221-29aee503c6df.png)
