### ISSUE TITLE
MAP Explorer - Info Icon Buttons Don't Work 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#116]
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/#

It appears all the Info icons aren't working 
![info-icon](https://cloud.githubusercontent.com/assets/16559612/16903862/d435c608-4c57-11e6-80e1-c6e540ce0799.JPG)

**Comment by acorbi** [comment]
@Huyeng can you please check this?

**Comment by Huyeng** [comment]
Please merge this https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/194 of issue 138. The code will fix this issue.

**Comment by acorbi** [comment]
Fixed.
