### ISSUE TITLE
Update the tab on category page to be consitent as the search page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1166]
Please update the styling of the post type tabs in category page as the search page.
Category page:
https://opendevelopmentcambodia.net/category/social-development-2/ethnic-minorities-and-indigenous-people/?queried_post_type=topic

Search page:
https://opendevelopmentcambodia.net/?s=Ethnic+minorities+and+indigenous+people

Improve Functions: 
- Currently, the custom post type that has no post is not hidden. 
- Show only the custom post types that corresponding to the category.  It mean that hide the custom post type of the category if no post.

**Comment by acorbi** [comment]
@Huyeng please refer to the document **Enhancements on category page’s layout** https://docs.google.com/document/d/1j2eWETklPXUa_jZYBDZJxvGN9nsNoCEUMYnbrAdWeTU/edit where this is being discussed/drafted. There is currently a mockup made by Jia Li but not implementation has begun yet, we should start gathering feedback and agree on a final design before moving on to estimation and implementation.

**Comment by Huyeng** [comment]
The templates are designed by adapting from the search page which has the left sidebar. However, now the design of the search page was changed, so the category template should be updated too.
