### ISSUE TITLE
Map Explorer ELC TABLE LINK not working 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#117]
https://cambodia.opendevelopmentmekong.net/company-profiles/economic-land-concessions/

When i click - Table
![elc-table](https://cloud.githubusercontent.com/assets/16559612/16903893/cb1faf92-4c58-11e6-9fd4-d21a24d89ada.JPG)

it takes long... and then I get...

![404](https://cloud.githubusercontent.com/assets/16559612/16903901/e0db0a02-4c58-11e6-8dc8-555816f8616f.JPG)

**Comment by Huyeng** [comment]
This is the old ulr of ELC profile page. The link was updated on PROD site, but not PP.
