### ISSUE TITLE
Embedded map not rendering on PP

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#1171]
Hi @acorbi and @Huyeng,

There's an embedded map containing 3 layers on a published topic briefing on pre-production:
https://laos.pp.opendevelopmentmekong.net/topics/infrastructure/

This is not rendering on my machine, can you investigate?

**Comment by Huyeng** [comment]
Thanks @DBishton for reporting. 
After checking, you added only the layers, but no map is created for rendering.  Now, the map is presenting on the Infrastructure topic page.

Further detail please read the wiki: https://wiki.opendevelopmentmekong.net/partners:thematic-maps#how_to_embed_a_thematic_map_on_a_page
