### ISSUE TITLE
Map Explorer MINING LICENCES TABLE LINK not working 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#118]
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/#

When I click table link 
![mining-licence-table](https://cloud.githubusercontent.com/assets/16559612/16903928/76ce797c-4c59-11e6-94f3-9d065fc24a33.JPG)

I get this

![mining-licence](https://cloud.githubusercontent.com/assets/16559612/16903926/735ddf08-4c59-11e6-8c22-a8b13511cc00.JPG)

**Comment by Huyeng** [comment]
There is no profile page of mining published. It may just testing link.
