### ISSUE TITLE
Map Explorer OIL & GAS TABLE LINK not working 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#119]
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/#

When I click table link 
![oilandgas-table](https://cloud.githubusercontent.com/assets/16559612/16903937/bfd75ae4-4c59-11e6-9926-8a6bed153922.JPG)

I get this

![oilandgas](https://cloud.githubusercontent.com/assets/16559612/16903938/c64ebe76-4c59-11e6-8402-06ac67326636.JPG)

**Comment by Huyeng** [comment]
I can't produce the error. When i click on table icon, it brought me to profile page of oil and gas page. 
I think, the error has gone after updating code.
