### ISSUE TITLE
Data contributors registration

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1192]
@acorbi -- I've noticed a few people have registered to use our CKAN directly in the ODM CKAN. I get their notification as a new user. However, I'm not sure who they are or how they determined to get on the site. This is why we have the survey attached to the ODM front end which also allows us to ensure that when they register they are aware of our terms of use. 

Currently I'm sending them a kind note to ask them to register so that we can manage their contributions to the platform.  Could you please implement something which would direct people to register on the form prior to registering on CKAN. This would then provide us with some details of who these people are and how they came to register. 

Please note that the 7 people who recently registered have not responded to my request to sign up on the main page. Which means that we are not engaging them effectively and as I know nothing about them I don't know how to entice them to participate.

**Comment by acorbi** [comment]
> Currently I'm sending them a kind note to ask them to register so that we can manage their contributions to the platform. Could you please implement something which would direct people to register on the form prior to registering on CKAN. This would then provide us with some details of who these people are and how they came to register.

@prustar, if I am not mistaken, the link to the CKAN registration page is "hidden" (not exposed) everywhere except on the message presented after users complete the form. That means that they should only be able to find the link to the registration link once they have filled it out, making it necessary for them to do so.

Is this correct?

**Comment by prustar** [comment]
@acorbi -- I realise the link is hidden I couldn't find it when doing a search either. I don't know how to explain why we are getting registrations on CKAN without filling out the registration form? **But we are.** 

7 people that I have no idea who or how they came to register on our CKAN. It is very probable that one of our partners directed them or someone who is already a contributor. I don't know but I do know that if we don't know anything about these people and they aren't aware of our terms of use then we can't randomly assign them to an organisation and have them contributing data. This is a potential risk to the platform and one we should be mitigating.

**Comment by acorbi** [comment]
> I don't know but I do know that if we don't know anything about these people and they aren't aware of our terms of use then we can't randomly assign them to an organisation and have them contributing data.

I agree with that. My suggestion here would be: Do not assign anyone to any organisation without having them among those who filled out the form. As long as they are not assigned to any organization, they cannot do anything on CKAN.

**Comment by acorbi** [comment]
Proposed solution on https://github.com/OpenDevelopmentMekong/ckanext-odm_notifications/issues/1. closing this one
