### ISSUE TITLE
Add SDG's to Taxonomic tree

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1199]
@acorbi -- Please add the 'Sustainable Development Goals' to the taxonomic tree as a top tier.

Individual goals as a second tier: 
- SDG1 No Poverty
- SDG2 Zero Hunger
- SDG3 Good Health and Well-Being
- SDG4 Equality Education
- SDG5 Gender Equality
- SDG6 Clean Water and Sanitation
- SDG7 Affordable and Clean Energy
- SDG8 Decent Work and Economic Growth
- SDG9 Industry, Innovation and Infrastructure
- SDG10 Reduced Equality
- SDG11 Sustainable Cities and Communities
- SDG12 Responsible Consumption and Production 
- SDG13 Climate Change 
- SDG14 Life Below Water
- SDG15 Life on Land
- SDG16 Peace, Justice and Strong Institutions 
- SDG17 Partnerships for the Goals

We may included after some time individual breakdown of the indicators but I think this needs to be organic as we won't be able to populate this immediately. 

Also there is a need to discuss the convention for searches and outline some of the parameters to ensure that people who search for example: 

1. SDG Land - get results for indicator 15
2. SDG 15 - get results for indicator SDG15 Life on Land
3. Life on land - get all results from SDG15 Life on Land
etc.

What if people add ',' on the search such as 'SDG, climate change' does this affect the search? 

If we need to document this in a formal way then please let me know we can collaborate on this. 

Also please note that we will be creating a dashboard style for the landing page of the SDGs which will be placed on the main menu bar. The dashboard should house the indicator Logos as supplied by the UN and function as the taxonomic tree for people to select from. 

We probably need to have this mocked up and perhaps Jia Li could help. 

-- Pyrou

**Comment by acorbi** [comment]
@prustar ok adding new taxonomic terms involve the following steps:

- modifying the taxonomy definition maintained on http://github.com/OpenDevelopmentMekong/odm-taxonomy
- Adding the new top tier and children terms to the categories on WP
- Adding the terms on CKAN so they appear as selectable options under **topics**

I can undertake this task which would take me around 4h. @Huyeng any comments about this addition to the taxonomy?

Regarding the search, we can use synonyms so those terms all match to the same thing

> What if people add ',' on the search such as 'SDG, climate change' does this affect the search?

Comma is a so-called "stopword" and is not considered on searches

> If we need to document this in a formal way then please let me know we can collaborate on this.

We could put together a guide on the wiki which explains editors how to associate content (both on WP and CKAN) to SDGs. Or better extend https://wiki.opendevelopmentmekong.net/partners:keywords_and_taxonomic_tagging_guidelines

> Also please note that we will be creating a dashboard style for the landing page of the SDGs which will be placed on the main menu bar. The dashboard should house the indicator Logos as supplied by the UN and function as the taxonomic tree for people to select from.

Sounds good. This would definitely profit from some mocking and designing prior to implementation. Would you please coordinate this?

**Comment by gimmemochi** [comment]
@prustar I would like some clarifications. 
Do you want to modify the current [ODI Taxonomy](http://github.com/OpenDevelopmentMekong/odm-taxonomy) by adding SDG goals? 
OR 
Do you want to create a parallel/alternative way for categorizing content based on the SDGs goals by creating a new SDGs Taxonomy and map it to the ODI Taxonomy? 

If modifying the ODI Taxonomy is what you want, where do you suggest the 17 goals belong in the ODI Taxonomy?

**Comment by prustar** [comment]
@gimmemochi -- I mean exactly as I've specified above. SDG's as a new top-tier taxonomic group with the underlying indicators as 2nd tier. Options for 3rd and 4th tier as and when developed by partners.

This then allows us to tag content under each of these categories present on WP front end in organised manor, making linkages to relevant other taxonomic terms across the existing taxonomy. It then also means that search and navigation is facilitated along with the ability to specify more detailed keyword tags relating to these SDGs that increase their chances of results for specific datasets relating to specific indicators. i.e. a dataset on poverty indicators would naturally fall under SDG1 however we could additionally tag this 'poverty statistics'. Inversely statistics relating to income increases is also a sign of poverty alleviation however does not necessarily fall under SDG1 but SDG10 or 8 depending upon the focus, but could be tagged 'poverty statistics' to increase it's changes of resulting in SDG1 searches.

**Comment by acorbi** [comment]
@prustar, this has been done now. SDGs are available to select as:

- Categories on WP

![screenshot from 2017-12-05 11-53-19](https://user-images.githubusercontent.com/384894/33603644-86cda77e-d9b3-11e7-9c0d-e3e9015ff6cf.png)

- Topics on CKAN

![screenshot from 2017-12-05 11-31-25](https://user-images.githubusercontent.com/384894/33603649-8ca112da-d9b3-11e7-8b79-1746d3ec2db1.png)
