### ISSUE TITLE
MAP Explorer - Community Fisheries, Flooded Forest, Fish Sanctuaries  missing Table Link

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#120]
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/#

On production site:  https://cambodia.opendevelopmentmekong.net/map-explorer/
![community-fisheries](https://cloud.githubusercontent.com/assets/16559612/16903947/305acfee-4c5a-11e6-8aac-c415ae7e68ac.JPG)

On Version 2  Its missing
![community-fisheries-v2](https://cloud.githubusercontent.com/assets/16559612/16903953/4ae2e40a-4c5a-11e6-96b4-1ef6e4f376a6.JPG)

Same is true of these: Production
![fish-forest](https://cloud.githubusercontent.com/assets/16559612/16903970/cb00e9fc-4c5a-11e6-8207-947565ccf81b.JPG)

Verison 2.0
![fish-forest-v2](https://cloud.githubusercontent.com/assets/16559612/16903971/d525f7f6-4c5a-11e6-807c-7109bee939fe.JPG)

**Comment by acorbi** [comment]
@jpeizer1 it is important to note that we are testing v2.0 on pre-production and therefore we do not have the the same contents as in PROD. We can fix those links though for demonstration purposes but I would cautious on not spending much time doing config.

**Comment by jpeizer1** [comment]
@acorbi -- I'm just concerned during the conversion from pp to production they aren't in place -- When the platform  gets transferred over the tables should be there so they link to the tables in production.

**Comment by acorbi** [comment]
@jpeizer1 exactly, all those contents will be there and therefore those links should work

**Comment by jpeizer1** [comment]
@acorbi -- and the little table icons will automatically appear to the left of the Information Icons and correctly link to those locations as soon as the pp code is transferred without any intervention -Or- will programming have to be done to insure the table icons/links are there after the transfer?

**Comment by acorbi** [comment]
@jpeizer1 I believe no programming is needed. those links would appear automatically or would need to be added manually thorugh the dashboard. @Huyeng, @prustar  @DBishton should be able to shed some light on this

**Comment by Huyeng** [comment]
I would like to confirm that table icon will automatically appear if it is provide. 
There is a test of SEZ on PP: 
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/17015106/782c5220-4f52-11e6-97ac-0556ae495713.png)
