### ISSUE TITLE
Request to disable the Survey Popup on ODC website

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1200]
The survey popup made some people confused that ODC is advertising something on the site and they aren't happy with that. Thus, it was requested to disable Survey Popup on ODC site as soon as possible.

**Comment by acorbi** [comment]
@Huyeng the survey is currently being tested at this point and should only appear on ODM PP site. Should not appear on ODC and specially not on the PROD site. Can you specify a link (or better more details) indicating where you can reproduce this issue?

@gimmemochi is coordinating this and should be able to shed more light on the current configuration of the issue, which I am assigning to her.

**Comment by Huyeng** [comment]
It appeared almost of the page even the homepage.
<img width="386" alt="screenshot at sep 19 13-12-57" src="https://user-images.githubusercontent.com/6613530/30577914-5dab37ee-9d3b-11e7-9c84-9fd5d25307fc.png">

**Comment by acorbi** [comment]
@Huyeng please provide more concrete details:

- Can you specify a link (or better more details) indicating where you can reproduce this issue? PP or PROD?

**Comment by Huyeng** [comment]
@acorbi, it is on the PROD site. Sometimes, it appears, but sometimes it is not.
The pages that were informed about appearing the survey form are including homepage, access to public service page and others not sure. 

Anyways, please ensure that the embedded code of survey won't be added on ODC Prod site.

**Comment by acorbi** [comment]
@Huyeng I have just opened this PR so the code is only applied on PP environment. This code needs to be undone once the survey is ready to be rolled out.

Can you please review&test this and merge if it is fine?
