### ISSUE TITLE
MAP EXPLORER: geoserver legend not displaying

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1205]
@acorbi @Huyeng @thetaung2 -- just did test for using WCS geoserver to upload map layers into OD Myanmar. It worked but the legend isn't displaying correctly: 

![image](https://user-images.githubusercontent.com/14996905/31349389-11a3b4de-ad49-11e7-86f7-51c063b2a688.png)

see layer in PP: https://pp.opendevelopmentmyanmar.net/wp-admin/post.php?post=51341&action=edit
see legend image: http://104.155.211.193/geoserver/MyanmarMarine/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=MyanmarMarine:WatershedPollutionRiskWGS&LEGEND_OPTIONS=fontName:DroidSans;fontSize:9;fontColor:333333;fontAntiAliasing:true

**Comment by acorbi** [comment]
@prustar Fixed. It was an issue with the HTML code entered on the legend box. THe right value is:

`<div class=“wms-legend”>
  <h5>Watershed Pollution Risk</h5>
  <img src="http://104.155.211.193/geoserver/MyanmarMarine/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=MyanmarMarine:WatershedPollutionRiskWGS&LEGEND_OPTIONS=fontName:DroidSans;fontSize:9;fontColor:333333;fontAntiAliasing:true"/>
</div>
`

closing

**Comment by prustar** [comment]
@acorbi what was the error so I can check the wiki. Was it the instructions or a typo?

**Comment by acorbi** [comment]
a typo, some weird quotes character...
