### ISSUE TITLE
Add magic field for author and links and "[language] translated by ODV" to ODV news and announcements 

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1206]
@acorbi In the news and announcements section on WP editor panel. Perhaps @Huyeng can help?
Please add:
* Author (EN)
* Article link (EN)
* Author (VN)
* Article link (VN)

<img width="1009" alt="screen shot 2017-10-10 at 11 32 30 am" src="https://user-images.githubusercontent.com/6489398/31369473-fa385cb2-adae-11e7-8f34-47f429589b95.png">

* Vietnamese translated by ODV
* English translated by ODV
Question: @Huyeng Are ODC editor using these?

<img width="272" alt="screen shot 2017-10-10 at 11 33 01 am" src="https://user-images.githubusercontent.com/6489398/31369471-f665dccc-adae-11e7-8572-8b9590616618.png">

**Comment by acorbi** [comment]
@gimmemochi this is a quick one, will do.

**Comment by prustar** [comment]
@acorbi @gimmemochi -- Awesome! Thanks guys!

**Comment by acorbi** [comment]
@gimmemochi @prustar @Huyeng @mailannguyen This is now implemented. 

While creating or editing an **Announcement** on the WP dashboard, editors can now select the **Language** on the sidebar:

![screenshot from 2017-10-10 11-44-53](https://user-images.githubusercontent.com/384894/31380073-9606d406-adb0-11e7-8351-d0a3aff2e16a.png)

The public announcement source (sources still need to be created)

![screenshot from 2017-10-10 11-46-11](https://user-images.githubusercontent.com/384894/31380093-a644b0fe-adb0-11e7-9814-758990ef32cf.png)
 
and set the magic fields:

![screenshot from 2017-10-10 11-45-34](https://user-images.githubusercontent.com/384894/31380107-b08c649e-adb0-11e7-8c75-33986b252822.png)

Closing this

**Comment by gimmemochi** [comment]
Alex, thanks for adding this to the announcement post type. Could you add it to the News post type as well. Would be great if this can be done today or Monday. We would like to begin publishing news on Tuesday.

**Comment by acorbi** [comment]
@gimmemochi @mailannguyen done

![screenshot from 2017-10-12 13-50-14](https://user-images.githubusercontent.com/384894/31534983-786aecca-aff9-11e7-9652-3be50cbd27dd.png)
![screenshot from 2017-10-13 09-32-01](https://user-images.githubusercontent.com/384894/31534984-788f3512-aff9-11e7-973e-1762db3a8d48.png)
