### ISSUE TITLE
ODV: Importing taxonomy translation from Transifex to Wordpress

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1211]
@acorbi This issue is related to #1210.
As per the wiki guide on [collaborative translation](https://wiki.opendevelopmentmekong.net/partners:collaborative_translation#localizing_multi-site_front-end), the Taxonomy in WordPress is managed under the WordPress CATEGORY. To translate the taxonomy of each website on WordPress, editor has to click Category on the left hand menu, and then click Edit any taxonomy terms to translate and update it by pressing the Update button.

I also understand that tags and new sources also required to manually translate by editors. These are manageable manually. 

However, in regard to the taxonomy, is there a way to automate the translation process once #1210 is closed? The [Taxonomy package](https://www.transifex.com/open-development-mekong/odm-taxonomy/language/vi/)  has already been translated to Vietnamese and reviewed.

cc: @prustar @mailannguyen

**Comment by acorbi** [comment]
@gimmemochi will investigate a way to automatically import those translations

**Comment by prustar** [comment]
@gimmemochi -- Please clarify, is it just the translation or overall inconsistency in updating the WP categories to conform with our taxonomy? 

Seems silly that the Editors should need to manually do this as it would rely on them to confer with the taxonomic tree which is not easy to view and follow in the diagram provided. 

@acorbi -- Also please note that this would also related to my request to enhance the taxonomic structure to be more modular and allow for some independence at National levels to curate their own topics. Don't know how to find that issue or remember which repository it was under.

**Comment by gimmemochi** [comment]
@prustar This specific issue  is about importing Vietnamese translation from Transifex to ODV.
 #1210 Is about making ODV Taxonomy consistent with the Universal Taxonomy. As noted in https://docs.google.com/document/d/1yuvp7UTtmIao_anF1EwppBjXtwYNoMqJKwBZtILUYzc/edit#heading=h.m0pfwnecks45 @acorbi has imported the Universal Taxonomy in EN to ODV, ODT, and ODL. Now the translation needs to be imported from Transifex, if possible.

A new issue need to be created to address harmonizing ODM, ODC, and ODMm taxonomy with the universal taxonomy (as outlined in the Google Docs above).

**Comment by acorbi** [comment]
thanks @gimmemochi for the clarification.

@prustar yes, it would be interesting to find your suggestion for a modular approach to allow flexibility on the taxonomy's management. Currently, all sites "should" stick to the universal taxonomy. Which is not the case for ODM, ODC and ODMm

**Comment by acorbi** [comment]
@gimmemochi found an implemented (see https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1223) a mechanism for automatically importing the translations stored on https://github.com/OpenDevelopmentMekong/odm-taxonomy into WP. This involves some scripting only accessible for admins to execute.

I have documented the process on: https://wiki.opendevelopmentmekong.net/partners:collaborative_translation#automatic_import_of_localized_taxonomic_terms_into_wordpress_categories

**Comment by prustar** [comment]
@acorbi the issues of taxonomy hierarchy and lower tier flexibility is now extremely pressing have you had more thoughts about how to implement this?
