### ISSUE TITLE
Displaying iframe embed on ODV homepage with widget areas

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1212]
@acorbi We are working to add news, announcements, site update and more content such as profiles and topic pages to ODV. We are working to configure the homepage at the moment.

In May we disabled the default homepage template which is configurable with widgets and widget areas as describe in the [Wiki guide on front-end 2.0 configuration](https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0). These widgets would be display below the slider box. Instead of the default homepage template, we displayed a page with two embed iframe: a Vietnam at the glance dashboard from Venngage and a map layer entitled Chinese foreign aid projects in Vietnam. The map layer has been removed a few days ago but you can see [ODL homepage](https://laos.opendevelopmentmekong.net/) as a reference.

I understand that if we reset the the home page to the default one, the embed iframe from Venngage will not appear (as it is stored in a Page).

Could you please estimate how much time it would take to develop a solution that would allow the following display? 

<img width="459" alt="screen shot 2017-10-18 at 4 50 41 pm" src="https://user-images.githubusercontent.com/6489398/31712589-ba9b1194-b425-11e7-8840-d7c2ab8343ab.png">

(I'm explaining in detail since @prustar and @mailannguyen are new to this issue).

**Comment by acorbi** [comment]
hey @gimmemochi, thanks for the detailed explanation. in order to achieve this, following steps would  be needed:

- [ ] Install and configure https://wordpress.org/plugins/widget-shortcode/  **1 h - Alex**
- [ ] Configure the news and public announcements widgets on the wordpress dashboard under **Appearance > Widgets** **1h - Editor** 
- [ ] insert shortcode on "Vietnam at a glance" page to display the configured widgets on the previous step. **1h - Alex**

**Comment by acorbi** [comment]
Hey @gimmemochi I tested the plan I proposed yesterday on my comment and works with just a caveat, the widgets need to take the whole screen-width. That means no 2-col layout. It would be doable but would involve rather tricky/hacky solutions.

See https://vietnam.pp.opendevelopmentmekong.net/ and tell me if you want me to implement this on https://vietnam.opendevelopmentmekong.net (PROD)

**Comment by gimmemochi** [comment]
@acorbi We want to display 2-col to make it consistent with ODM. How tricky is the solution?

**Comment by acorbi** [comment]
OK, I have another alternative solution which consist on not using the page "Vietnam as a glance" as homepage but the widget-based option. We can then add the iframe embed as a widget. let me try it out on PP

**Comment by acorbi** [comment]
OK, done. See https://vietnam.pp.opendevelopmentmekong.net/

Should I implement on PROD?

**Comment by gimmemochi** [comment]
Yes, please. Thank you, Alex.

**Comment by prustar** [comment]
@acorbi Please ensure that it's still mobile responsive.

**Comment by acorbi** [comment]
@gimmemochi There are no published news or announcements yet on ODV (they are all either drafts, pending or private) thus would not be listed in the widgets, please publish some first:

https://vietnam.opendevelopmentmekong.net/wp-admin/edit.php?post_type=news-article
https://vietnam.opendevelopmentmekong.net/wp-admin/edit.php?post_type=announcement

Also, please make sure the widget titles are translated to vietnameses on:

https://vietnam.opendevelopmentmekong.net/wp-admin/widgets.php

Ping me when it is done so I can do the switch

**Comment by prustar** [comment]
@gimmemochi - Please work with @mailannguyen  to do this as she will be responsible for the Vietnamese site.
