### ISSUE TITLE
Add a Public announcement sources and Magic field box to ODM, ODT, ODL

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1216]
@acorbi Just realized that ODM hasn't been using the Public announcement sources and Magic field box for author and link on the Announcement page. Could you please add them to ODM, ODT, and ODL? 

I'm going to revise the guide on the wiki to make the editorial process for Public announcement consistent across the platform.

<img width="300" alt="screen shot 2017-10-27 at 10 15 41 am" src="https://user-images.githubusercontent.com/6489398/32087220-9ed69e02-bb04-11e7-8b8f-c69badc8f331.png">
<img width="795" alt="screen shot 2017-10-27 at 10 49 56 am" src="https://user-images.githubusercontent.com/6489398/32087225-a7d64c28-bb04-11e7-9580-e780831c86b3.png">

**Comment by acorbi** [comment]
@gimmemochi what about ODMM?

**Comment by acorbi** [comment]
@gimmemochi implemented consistently across all sites. Now those newly created taxonomies need to be filled with values. CLosing

**Comment by gimmemochi** [comment]
@acorbi Yes, add them to ODMM too.
