### ISSUE TITLE
Disclaimer of translation not visible on WP

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1217]
@acorbi 
Sometimes editors have to translate  **news summary**  or  **public announcement** from local language to English or from English to local language. We trust that editors take take great care to ensure the translation is as accurate as possible; however, most of OD editors are non-native speakers and sometimes produce grammatical or spelling errors when translating from local language to English. We avoid implying that the **news agency** or **Public announcement source** produce these errors by adding a disclaimer (using the box below) to notify the readers whether the text they read is a translation.
<img width="607" alt="screen shot 2017-10-27 at 5 16 39 pm" src="https://user-images.githubusercontent.com/6489398/32100575-76448582-bb3e-11e7-83db-5059fbc79a33.png">

I've been rewriting the guide on [news curation](https://wiki.opendevelopmentmekong.net/partners:news_collection) and when I tried to find examples to include in the guides, I realized that the text "(LANGUAGE) translated by OD team" is not visible. https://vietnam.opendevelopmentmekong.net/vi/news/vietnam-to-run-out-of-sand-in-5-years-say-experts/

Is this a bug? Or is it something editors can configure on WP?

@Huyeng Do you know if ODC editors still use this translation disclaimer? I couldn't find any news or announcement posts on ODC with the disclaimer either.

**Comment by acorbi** [comment]
@gimmemochi In order for that message to appear, editors need to mark that on the language box in the editing screen

![screenshot from 2017-10-27 14-37-58](https://user-images.githubusercontent.com/384894/32104376-747c90ba-bb24-11e7-8a58-15bc672e67a0.png)

Then it should appear on the front-end.

Is there a certain news article, where this has been marked But which does not show that information? If so, please provide me with details and I'll investigate

**Comment by gimmemochi** [comment]
@acorbi The checkboxes have been marked on ODV. See this for example: https://vietnam.opendevelopmentmekong.net/wp-admin/post.php?post=1956615&action=edit
<img width="821" alt="screen shot 2017-11-01 at 10 58 29 am" src="https://user-images.githubusercontent.com/6489398/32259515-a59ba97e-bef3-11e7-93c1-676d80685744.png">

There should be a disclaimer on the Vietnamese site, with a message read "Tiếng việt được dịch bởi ODV" (Vietnamese translated by ODV)
cc'ed @mailannguyen here so she can be in the loop.

I don't see translation disclaimer on ODC Gen II site at all. 
On the ODC archived site, the translation disclaimer appears as such:
<img width="803" alt="screen shot 2017-11-01 at 10 54 30 am" src="https://user-images.githubusercontent.com/6489398/32259458-40656e28-bef3-11e7-9fed-cdf8dc4502b4.png">
