### ISSUE TITLE
Disclaimer text on local language site shows EN

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1218]
@acorbi @Huyeng  Did we change the way the disclaimer text is presented? 
Please see ODC KH page below.
<img width="1279" alt="screen shot 2017-10-30 at 3 40 10 pm" src="https://user-images.githubusercontent.com/6489398/32161629-e741f4a8-bd88-11e7-8fa7-b10bf52f422c.png">

I found that ODV has the disclaimer translated and stored as a Page post-type: https://vietnam.opendevelopmentmekong.net/wp-admin/post.php?post=146456&action=edit

I went to Appearance --> Open Development and saw only the English version, so I added the VN translation in the box. https://vietnam.opendevelopmentmekong.net/wp-admin/themes.php?page=odm_options 

Translation needs to be added for ODC and ODMm.

**Comment by acorbi** [comment]
Thanks @gimmemochi!

Yes, this needs to be added to ODC ( @huyeng ) and ODMm ( @thetaung2 ). Please add both versions of the discalimer text for the footer as Pinkie did under https://vietnam.opendevelopmentmekong.net/wp-admin/themes.php?page=odm_options

![screenshot from 2017-10-30 10-59-09](https://user-images.githubusercontent.com/384894/32164973-63a47ffc-bd61-11e7-8151-711e807b2cf7.png)

**Comment by thetaung2** [comment]
Done @acorbi

**Comment by acorbi** [comment]
@thetaung2 awesome :trophy:
