### ISSUE TITLE
Improve style of Maps submenu

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#122]
When I hit the MAP CATALOGUE icon I don't always get
https://cambodia.pp.opendevelopmentmekong.net/layers

Sometime I am taken too Map Explorer
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/

It appears that you can mouse close to or sometimes in the Map Catalog Icon Like I did here and if it stays light green when I click it - it goes to Explorer instead

![000066](https://cloud.githubusercontent.com/assets/16559612/16904075/fc203b12-4c5c-11e6-8ede-53b5e8777ad0.png)

Only if it changes to dark green am I sure I'll go to
https://cambodia.pp.opendevelopmentmekong.net/layers

**Comment by acorbi** [comment]
not valid anymore
