### ISSUE TITLE
The styling of layer's info window on map explorer is not consistent

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1228]
Description from the WP content
 ![image](https://user-images.githubusercontent.com/14996905/32208240-9a844646-be2f-11e7-83cf-a51c14f02e6b.png)

Description from Dataset
![image](https://user-images.githubusercontent.com/14996905/32208349-5ea0d472-be30-11e7-9a0c-991e68d9c5ab.png)

**Comment by prustar** [comment]
@Huyeng @S-mardii @tthy --- Map explorer - WP Jeo Theme has been deprecated therefore there is no need for this to be updated and maintained.

**Comment by S-mardii** [comment]
Fixed
