### ISSUE TITLE
Khmer Flag Change Gets you stuck in only Khmer...

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#123]
https://cambodia.pp.opendevelopmentmekong.net/layers/hydropower-reservoirs/

I clicked the Khmer Flag 
![pre-khmer](https://cloud.githubusercontent.com/assets/16559612/16904115/e7db751c-4c5d-11e6-8281-0603d5301706.JPG)

And got this
![post-khmer](https://cloud.githubusercontent.com/assets/16559612/16904117/eff8e770-4c5d-11e6-8bb7-6413fd734c6f.JPG)

The problem is if I now leave this section entirely and click MAPS or TOPICS... etc.,.. I am stuck on Khmer with only a Khmer flag and can't change back... The English Flag Disappears
https://cambodia.pp.opendevelopmentmekong.net/km/map-explorer/
![post-khmer-1](https://cloud.githubusercontent.com/assets/16559612/16904129/27d35018-4c5e-11e6-95e2-679a01f735e1.JPG)

https://cambodia.pp.opendevelopmentmekong.net/km/topics
![post-khmer-2](https://cloud.githubusercontent.com/assets/16559612/16904130/3e0b2ec8-4c5e-11e6-81f1-131db75f4d56.JPG)

**Comment by acorbi** [comment]
@jpeizer1 good one, this is important

**Comment by Huyeng** [comment]
Fixed Yesterday.
