### ISSUE TITLE
WMS layer does not show up on website

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#1246]
I am trying to replace  ODC map layer with WMS. Unfortunately those layer does not show up on the website (Interactive map). I have check the WMS layer already and it is working fine on GeoSever.
 For example, GeoServer WMS layer:
 - Airport:  https://geoserver.opendevelopmentmekong.net/geoserver/Infrastructure/wms?service=WMS&version=1.1.0&request=GetMap&layers=Infrastructure:Airports_of_Cambodia_2015&styles=&bbox=102.9975,10.579686,107.186944,13.73&width=768&height=577&srs=EPSG:32648&format=application/openlayers
-Pre school: https://geoserver.opendevelopmentmekong.net/geoserver/Social_development/wms?service=WMS&version=1.1.0&request=GetMap&layers=Social_development:Pre_school&styles=&bbox=212773.298266628,1155087.88055457,764452.283445156,1594088.1338697&width=768&height=611&srs=EPSG:32648&format=application/openlayers

Those 2 layers are working on Geoserver but when I put them to map explorer it does not show up.
Layer on website:
-Airport https://opendevelopmentcambodia.net/wp-admin/post.php?post=74224&action=edit
-Pre school: https://opendevelopmentcambodia.net/wp-admin/post.php?post=99171&action=edit

On the other hand, yesterday, I drafted a WMS layer on the website and it is working,: https://opendevelopmentcambodia.net/wp-admin/post.php?post=112697&action=edit

**Comment by acorbi** [comment]
@punwath I have checked the airport layer and noticed that it is actually rendering but the projection seems to be wrong and that is why the POIs are rendered incorrectly, if you zoom out a couple of levels, you will see:

![screenshot from 2018-01-10 10-30-50](https://user-images.githubusercontent.com/384894/34765385-a3ec7498-f5f1-11e7-9f75-854c3ddeaba9.png)

I see that the layers is rendering fine on geoserver. So maybe this is an issue with the projection on the mapping logic. @Huyeng can you take a look at it?

**Comment by prustar** [comment]
@Huyeng @punwath @acorbi -- This has happened a few times now. I think we should define the projection in WP and ensure that all the Geoserver layers match this. We then need to update the wikis to include the projections for users so that they know what projection to assign their datasets. 

Suggest to use CRS - **WGS 84** and **EPSG:4326** as this is the most commonly used international standard. 

National datasets can still be provided in other file formats (shp etc) in localised projections and made available to the user if you would like to maintain this option.

**Comment by Huyeng** [comment]
In coding, the CRS has been defined as EPSG:4326, but i don't know why the projection won't convert. 
Anyways, I would like to suggest to publish the correct project on geoserver.

**Comment by prustar** [comment]
@Huyeng - yes thanks for doing this.
