### ISSUE TITLE
Topics Page - Cambodia - Khmer Format Issues

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#125]
https://cambodia.pp.opendevelopmentmekong.net/km/topics

Some items not word wrapping and breaching right margin:

![topics](https://cloud.githubusercontent.com/assets/16559612/16904202/647ab69a-4c5f-11e6-894f-6c481a78226d.JPG)

**Comment by acorbi** [comment]
adding this to https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/107 and closing.
