### ISSUE TITLE
Add social buttons on sidebar in dataset detail page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#1251]
Currently, on dataset detail pages such as http://opendevelopmentcambodia.net/dataset/?id=ilmenite do not expose the social buttons.

![Uploading Screenshot from 2017-06-05 11-47-57.png…]()

**Comment by S-mardii** [comment]
The current version of Dataset details page is hosted on CKAN.

Close this issue for now.
