### ISSUE TITLE
The subscription on ODM and ODC page doesn't work now

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1253]
The subscription form on ODC and ODM page stop working for awhile. It seems have a javascript conflicting https://opendevelopmentmekong.net/contact/
https://opendevelopmentcambodia.net/contact/

**Comment by acorbi** [comment]
@Huyeng I studied possible solutions to the issue and found this plugin: https://wordpress.org/plugins/mailchimp-for-wp/ which I integrated on PP for testing:  https://pp.opendevelopmentmekong.net/contact/

Can you please review it and let me you if you consider it a good option. If so, I will integrate it on all PROD sites.

**Comment by acorbi** [comment]
Fixed by using the mailchimp easy-forms plugin for wordpress. thanks @Huyeng
