### ISSUE TITLE
Cambodia Site NEWS Menu Item - Drop Down and News Page Formatting Issues 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#126]
On the News Drop Down -  Overlap, margin breaches

![000068](https://cloud.githubusercontent.com/assets/16559612/16904223/96a340e2-4c5f-11e6-946b-95c2da46785d.png)

Same issue on the actual news page
https://cambodia.pp.opendevelopmentmekong.net/km/news#!/story=post-92490

![newspage](https://cloud.githubusercontent.com/assets/16559612/16904247/0473ff1c-4c60-11e6-9169-155669f22d74.JPG)

**Comment by acorbi** [comment]
this has been raised already on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/107, closing
