### ISSUE TITLE
Problem GOING HOME from ODC in Khmer to Mekiong In English

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#127]
I was here in Khmer:
![newspage](https://cloud.githubusercontent.com/assets/16559612/16904270/6193ea9a-4c60-11e6-8460-0b5f032ac48c.JPG)

And tried to hit the Mekong page 
![mekong](https://cloud.githubusercontent.com/assets/16559612/16904274/7e56d62e-4c60-11e6-8920-632d6be49785.JPG)

and ended up with this 
![gohome](https://cloud.githubusercontent.com/assets/16559612/16904276/8b43f5ec-4c60-11e6-9ec8-024d5e1b5868.JPG)

**Comment by acorbi** [comment]
@jpeizer1 good catch, while navigating from site to site, the language part of the URL should be ignored. in this case you browsed from http://cambodia.pp.opendevelopmentmekong.net/**km**/news to http://pp.opendevelopmentmekong.net/**km**/news but shoulb be http://pp.opendevelopmentmekong.net/news
