### ISSUE TITLE
Login to WordPress

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#1270]
Now ODC team cannot login to WordPress. There is also a notification of "Enable cookies" as you can see in the attached picture. What can we do right now?
![image](https://user-images.githubusercontent.com/19201022/38593568-23b5ceba-3d6c-11e8-80dc-e89595bcb149.png)

**Comment by derwas** [comment]
Issue fixed with WP configuration.
