### ISSUE TITLE
Search on Main Menu: 502 Bad Gateway

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#1275]
There is an issue then we use the search in the main menu bar as below.
For example, I am searching for the election and get the  URL: https://opendevelopmentcambodia.net/?s=election

![image](https://user-images.githubusercontent.com/18112596/39300568-5978e486-4976-11e8-9381-b248defdffcb.png)

**Comment by vatana92** [comment]
Regarding to this issue, even the search page is back. But the search functionality doesn't work properly (Not effective). Many data and information are not searchable. 
If just focus only the dataset on CKAN (dataset, publication, & Law): Even there are some private records, there are still a lot of public records that should be found on WordPress search page. (https://data.opendevelopmentmekong.net/organization/cambodia-organization?q=Hydropower&sort=score+desc%2C+metadata_modified+desc)
![image](https://user-images.githubusercontent.com/19201022/39621253-44619582-4fb8-11e8-82dd-9a6a9db1a77c.png)

Here are the screenshot from the WordPress search result.
![image](https://user-images.githubusercontent.com/19201022/39621287-698f9dcc-4fb8-11e8-95c0-f7919af1b9cb.png)

**Comment by Huyeng** [comment]
Fixed
