### ISSUE TITLE
The Queens English or Queens English?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#128]
BTW -- Are we using "The Queens" English or "Queens" (as in Queens, New York)  English.. for the site? 

This is just for consistency sake... As I see some British spellings which my mind automatically wishes to correct. I want to be sure we're doing this all in one (English) language. Since I am dealing with a largely European group many of whom had a British-English education can I assume it should all be in British -English?

I tried searching for Organisation and Organization and got results for both...

**Comment by acorbi** [comment]
@DBishton ?

**Comment by DBishton** [comment]
@jpeizer1 @acorbi For the editorial copy, our style is AP and US-spelling, much as that is not my first impulse. Multi-word titles should be capitalized on the first word. However this changed over time and it's possible there are some  inconsistencies. @jpeizer1 Could you log examples as you see them?

**Comment by jpeizer1** [comment]
@acorbi @dbishton Ahhh... "Queens" English then.. Although technically speaking "Queens" and "Kings" (now Brooklyn) Counties in the city of "New" York do have something to do with the British taking what used to be "New" Amsterdam from the Dutch --  The only Colony/Pre-US State to have this distinction ;-)
That's why "New" York is not technically part of "New" England.

Anyhow.... I noticed catalogue spelled funny (e.g. not spelled in US English "catalog" ;-) ) in a few places but am having trouble locating them..

**Comment by acorbi** [comment]
@jpeizer1 @DBishton I was the one who wrote "catalogue". Apologies, I am either "Queens" or "The Queen" English native speaker (genious comparison, i take note of it :wink: )

**Comment by acorbi** [comment]
@jpeizer1 @DBishton Can we close this? if not, please provide detailed instructions on what needs to happen to be closed.

**Comment by gimmemochi** [comment]
@jpeizer1 @DBishton @acorbi ODC uses American English. Our Style guides were written to that style.
