### ISSUE TITLE
Serach Drop Down / Serach Function -- Multi-Issues 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#129]
I did a search for "Organization" in Cambodia

1. You can't see the green against this background.

2. What are these results? 

Water pollution
[caption id="attachment_90912" align="aligncenter" width="76
Solid waste
[caption id="attachment_91112" align="aligncenter" width="76
Sports
[caption id="attachment_74934" align="aligncenter" width="76

3. Only when I *TYPE* the word "organization" do I get the search drop down menu... If I start typing and field memory in my browser shows me a selection of words to choose from and I pick one - I go immediately to the advanced search page without getting the drop down,

I wonder here too if we should dispense with the drop down and go directly to the advanced search page (although here I see some benefit of keeping your place in the site if you search and decide to close the drop down rather than clicking through a result. 

![search](https://cloud.githubusercontent.com/assets/16559612/16904514/fb77e5f8-4c65-11e6-8fc4-62b12bc09e74.JPG)

**Comment by acorbi** [comment]
@jpeizer1 **[caption id="attachment_90912" align="aligncenter" width="76** is part of the content of the post, it is a so called shortcode. 

I will tweak the code so shortcodes are not shown in those post excerpts...
