### ISSUE TITLE
Enable Attribution of OSM for Interactive Map

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1298]
One user informs the team that the current interactive map does not give the credit to the OSM. 
URL: https://opendevelopmentcambodia.net/map-explorer
![image](https://user-images.githubusercontent.com/18112596/57207064-d18ea280-6ff4-11e9-9e48-6f6e25e73b5d.png)

**Comment by Huyeng** [comment]
Issue logged in: https://github.com/OpenDevelopmentMekong/IssuesManagement/issues/214

**Comment by prustar** [comment]
@Huyeng -- The WP Jeo Mapping theme has been deprecated. It's no longer used nor should it be accessible to users.

**Comment by S-mardii** [comment]
Fixed
