### ISSUE TITLE
Sub category shows in wrong parental category

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#130]
Actually the census was set in degraphic category but it appears not only on the parental category but also the energy category.
![image](https://cloud.githubusercontent.com/assets/18112596/16905201/ac859e10-4ccc-11e6-882a-42d9026c7ff8.png)

**Comment by acorbi** [comment]
@Huyeng I am assigning this to you. Can you please check code and config?.

**Comment by acorbi** [comment]
@Huyeng fixed?

**Comment by Huyeng** [comment]
It is fixed now.
