### ISSUE TITLE
No Topic listed on search page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1303]
Before, there are the main taxonomy listed.

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/6613530/60399730-57614100-9b93-11e9-8c36-22c003eee29b.png">

https://opendevelopmentcambodia.net/?s=Baseline+survey+on+mine

**Comment by S-mardii** [comment]
Fixed
