### ISSUE TITLE
Viewing the large image of announcement thumbnail shows incorrectly

### ISSUE THREAD

**Issue by vimoil** [OpenDevelopmentMekong/wp-odm_theme#1307]
The image was uploaded in Khmer language for Khmer announcement page. However, when we view the large image on announcement thumbnail, it shows image of English announcement page. 

![image](https://user-images.githubusercontent.com/34901723/62843195-35a2c000-bce2-11e9-93b4-8a765a321374.png)

**Comment by S-mardii** [comment]
Fixed on PreProduction
