### ISSUE TITLE
Insert default widgets when the new theme is activated

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#131]
Since the homepage will demonstrate through the widgets, I would like to suggestion to insert widgets as default when the theme is activated. Doing this we don't need to add and configure widget one by one on homepage. Moreover, users can manage the widget if they would like to change them.

**Comment by acorbi** [comment]
@Huyeng this is  a great suggestion. I already reported it on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/29, let's discuss it there. I am closing this since it is duplicated

**Comment by Huyeng** [comment]
Great.
