### ISSUE TITLE
Legend is not consistent 

### ISSUE THREAD

**Issue by vongpisith** [OpenDevelopmentMekong/wp-odm_theme#1310]
![image](https://user-images.githubusercontent.com/36388325/64327595-2f101b80-cff6-11e9-9b59-d6615eaba5a1.png)
there are two sub-legends not consistent as they are down-spaced which is not well-aligned with the other sub-legends.

**Comment by prustar** [comment]
@vongpisith -- please provide where you are getting this from?

**Comment by S-mardii** [comment]
@prustar --- this is the issue on the previous version of Interactive Map layer navigation.

**Comment by S-mardii** [comment]
Fixed
