### ISSUE TITLE
Create a Personal Bio post type

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#1317]
To enhance the management of the profile information of the team and other individuals on the platform, a new post type should be created **Personal Bio**.

**Comment by arky** [comment]
At the moment, we don't have the resources for future enhancements.

It is also not recommended to continue building upon the existing theme as they are not standards compliant.

**Comment by Huyeng** [comment]
No worry, I will support this task. This new cpt will be useful to create the bio of each board member, volunteer, intern or staff which is easy to manage for resigned or new members.

**Comment by S-mardii** [comment]
Plugin https://github.com/OpenDevelopmentMekong/wp-odm_team_profile is developed and installed on ODC.
