### ISSUE TITLE
Profile menu filter scrolls over the country menu

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#132]
Small styling issue: 

![image](https://cloud.githubusercontent.com/assets/14996905/16908677/c5919688-4ccd-11e6-9bde-82c7c771ec6f.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/commit/ba95cc67d21f4db996cad45e9d60f47141685ea9
