### ISSUE TITLE
Map Explorer doesn't show the Layer name in Khmer language

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#133]
The layer has the name in Khmer language but it doesn't appear.

![image](https://cloud.githubusercontent.com/assets/18112596/16908807/80cfa726-4cf8-11e6-9302-8c652924c062.png)

**Comment by acorbi** [comment]
@Huyeng im assigning this to you. I believe you implemented a mechanism so non-translated layers would not appear on the selection box...

**Comment by Huyeng** [comment]
This happened on the Current theme on PROD site, but not the new theme on PP.
