### ISSUE TITLE
Page with <iframe> break the responsiveness on Mobile

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#1330]
For the page with <iframe> additional width was added to the class name .post-content on mobile view and it breaks the mobile responsiveness.

Link to the page with iframe:

- https://opendevelopmentcambodia.net/topics/energy/
- https://opendevelopmentcambodia.net/social-accountability/health-center/

![image](https://user-images.githubusercontent.com/18528756/161181940-58707c7a-3645-4a6c-967b-247f8348f8e9.png)

**Comment by S-mardii** [comment]
@EricSoroos I would like to check with you regarding the main branch of this repo. Is it `master` or `php7`?

**Comment by EricSoroos** [comment]
This repo is now on master.
