### ISSUE TITLE
Map explorer: Satellite image is not a satellite image

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#137]
I don't know the source but this is not a satellite image: 
![image](https://cloud.githubusercontent.com/assets/14996905/16911352/43599b96-4cde-11e6-9a71-e562b3b60115.png)

Still can't revert back to normal base layer. 
All base layers should have option for metadata link.

**Comment by jpeizer1** [comment]
@prustar  @corbi while I don't think is optimal Pyrou -- I find I can revert to teh base layer if I click the layer I am showing a second time. so each of those layers PLAIN, SATELLITE, TERRESTRIAL is like an on and off switch.

**Comment by Huyeng** [comment]
@prustar, if i'm not wrong, the satellite layer just testing layer that Alex added for testing the baselayer functionality. 

@jpeizer1, the function of the baselayer works like swap and switch. It means that the base layer will be changed if other is clicked. Moreover, it also on and off if click the same layer. First click, the base layer will changed, second click, it will be disabled and the default will show instead.

**Comment by prustar** [comment]
@Huyeng The on/off function is fine however if you don't know this then you continue to click in frustration. Perhaps an indicator that changes when you click on/off would help the user to realise this, it could be simply a highlight of some sort around the box.

**Comment by Huyeng** [comment]
The active layer is highlighted.

**Comment by acorbi** [comment]
Fixed with import from PROD DB.
