### ISSUE TITLE
Map Explorer: Fixes Undefined variable

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#139]
![screenshot_15](https://cloud.githubusercontent.com/assets/6613530/16913003/f2324194-4d11-11e6-8dbe-ab82989c5b0f.png)

**Comment by acorbi** [comment]
@Huyeng is this happening on your dev env? I cannot reproduce it on mine or in Pre-production

**Comment by Huyeng** [comment]
There are some other debug that you will get also if the wp_debug is enabled.

**Comment by Huyeng** [comment]
Alex, is the issue fixed?
