### ISSUE TITLE
Data page layout incomplete

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#140]
Layout of data page appears to be missing/incomplete:

https://pp.opendevelopmentmekong.net/data/

![image](https://cloud.githubusercontent.com/assets/1206387/16913319/b0f8ae6e-4d13-11e6-9ca7-da1173a506ad.png)

![image](https://cloud.githubusercontent.com/assets/1206387/16913331/c51a1932-4d13-11e6-8879-62c6e2ca902a.png)

**Comment by acorbi** [comment]
@DBishton discussion about the data page on #50 . closing...
