### ISSUE TITLE
Topics - No dates? -- Home Page

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#147]
https://pp.opendevelopmentmekong.net/

I notice Topics no longer have update Dates on the home page. I think they should (otherwise why are _those_ four selected topics chosen?). I just think there should also be some small description describing whats been updated in the topic.  

![topics](https://cloud.githubusercontent.com/assets/16559612/16926771/3533246e-4cf8-11e6-8113-7f315ec4246f.JPG)

**Comment by acorbi** [comment]
@jpeizer1 those widgets can be configured to show the date (post meta) as pictured below. So I guess this is a decision for @DBishton to take. Anyway, I have enabled the date by now.

![screenshot from 2016-07-18 21-10-44](https://cloud.githubusercontent.com/assets/384894/16927141/5be0f558-4d2c-11e6-914f-261fa0502417.png)

Please mind that currently, the shown date is the creation date, I believe. I should then modify the logic so the latest modification date is shown, correct @jpeizer1 @DBishton ? I think we should implement this consistently across the platform.

Summary: If we configure it show (as in widget below) we show only one date, that is: the modification date.

**Comment by jpeizer1** [comment]
@acorbi @dbishton  - I believe we have to show the home page to be "alive" and the dates do that. As the latest analytics show we are still stuck at something like 2300 monthly views for Mekong and part of that I think has to do with the perceived unchanging nature of the site.  We have a 75% Bounce rate! People go to the front page and leave - by contrast ODC new gen has a 60% bounce rate.

**Comment by acorbi** [comment]
Dates are showing on ODM frontpage topics list now. This is a configuration issue and therefore the implementation is available. closing...
