### ISSUE TITLE
Topics -- Drop Down 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#150]
See now this is a good, attractive use of the Mouse rollover function for main menu items, (as opposed to duplicating the entire topics page as a rollover which was quite confusing). You just show one line topics in an attractive grouped format. This would work in Mekong too if we wished to do rollovers for topics. 

![hackpad com_baly4ob9re9_p 221970_1468855377920_screenshot from 2016-07-18 17-20-06](https://cloud.githubusercontent.com/assets/16559612/16930280/7c1c4b10-4d09-11e6-9e86-ceced336e37a.png)

The only minor downside is the user may not realize they can actually click the TOPICS menu item to get top the actual topics page showing all the boxes and updates.

**Comment by acorbi** [comment]
Implemented also in mekong
