### ISSUE TITLE
Map Explorer: Terrestrial Ecoregions showing blank screen

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#151]
https://pp.opendevelopmentmekong.net/map-explorer/

Terrestrial Ecoregions showing blank screen

![mapex](https://cloud.githubusercontent.com/assets/16559612/16934607/c619d662-4d25-11e6-9da3-5e7630d13c1f.JPG)

**Comment by jpeizer1** [comment]
even with CTRL+F5

**Comment by Huyeng** [comment]
This is the cartodb layer, so it won't show due to the conflict script. It should work after fixing issue #114.

**Comment by acorbi** [comment]
Fixed
