### ISSUE TITLE
TOPICS - OD MEKONG - Numerous Issues: (404) / Inconsistencies / Sort / Sub Topic issues

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#152]
Am putting all these together so you can see related issues and then split if you prefer

![000071](https://cloud.githubusercontent.com/assets/16559612/16935050/e1a54642-4d29-11e6-9fae-371d53a911d7.png)

If you click the any of the Three Heading labels in the TOPIC drop down (Environment & Land, Economy & People) You get a 404 Error

The following Drop Downs TOPICS Do not have the right links attached and give 404's:

Disasters & Emergency (404)	https://pp.opendevelopmentmekong.net/topics/disasters-and-emergency
Correct Link:	https://pp.opendevelopmentmekong.net/topics/disasters-and-emergency-response/

Environment and Nature resources (404)	https://pp.opendevelopmentmekong.net/topics/environment-and-nature-resources
Correct Link: https://pp.opendevelopmentmekong.net/topics/environment-and-natural-resources/

Urban Administration	(404) 	https://pp.opendevelopmentmekong.net/topics/urban-administration		
Correct link: https://pp.opendevelopmentmekong.net/topics/urban-administration-and-development/

The following Drop Down TOPICS Do not have the right links attached and also don't appear on Topic Page as a Box

Law & Judiciary		(404)			https://pp.opendevelopmentmekong.net/topics/law-and-judiciary
	

The following TOPICS on Topics page are actually Sub-topics and don't appear in drop-down

Fishing, fisheries and aquaculture
https://pp.opendevelopmentmekong.net/topics/fishing-fisheries-and-aquaculture/

Mekong River Basin
https://pp.opendevelopmentmekong.net/topics/mekong-river-basin/

Forests & Forestry
https://pp.opendevelopmentmekong.net/topics/forests-and-forestry/

Watersheds
https://pp.opendevelopmentmekong.net/topics/watersheds/

Hydropower Dams
https://pp.opendevelopmentmekong.net/topics/hydropower/

As a rule I think the Topics page should mirror the Topic Dropdown in terms of showing Topics and not subtopics. I would suggest putting ALL 17 Topics on a single page (rather than 10 topics per page on 3 pages) -- Either sorting in alpha order, or date of last update order - or under the three Uber-Drop Down Categories (Environment & Land, Economy & People).

I would further suggest that update dates for the Topics be right under the topics. If a SUB-Topic is modified it should appear in the Topic Box it is a child of along with its modification date (certainly there are enough room in those boxes for multiple sub-topic mods even moreso if you shorten the date formats.

**Comment by acorbi** [comment]
@jpeizer1 I have corrected the wrong links that you identified. thanks for that!
Also disabled the links on the headings (they do not correspond with any topic, they are topic areas)

Again, mind the differences between pre-production and production contents. 

> As a rule I think the Topics page should mirror the Topic Dropdown in terms of showing Topics and not subtopics. I would suggest putting ALL 17 Topics on a single page (rather than 10 topics per page on 3 pages) -- Either sorting in alpha order, or date of last update order - or under the three Uber-Drop Down Categories (Environment & Land, Economy & People).

Created https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/157
