### ISSUE TITLE
Map Explorer: No sub category of map is shown up

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#154]
Some layers are assigned to the subcategory, but the they are displayed without subcategory. 

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/16938127/2bc082d0-4d9f-11e6-9149-89d395e7df63.png)

**Comment by acorbi** [comment]
Fixed via 486d09b522c12599aa433f11bad10163df114371
