### ISSUE TITLE
The the sub menu doesn't show correctly

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#156]
When add more sub manus, the main menu doesn't show correctly. 
Those 4 sub manus should be under the Hydropower.
![image](https://cloud.githubusercontent.com/assets/18112596/16941230/0bf990bc-4db9-11e6-87c8-2f9d7483dbb1.png)

**Comment by acorbi** [comment]
@punwath this issue does not belong to this repository. It relates to the "old" wordpress frontend which is https://github.com/OpenDevelopmentMekong/opendev-wptheme, please file this Issue there. thanks
