### ISSUE TITLE
Include maps on search suggestions and advanced search

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#159]
Currently, search suggestions only expose Topics, Stories, Profiles and Data. Map layers should be added to the list of contnt types that get queried.

<img width="1266" alt="0c31fefa-4d07-11e6-93bc-4199ed644038" src="https://cloud.githubusercontent.com/assets/384894/16944805/8a49041e-4da2-11e6-91ff-41b543fe0a86.png">
<img width="1265" alt="087e095c-4d07-11e6-813c-270f786a394b" src="https://cloud.githubusercontent.com/assets/384894/16944807/8c8d0f2c-4da2-11e6-90ef-9607c6d6b5ce.png">

**Comment by prustar** [comment]
@acorbi - I have raised the issue of distinction between data (spatial vs non-spatial) continuously. This is why I've been lobbying for a map catalogue - thank you for now implementing this. 

Suggestion - considering that there is currently no clear distinction in CKAN and that we are now pulling the map data into a catalogue using WP layers then can we direct the search for map layers here? This is not an ideal solution as it would then need to search across the platform and not in a centralised location such as in CKAN.

**Comment by acorbi** [comment]
>  then can we direct the search for map layers here?

@prustar yes, once this issue is fixed, users will be getting results from the layers stored on WP (the same items they get when they open the map catalogue)
