### ISSUE TITLE
Show additional data fields in order

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#168]
**Datasets:**

Source
Date Created
Temporal Range
Process
Logical consistency
Completeness
Access use and Constraints
Copyright
License
Attributes
Last updated

@prustar please complete for lib records and laws

**Comment by prustar** [comment]
Please add **language** to the above after license. 
All list: 
**TITLE
TAGS
ORGANISATION (only for ODM site)**

**Library:** 
Description 
Document type
Publication date
Source (would it be possible to add a citation) 
Author (only display the author if there is something entered in these fields) 
Publication place
Language
License
Access use and Constraints

**Laws, Policies and Agreements:**
Full title
Short description
Document type
Status
Adoption date
Language
License
Access use and Constraints.

**Comment by prustar** [comment]
@acorbi - let's see how they look in this order and if people would like to see more fields. I believe these are the most important.

**Comment by acorbi** [comment]
@prustar moving to https://github.com/OpenDevelopmentMekong/wpckan/issues/152 since it belongs to that repository. closing this one
