### ISSUE TITLE
Dataset detail page Admin Function

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#172]
When a detailed data page has been loaded on WP it would be handy to have an ADMIN function (hidden from the users) to be able to directly go to the resource in CKAN to make edits if necessary.

**Comment by acorbi** [comment]
Closing, this belongs to https://github.com/OpenDevelopmentMekong/wpckan/issues/232

**Comment by acorbi** [comment]
REopening, it belongs here actually.
