### ISSUE TITLE
MAP Explorer: ODC Legends appear in Khmer even with English Chosen

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#174]
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/

Legends appear in Khmer even with English Chosen -- actually sometimes the legends are fully Khmer (label and items) sometimes just Labels... 

![legends-khmer](https://cloud.githubusercontent.com/assets/16559612/16962022/f341779c-4dbd-11e6-9d16-1a98c7820f51.JPG)

**Comment by acorbi** [comment]
@Huyeng this might be related to the issue on PROD

**Comment by Huyeng** [comment]
No, it is different. 
It caused by the CURRENT_LANGUAGE was not defined, so it has to replace with the function that you created.

**Comment by acorbi** [comment]
@Huyeng @jpeizer1 ok, im assigning myself this task.

**Comment by acorbi** [comment]
@Huyeng ok, you were faster. Just merged your PR. 

Issue fixed via e9a67720361753b2e23ce09123c2e5424359b1c7
