### ISSUE TITLE
MAP Explorer ODC: Formatting issues with Subgroup of themes

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#175]
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/

Please compare these items in pp and production ODC map explorer - There is an extra thin grey vertical line on the left margin in PP that makes this group of items look more separate and less connected. Production formatting of this group is better. 

PP
![extra-line](https://cloud.githubusercontent.com/assets/16559612/16962087/31f6210e-4dbe-11e6-9050-789d0c52ec8a.JPG)

Production
![prod-line](https://cloud.githubusercontent.com/assets/16559612/16962136/6035d67c-4dbe-11e6-9f07-0857b29232f5.JPG)

**Comment by acorbi** [comment]
Fixed via 2863a07ef0c827ed4c4e6e6cd7f092c63964655b
