### ISSUE TITLE
NEWS & Containers in General  10 boxes in a 12 box space

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#176]
As in the example below we have 10 boxes of news on a page that can clearly fit 12 and we have 279 pages of this -- meaning we have 558 blank spaces and if we had actually 12 spaces all filled in we'd have 46 less physical pages to rifle through. I notice this odd 10 box configuration in other areas like Topics as well although there are 12 spaces to fill.

![news-container](https://cloud.githubusercontent.com/assets/16559612/16974101/32d871f0-4e07-11e6-890c-b4e1fa642499.JPG)

**Comment by acorbi** [comment]
Fixed, the number of posts per page is specified in the Wordpress dashboard under **Settings > Reading** . I changed from 10 to 20

![screenshot from 2016-07-20 09-36-09](https://cloud.githubusercontent.com/assets/384894/16978694/92f67126-4e5d-11e6-91f5-e015acb2757d.png)
