### ISSUE TITLE
Switching Language: English icon disappeared

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#179]
On English page, the language icons for both languages are appeared, but the English icon disappeared on Khmer site. 
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/16982292/446421f2-4e99-11e6-8476-83aac80a68ac.png)

**Comment by acorbi** [comment]
Duplicated issue on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/123. Closing

**Comment by Huyeng** [comment]
I didn't find it before posting.
