### ISSUE TITLE
ODC Topics Missing From Main menu 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#192]
https://cambodia.pp.opendevelopmentmekong.net/topics

Only way I got to it was being in OD moekong Topics and switching to Cambodia to see the page

**Comment by acorbi** [comment]
hey jp, 
the pp sites are currently being configured from scratch as part of a editorial training with partners. all those menu items will be cobtinuosly added again. please hold on with issues reporting until further notice.
--
Gesendet von der myMail-App für Android Donnerstag, 21 Juli 2016, 09:22vorm. +02:00 von jpeizer1  notifications@github.com :

**Comment by acorbi** [comment]
Closing
