### ISSUE TITLE
Cleanup unused post taxonomies

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#199]
![screenshot from 2016-07-21 16-33-19](https://cloud.githubusercontent.com/assets/384894/17029889/6135f68c-4f6d-11e6-8d60-4a05c8deb67d.png)

Under **Posts** on  https://cambodia.pp.opendevelopmentmekong.net/wp-admin/ there are a series of post taxonomies that are probably not used anymore. Please review and cleanup those not needed.

**Comment by acorbi** [comment]
@Huyeng I assign this task to you. Please do once we rollout v2.0 (tomorrow)

**Comment by acorbi** [comment]
@Huyeng can you please take care of this one? I believe should rather quick to do...

**Comment by Huyeng** [comment]
Two taxonomies are deleted: old-category and ODC Homepage.

**Comment by acorbi** [comment]
ok, closing this then
