### ISSUE TITLE
WP1.3: Implement slide down sub menu for main menu items

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#20]
Menus at the top header should rely on wordpress menus configuration (under Appearance > Menus ) as much as possible. This task consist on:

- Adapting the code on **header.php** in order to implement the menu concept drafted on https://drive.google.com/open?id=0BymS3LWpLYfobEZjSmI5MjRtOW8 . All the layout work should focus on the **od-submenu** element, see https://docs.google.com/drawings/d/1PfiaqzK_1Pt7T3I3bWusZICY_oCKqgHwY-brZufHkVY/edit

- Allowing editors to specify which icon should be presented for each menu item https://premium.wpmudev.org/blog/add-icons-wordpress-menus/?utm_expid=3606929-67.-MP1PYYzS_6mvlSTiltv6Q.0&utm_referrer=https%3A%2F%2Fwww.ecosia.org%2Fsearch%3Fq%3Dhowto%2Bwordpress%2Bhamburger%2Bmenu%26region%3D%26lang%3D%26f%3Dfalse

- Take inspiration from http://wpmegamenu.com/megamenu/ in order to code different custom menu layouts (for topics, for news, etc...)  that then can be associated with menu elements by the editors. This layouts could be maintained in separate template files (e.g under /inc/menu-templates/)

- CSS adjustments should be done on a new file **_header-menu.less** that will be imported by **_header.less**

![screenshot from 2016-06-15 15-47-20](https://cloud.githubusercontent.com/assets/384894/16082052/7a984e82-3310-11e6-8e3c-e9f035dbca54.png)

**Comment by DragonVirus** [comment]
@acorbi While i searched for way to implement it. i found this https://www.maxmegamenu.com/ I have tested it and it does all we need. What do you think ?

**Comment by acorbi** [comment]
Max Mega Menu has been integrated, closing this issue.
