### ISSUE TITLE
Widescreen Issues

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#202]
Recent changes (to css formats?) have created issues with wide screens. The center frame is no longer centered and CONTENT API and RSS FEED now are at the far right margins. Home is still centered but Topics, news, profiles, stories all look like below:

![widescreen](https://cloud.githubusercontent.com/assets/16559612/17036512/96198b88-4f5a-11e6-9f3e-a09973685734.JPG)

**Comment by acorbi** [comment]
That white space on the right is the sidebar which will be populated with content once we finish configuring the pre-production sites. closing this issue
