### ISSUE TITLE
CONTACT FORM Orange Box

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#203]
I thought we were going to do away with this horrid little orange contact form box on the side that gets in the way of things and has previously caused vertical lines in some browsers -- and out that either on the bottom or top. Weren't we supposed to have like a little email icon at the top that would then open up the contact form? 

![orange](https://cloud.githubusercontent.com/assets/16559612/17036710/70ca2f8a-4f5b-11e6-801b-7e6173da76a9.JPG)

**Comment by acorbi** [comment]
Disabled. It got re-enabled after dumping the production DB contents into Pre-production. closing
