### ISSUE TITLE
Cleanup unsued pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#205]
On ODC and ODM wordpress dashboards, under **Pages > all pages** there are a series of draft and published pages that are unused and would need to be deleted.

@DBishton Im assigning this to you.

**Comment by acorbi** [comment]
@DBishton I assign this to you. Please do once we rollout v2.0 (tomorrow)

**Comment by DBishton** [comment]
@acorbi I have reviewed and deleted 14 unused pages on ODM.

@Huyeng , can you work with @ChandaraKhun to review and delete unused pages on ODC?

**Comment by acorbi** [comment]
Fixed
