### ISSUE TITLE
ODM Content taxonomy widget not expanding for child topics

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#207]
When you go to https://cambodia.pp.opendevelopmentmekong.net/topics/drought/, the tree view does not appear expanded.

![screenshot from 2016-07-22 09-26-54](https://cloud.githubusercontent.com/assets/384894/17049593/89fd7654-4fee-11e6-8d01-e797f496492c.png)

**Comment by S-mardii** [comment]
It works for me; you might recheck once again

**Comment by Huyeng** [comment]
It was fixed.
