### ISSUE TITLE
Open Mekong Site Showing Thailand

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#238]
Can't click on anywhere else but Thailand when i try different countries
![capture](https://cloud.githubusercontent.com/assets/16559612/17421049/ae07a836-5a74-11e6-8b5b-86d25339e457.JPG)

**Comment by jpeizer1** [comment]
This is happening again...

**Comment by acorbi** [comment]
@jpeizer1 @Huyeng I believe this happens during the automatic deployment process when we push new code to the master branch of the code repository and has been already reported on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/110, closing this issue
