### ISSUE TITLE
Update Format: Page Footer

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#251]
![screenshot 1](https://cloud.githubusercontent.com/assets/18528756/17513967/47337484-5e5a-11e6-903e-031f6cc8fc19.png)

**Comment by acorbi** [comment]
@S-mardii please indicate in detail the elements that need to be fixed and which improvements need to be done.

**Comment by S-mardii** [comment]
Hi @acorbi, Huyeng prefer to keep the same footer style as the old theme
![screenshot 1](https://cloud.githubusercontent.com/assets/18528756/17766572/f78c4728-6555-11e6-96ff-b306bdc956c5.png)

**Comment by acorbi** [comment]
oh I see, feel free to configure Max Mega Menu on http://cambodia.pp.opendevelopmentmekong.net/ for reflecting that style and proposing CSS changes as part of a Pull Request.

**Comment by S-mardii** [comment]
I have tried using Max Mega Menu to reflect this style, but I cannot find a way to make Max Mega Menu show all the sub-menu without hovering or clicking. Is there any way to do that?

**Comment by S-mardii** [comment]
I have pull a request (#256) to alter default footer menu style without using Max Mega Menu.

**Comment by acorbi** [comment]
@S-mardii I understand that we would then disable the Max Mega Menu for the footer menu right? Then with your PR the items will be rendered as wished?

**Comment by S-mardii** [comment]
Yeah you are right.

**Comment by acorbi** [comment]
fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/256
