### ISSUE TITLE
Remove filtering news by tags on theme settings

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#271]
With the new frontend, this functionality is not used anymore. 

![screenshot from 2016-08-15 17-30-16](https://cloud.githubusercontent.com/assets/384894/17669462/007ff680-630e-11e6-870b-a215eeb6ff6e.png)

**Comment by S-mardii** [comment]
@acorbi  Could you tell where this is presented on the site?

**Comment by S-mardii** [comment]
@acorbi found and deleted
