### ISSUE TITLE
Topic Page: Listed the related datasets on some topic pages are not related

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#273]
Currently, some page of topics list automatically the latest related dataset, library records, laws, publications rather than the related dataset.

Suggestion: for those topic pages that not manually add the related dataset, should list the related items based on the page name as the key words.

**Comment by acorbi** [comment]
@Huyeng For this we can use the WPCKAN related resources by post's category widget. closing this issue
