### ISSUE TITLE
Add The Election page to ODC New site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#274]
Since migration, the election page has not accessible yet on the new site.  
Create a menu item or page that allow users can access the election page.

**Comment by gimmemochi** [comment]
@DBishton You should support @ChandaraKhun in looking for a solution/proper content type for the ODC election page. ODC will be updating the page for the upcoming elections (2017 and 2018), I suppose. This is the same issue (#384) as identifying the content type for "ODC Forest cover studies 1973-2014). cc: @prustar

**Comment by Huyeng** [comment]
The menus are added main navigation, so the users can access to those page. 
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/21793711/47165e72-d726-11e6-8277-718c0cf5f90a.jpg)
