### ISSUE TITLE
Maps Explorer: Miss activated icons when layer is enable on maps explorer

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#275]
There is no icon to show the activated layers on map explorer.

**Comment by acorbi** [comment]
@Huyeng can you please provide more details about this issue? Thanks

**Comment by Huyeng** [comment]
Refer to this issue below:
![screenshot_14](https://cloud.githubusercontent.com/assets/6613530/18424149/e46ab1e0-78d6-11e6-94f1-3dfce546aadf.png)

However, i fixed before deploying for a while, it has not closed automatically after merging. 
I close it now.
