### ISSUE TITLE
Necessary to use strip_tags for widget's title??

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#278]
Currently, while storing the widgets title, the strip_tags function is called which then disables multilingual functionalities for the widgets. This is breaking the possibility of setting the title in newly-added widgets.

Example on https://github.com/OpenDevelopmentMekong/wp-odm_theme/blob/master/inc/widgets/odm-custom-posts-widget.php#L181

@Huyeng I could only reproduce this in my dev env which might have another language config as PP. In PP the current code seems to be working fine so I do not know id this is actually an issue.

I have created following PR which proposes a code change: https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/279

Let's discuss over there whether my PR should be merged.

**Comment by acorbi** [comment]
@huyeng ping

**Comment by Huyeng** [comment]
No. You can remove it.
