### ISSUE TITLE
Enhance profile pages to be more responsive  

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#282]
Same as https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/276
![screen shot 2016-08-16 at 17 28 25](https://cloud.githubusercontent.com/assets/384894/17704928/ddd8f3d8-63d6-11e6-8ecc-a808fbbd9cb5.png)

**Comment by DragonVirus** [comment]
Which page exactly is the one in the screenshot ? Seem like the table problem in responsive view is already fixed.

**Comment by acorbi** [comment]
@DragonVirus should be any profile page, example: https://cambodia.pp.opendevelopmentmekong.net/profiles/economic-land-concessions/

Please coordinate with @Huyeng who is working on the profiles to not duplicate work

**Comment by Huyeng** [comment]
@DragonVirus, are you working on this? If not, i will take care it while I'm working on profile page with other issue.

**Comment by DragonVirus** [comment]
Thanks @Huyeng. I will leave it to you then. :)

**Comment by acorbi** [comment]
assigning @Huyeng to this issue then
