### ISSUE TITLE
Enhance topic pages to be more responsive

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#283]
Embedded iframes and images should be automatically adjusted to the screen's width.

![screen shot 2016-08-16 at 17 27 29](https://cloud.githubusercontent.com/assets/384894/17704960/fa97857a-63d6-11e6-9e84-02bb2d5add1f.png)

**Comment by acorbi** [comment]
reopening this Issue, still not 100% responsive, see example: opendevelopmentmekong.net/topics/agriculture-and-fishing/

**Comment by S-mardii** [comment]
Please send the link of Cambodia's topic page above.

**Comment by acorbi** [comment]
@S-mardii this is how it looks in my phone, android OS both firefox mobile and Chrome

![photo_2016-09-15_16-43-02](https://cloud.githubusercontent.com/assets/384894/18554142/861c9d44-7b63-11e6-8040-c09f85b6dc90.jpg)

**Comment by S-mardii** [comment]
@acorbi  I see

**Comment by acorbi** [comment]
Fixed
