### ISSUE TITLE
Background color of menu on mobile

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#284]
Is white so text cannot be read, it should be the same as the menu on desktop.

![screen shot 2016-08-16 at 17 28 01](https://cloud.githubusercontent.com/assets/384894/17704976/0af85e4e-63d7-11e6-96d9-2a41a540bd5a.png)

**Comment by DragonVirus** [comment]
@acorbi i will work on it.

**Comment by acorbi** [comment]
@DragonVirus awesome, thanks! assigning you this issue....
