### ISSUE TITLE
Error of the cache memory

### ISSUE THREAD

**Issue by ngohaily** [OpenDevelopmentMekong/wp-odm_theme#286]
Hi everyone,
I make one issue here if any body meet it
Sometimes the Vietnam page is pointed to another page even the domain name is the vietnam.opendevelopment
![blob](https://cloud.githubusercontent.com/assets/19347288/17728833/54582a88-648b-11e6-96c4-ae65cc50f08a.png)
Additionally, when we posted some news which is displayed in the page but next day when we open the page the news isnt displayed even the data still is stored on the server
For example:
 
![cu](https://cloud.githubusercontent.com/assets/19347288/17728916/ca2b06fe-648b-11e6-871c-482c24001565.png)
it's the news of date 5/08/2016 but today is 17/08/2016
but when i open dashboard and update the news it will display on the page on my computer
![moi](https://cloud.githubusercontent.com/assets/19347288/17728952/fa43ff3a-648b-11e6-9e88-e35230877cdb.png)
 but when i open the page on another computer. the page return the old page (date 5/08/2016)

**Comment by acorbi** [comment]
thanks @ngohaily for reporting this, I will look at the issues later today.

**Comment by acorbi** [comment]
This is now fixed
