### ISSUE TITLE
"Popular" Label

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#293]
Suggest another word or phrase to replace "Popular" in the label titles of data page like "Most Searched for" or something like that.

Since popular also means "regarded with favor, approval, or affection by people in general" you get into an uncomfortable situation when you have 'Popular' Laws or Decrees selected that are in fact not popular at all... what they really are is most viewed, most selected, etc..

![capture](https://cloud.githubusercontent.com/assets/16559612/17842351/04857570-67f0-11e6-9841-54a8f7edb1bb.JPG)

**Comment by acorbi** [comment]
@prustar any ideas for better wording? Most viewed datasets/library records/laws would be my favorite.

**Comment by jpeizer1** [comment]
Agreed MOST VIEWED is best.
