### ISSUE TITLE
Create a new template for home profile page.

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#295]
ODC will have a new project that will be place under profile session, but the template is different from current profile and it also has the several sub page as template below. Thus, the new templates profile need to create.
![public-services-page-template-2](https://cloud.githubusercontent.com/assets/6613530/17844591/2d9c2042-6865-11e6-84b0-5ebc00d5926e.jpg)

**Comment by acorbi** [comment]
Closing since it belongs https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/issues/19

**Comment by Huyeng** [comment]
You are right.
