### ISSUE TITLE
Create the widget areas for profile page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#296]
Create widget area to be able to present the related laws, resources, news and other on profile page
- Profile Area Left
- Profile Area Bottom Left
- Profile Area Bottom Right

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/commit/f083b39ff2b42af4444575cc33682cf76f246164 
@Huyeng  Remember to specify the text ```Fixes #ISSUE_NR``` (example Fixes #296) as part of the commit/PR message so the issue gets automatically fixed when the PR is merged.
