### ISSUE TITLE
The display errors of the language pages

### ISSUE THREAD

**Issue by hailyodv** [OpenDevelopmentMekong/wp-odm_theme#299]
Hi everyone,
In fact now, we have the errors of language display. Vietnam open development have 2 pages: english and vietnamese. But now there are the posts (or news) in english are displayed in the vietnamese page or reserve the news in vietnamese is displayed in the english page. So could you help us fix this error, please? Thank you very much!
This is the vietnames page
![englishpage](https://cloud.githubusercontent.com/assets/21078816/17878632/8e49cc26-6916-11e6-90d2-ee5fe985e2af.png)

This is the english page
![englishpage1](https://cloud.githubusercontent.com/assets/21078816/17878666/d1b82598-6916-11e6-9c3e-7d7abe9c1061.png)

**Comment by acorbi** [comment]
Hi  @hailyodv the Issue you are raising relates to the current theme (v1.0) deployed in production and therefore to another github repository. I have moved your issue to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/1009. Closing this one.

In the next days we are going to deploy the new theme (v2.0) which is currently deployed in pre-production, please make sure that you get familiarized with it on https://vietnam.pp.opendevelopmentmekong.net.
