### ISSUE TITLE
Add post layer meta box of map post type into the profile post type too if exist

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#301]

**Comment by acorbi** [comment]
@huyeng please specify more detailed description of the issue, with screenshots if possible.

**Comment by acorbi** [comment]
@Huyeng please specify details on this Issue, otherwise nobody knows what it is about

**Comment by acorbi** [comment]
@Huyeng please specify details on this Issue, otherwise nobody knows what it is about

**Comment by Huyeng** [comment]
Sorry for that. The idea is that I would like to add the metabox of layer as below for profile page. 
For instance, a profile SEZ page is creased, which needs the map of SEZ to present on the profile page. 
The map of SEZ  is aleady added as a layer for map explorer, so the idea just would like to retrieve all the layers that added and provide ability for the mapper and editor to add any layer that belong to the profile page.  Currently, they need to go to edit and copy the layer url  then add to the profile page.
Does it make sense?
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/18424090/4a10b0e0-78d6-11e6-9499-71d8f9020a9e.png)

**Comment by Huyeng** [comment]
It have done long time ago.
