### ISSUE TITLE
Khmer text not wrapping everywhere

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#310]
https://cambodia.pp.opendevelopmentmekong.net/km/

![screenshot from 2016-08-25 09-43-01](https://cloud.githubusercontent.com/assets/384894/17960780/684f8f04-6aa8-11e6-8e96-3f70f147e894.png)

**Comment by S-mardii** [comment]
To deal with this, I think we need to wrap the word in "Text" instead of "Visual".

![screenshot_1](https://cloud.githubusercontent.com/assets/18528756/17964060/7dcd58ae-6ae2-11e6-92c5-d480f208b625.png)

**Comment by acorbi** [comment]
Hey @S-mardii . True, that would work but involves an editorial-based solution. This Issue proposes the need of an code-based fix which I would like to explore first. Do you have any ideas on how to fix this with CSS?

**Comment by S-mardii** [comment]
I have no idea on this yet. If I go across any possible method, I will let you know.

**Comment by S-mardii** [comment]
@acorbi I am doing some searching on this issue and found this one. https://github.com/tinymce/tinymce/commit/a9561a4c19544bdca6cf7e289bf38e268f2ea309

However, I don't really understand about this

**Comment by S-mardii** [comment]
@acorbi  after my searching I have found this one https://github.com/tinymce/tinymce/commit/1696e387e818d9c3f4e2e2d8871f0218208a0212

I downloaded it and test replacing with the existing Tinymce in wp-includes/js in my local code. I noticed that Khmer text is well wrap as the zero width space have not been stripped off by WP. However, after replacing, visual text editor is disable.

I believe a right changing on the code there would solve the problem. I think you can help on this.

**Comment by S-mardii** [comment]
Also there is a proposed solution here. http://www.sbbic.org/2016/08/24/fix-khmer-zero-width-space-issue-wordpress/

**Comment by acorbi** [comment]
Amazing @S-mardii will check it out as soon as I can

**Comment by S-mardii** [comment]
@acorbi  I had as them for some details and I am informed as following:

http://www.sbbic.org/2016/08/24/fix-khmer-zero-width-space-issue-wordpress/#comment-4536

**Comment by Huyeng** [comment]
All the Khmer texts that editor posted are already wrapped, however, the WP has stripped out all the zero-width space of Khmer unicode when post or visual editor is switched to. 
The zero width space is the Khmer Unicode special character that represents a hidden space to separate each word.
A thing to fix this, we need to update tynimce javascript in wp-include. However, it is not the base approved. The issue will be happened again when the version of wp will be upgraded.

**Comment by Huyeng** [comment]
@acorbi, I would like to update the tinimce.js in wp-include to avoid stripping out the zero-width space of Khmer texts that already wrapped. What do you think? It is not the best way to solve the wrapped Khmer texts issue, but it is very helpful for ODC editors, otherwise, they need to edit and fix the wrapping texts on topic pages and news again and again.

**Comment by Huyeng** [comment]
It works fine after updating the tinymce file. 
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/18629957/737fc3c2-7e93-11e6-9b3b-e590d3bdc932.png)

**Comment by acorbi** [comment]
@Huyeng @S-mardii as you can see, besides the hack that we have been discussing today, I have done the following change on https://github.com/OpenDevelopmentMekong/wp-odm_theme/commit/2a827de32175a95ac65a4e8adcceb4dbc4d98298 in order for the khmer texts to wrap properly on firefox (which was not the case )

**Comment by acorbi** [comment]
There is still an issue under Firefox though which is not critical but it is not nice. Currently words in english are being chopped after any character:
![screenshot from 2016-09-19 16-53-44](https://cloud.githubusercontent.com/assets/384894/18636972/1f570434-7e8b-11e6-9771-6ddeeda3b4a0.png)
