### ISSUE TITLE
Better layout for "Summary translated by ODC team" notice

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#324]
On news articles, and potentially other content types, a **"Summary translated by ODC team"** message is presented when the summary in English was translated by the ODC Team.

Currently, this message has a grey background and does not fit visually with the way other metadata ( categories, tags, modification date) is presented.

![screenshot from 2016-08-30 10-23-46](https://cloud.githubusercontent.com/assets/384894/18081739/eaa3ccc6-6e9b-11e6-9039-4d390f0c1df5.png)

Suggestion would be to show this message **in-line** after the tags and to prepend a fontawesome icon (suggestion http://fontawesome.io/icon/pencil/) to the left.

**Comment by S-mardii** [comment]
Is this the layout you suggested?
![screenshot 1](https://cloud.githubusercontent.com/assets/18528756/18461219/e7832814-79a1-11e6-8f00-798186d27974.png)

**Comment by acorbi** [comment]
@S-mardii Exactly! that would be perfect. can you implement? For doing that, please add the corresponding logic into the **echo_post_meta** function on **/inc/utils/content.php**

**Comment by S-mardii** [comment]
@acorbi  Oh I have just seen you comment after make the pull request. Okay, I will update on **echo_post_meta**

**Comment by S-mardii** [comment]
@acorbi oh well, I just forgot that I have worked on it already. You can review my pull request

**Comment by S-mardii** [comment]
@acorbi then we can close this issue. Cheers

**Comment by acorbi** [comment]
CLosing...
