### ISSUE TITLE
Header// put the country selector label alphabetical order 

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#329]
![screenshot_1](https://cloud.githubusercontent.com/assets/18528756/18116764/ab89e6cc-6f74-11e6-9b61-9fb53c43875a.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/S-mardii/wp-odm_theme/commit/be69549dd9d4d0bb8adccd5e302d89ef3990c850
