### ISSUE TITLE
Links to sources not being translated

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#334]
![home-km-3](https://cloud.githubusercontent.com/assets/384894/18118510/8378dea0-6f55-11e6-9e0d-f49b3a21135d.png)

**Comment by Huyeng** [comment]
The issue is not different from this issue: https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/334

**Comment by acorbi** [comment]
@huyeng i think ypu have specified the same issue number 334. do you mean another issue?

**Comment by acorbi** [comment]
@Huyeng maybe you mean #342

**Comment by acorbi** [comment]
Fixed on PP by creating a dump of wp_2_options table and doing a search and replace operation on vim () with ```%s/\"kh\\/\"km\\/g``.

@huyeng, can you please test that it is now fixed on PP?
- frontend: https://cambodia.pp.opendevelopmentmekong.net/km/announcements
- dashboard: https://cambodia.pp.opendevelopmentmekong.net/wp-admin/edit-tags.php?taxonomy=layer-category

**Comment by Huyeng** [comment]
Awesome! it looks every item of taxonomy is translated.

**Comment by acorbi** [comment]
Closing, fixed via DB operation
