### ISSUE TITLE
Data from other countries in Myanmar site

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/wp-odm_theme#335]
![capture](https://cloud.githubusercontent.com/assets/20394487/18120309/ed04ec90-6f84-11e6-8f9b-749f72b25f57.PNG)

Only Myanmar-specific data should be seen in data page.

**Comment by DragonVirus** [comment]
@thetaung2 we just need to specify that in data page. I just edited the page. 

@acorbi you can close this issue.

**Comment by acorbi** [comment]
This has been fixed via f5c0a4bbb32465c0905509546e2ee977c55c4ef2
