### ISSUE TITLE
Want to update "Other Myanmar Resources"

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/wp-odm_theme#336]
![capture](https://cloud.githubusercontent.com/assets/20394487/18120414/721080ac-6f85-11e6-9a9b-98b72c523acd.PNG)

We will update this to include all the links to Gov: Ministries

**Comment by acorbi** [comment]
@thetaung2 this can be solved via editorial workflow. Please check with @DBishton on how to add more entries on that section. Closing this issue.
