### ISSUE TITLE
Warning: array_count_vavlues() in profile session

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/wp-odm_theme#338]
https://myanmar.opendevelopmentmekong.net/profiles/oil-and-gas-blocks/
https://myanmar.opendevelopmentmekong.net/wp-admin/post.php?post=295&action=edit

![capture](https://cloud.githubusercontent.com/assets/20394487/18120589/6a359d26-6f86-11e6-8940-f2bcdd2b078d.PNG)

We have this issue with our profile page.

**Comment by acorbi** [comment]
@thetaung2 checking

**Comment by acorbi** [comment]
Fixed via 4a824d13317596fd5699489199a76d0e7a44f5f9
