### ISSUE TITLE
Extend the width and descrease line-height of dropdown menu

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#340]
The width of sub-menu should be larger, and the light high of texts should be smaller. 

![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/18123194/05bef336-6f97-11e6-877b-9a3228dbe082.png)
![screenshot_9](https://cloud.githubusercontent.com/assets/6613530/18123193/05bad59e-6f97-11e6-845c-4f60d2c72eaf.png)

**Comment by acorbi** [comment]
@Huyeng this can be done by tweaking the width of the menu under **Appearance > Menus**.

**Comment by Huyeng** [comment]
What do you mean tweak the width?

**Comment by acorbi** [comment]
To do so:

1. Head to the wordpress dashboard
2. Under **Appearance > Menus** click on the "mega menu" button to open the advanced configuration options
3. Under the **Mega menu** section, select **Mega menu** for the submenu display mode option
4. increase the width taken by each of the menu items

![screenshot from 2016-08-31 11-37-02](https://cloud.githubusercontent.com/assets/384894/18123710/604bd346-6f6f-11e6-8e3f-94cf4a16a8c6.png)

**Comment by Huyeng** [comment]
It doesn't reply to what we need as they are shown inline. 
Anyways, I noticed that the styling on menu is not the same as PP. 
Line-height is too large that made users be confuse a menu item as two item.

**Comment by acorbi** [comment]
@Huyeng ok, im changing the title of this issue to reflect the request of decreasing the line-height on the submenu items and reopen the issue

**Comment by acorbi** [comment]
@Huyeng Actually, the wished layout can be achieved just by configuring the menus. Basically, by setting ** Sub menu width** property under **styling**.

![screenshot from 2016-08-31 17-50-09](https://cloud.githubusercontent.com/assets/384894/18135855/a109299a-6fa3-11e6-8d61-c327e78b2036.png)
