### ISSUE TITLE
All custom taxonomies don't tranlated in Khmer

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#342]
Changing language code from kh to km may affect to the translated Khmer of custom taxonomies.  
![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/18125950/2c76b17e-6fa3-11e6-8ccc-729dfbcbb469.png)

**Comment by Huyeng** [comment]
On Map explorer 
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/18126003/6636813c-6fa3-11e6-917a-b0cf5da656d6.png)

**Comment by acorbi** [comment]
Fixed on PP by creating a dump of wp_2_options table and doing a search and replace operation on vim () with ```%s/\"kh\\/\"km\\/g``.

@huyeng, can you please test that it is now fixed on PP?
- frontend: https://cambodia.pp.opendevelopmentmekong.net/km/announcements
- dashboard: https://cambodia.pp.opendevelopmentmekong.net/wp-admin/edit-tags.php?taxonomy=layer-category

**Comment by ChandaraKhun** [comment]
I noticed that the issues were fixed.
But make sure the format "author" & "link" to the news sources remain consistent.

**Comment by acorbi** [comment]
@ChandaraKhun thanks for feedback.

> But make sure the format "author" & "link" to the news sources remain consistent.

What do you mean by this? If there is any issue with that, please open a new github issue with details on what is wrong and how it should look like

**Comment by Huyeng** [comment]
I noticed that all most of the taxonomy's translation are fixed, but there an error was found. 
- Miss translated texts: 
![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/18309561/4684f8ce-7524-11e6-8562-bab40f3d5ba2.png)

For this string, we can translate it manually fix, but i'm not sure if there any errors has found.

**Comment by acorbi** [comment]
@Huyeng All the previously available translations should be now deployed. Please modify that one manually and re-open this issue (or open a new one) if this issue reapers. Im closing this Issue and https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/334 now
