### ISSUE TITLE
Major Menu issues

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#344]
I tried to log in today to determine progress towards new version update on Dell PC Windows using firefox -- This is what I saw simply opening: https://opendevelopmentmekong.net/ - The menu is just opened to topics vertically showing all of the selections  with broken icons

<img width="960" alt="odm-menu" src="https://cloud.githubusercontent.com/assets/16559612/18134458/77b4dcec-6f6c-11e6-80c1-bc413d15abef.png">

ODC menu has heavy lines framing each selection and drop downs are unworkable, behind other objects etc...

<img width="960" alt="odc-menu" src="https://cloud.githubusercontent.com/assets/16559612/18134472/80068c24-6f6c-11e6-96b4-988656f64572.png">

**Comment by acorbi** [comment]
hi @jpeizer1. thanks for raising the issue. It is alreadyy being fixed. Im currently adapting the automatic deployment scripts which caused that issue.
