### ISSUE TITLE
Data screens displaying incorrect info

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#345]
Looking at what appears on data:
https://myanmar.opendevelopmentmekong.net/data/  and on all the country data search screens -- even with the country name filled in by default -- the same number of datasets, library and law records are appearing for each country. and the same data seems to be dsiplayed under it as well.

<img width="960" alt="number-sets" src="https://cloud.githubusercontent.com/assets/16559612/18136126/3fdbbc2c-6f72-11e6-9376-843603ed0202.png">

 what is being shown is not specific to the country its being shown for

I've got Cambodian laws as most viewed in MYANMAR - and data on vietnam and thailand showing.

<img width="960" alt="data-myanmar" src="https://cloud.githubusercontent.com/assets/16559612/18136258/a3cbd4d8-6f72-11e6-8268-bd59dad232c2.png">

**Comment by acorbi** [comment]
@jpeizer1 jep, the filter was not being applied on the first screen presented, where the most viewed resources are shown. now is fixed
