### ISSUE TITLE
Inconsistencies in localizations of titles in topic pages widget

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#350]
In topic pages such as https://cambodia.opendevelopmentmekong.net/topics/development-policies-and-administration/?ct=t(OD_Network_Newsletter_Issue_1_8_2016) the titles of the widgets present following inconsistencies:

## When english language is selected

- Some titles appear in khmer

![screenshot from 2016-09-01 09-32-26](https://cloud.githubusercontent.com/assets/384894/18159081/513d5ac4-7027-11e6-98f9-dd00f9123b23.png)

## When khmer language is selected

- Some titles appear  in english
- the title for "related laws" reads "related datasets"

![screenshot from 2016-09-01 09-32-46](https://cloud.githubusercontent.com/assets/384894/18159101/681567a0-7027-11e6-938f-287814d14f21.png)

this issue needs to be fixed from an editorial perspective by setting the correct translations on the corresponding widgets areas under **Appearance > Widgets** on https://cambodia.pp.opendevelopmentmekong.net/wp-admin/widgets.php

@ChandaraKhun @Huyeng im assigning this to you. @DBishton please coordinate also with other partners so this is properly done on other country sites as well

**Comment by Huyeng** [comment]
The posts of related news list not correctly since the news article moved to the News post type.

**Comment by acorbi** [comment]
@Huyeng that is another Issue. We should keep the discussion focused on the issue raised, which in this case involves setting the corresponding widget titles for both languages. 

Please open a separate one if it is needed to address the issue you raised

**Comment by Huyeng** [comment]
Done!

**Comment by acorbi** [comment]
Awesome. thanks!
