### ISSUE TITLE
Fatal error when accessing ODMm land topic via country navigator

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#356]
Fatal error: Call to undefined function qtrans_use() in /var/www/html/wp-content/themes/wp-odm_theme/inc/utils/content.php on line 18

https://myanmar.opendevelopmentmekong.net/topics/land/

Accessed via the highlighted menu button from ODM land page

![image](https://cloud.githubusercontent.com/assets/1206387/18167333/372158d6-707a-11e6-8f40-d65e3f19f320.png)

**Comment by acorbi** [comment]
Issue already reported on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/337. Closing...
