### ISSUE TITLE
The links of the layer items on Map catalogue not working properly

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#360]
On the map catalogue is the place where users can download different kind of map data.
It is assumed that all the layers on map catalogue have resource stored on ckan, so when we click on the any title of layer, it should point to the data page.

For example: 
Aqueduct Atlas – Available Blue Water :  https://cambodia.opendevelopmentmekong.net/dataset/?id=cambodian-aqueduct-atlas

However, click on Access to Public Transport, it pointed to the page that contain only the image: 
https://cambodia.opendevelopmentmekong.net/layers/bus-lines/
Actually, it should point to https://cambodia.opendevelopmentmekong.net/dataset/?id=public-transportation

**Comment by acorbi** [comment]
@Huyeng How is the related dataset (the value for the id parameter on the link's URL) stored on the corresponding map?

**Comment by Huyeng** [comment]
Of course, the id parameter. However, the all layers that show up on the map catalogue are not the layer at all, some are sub categories (group of the layer) that do not container any post meta. For example, all the ELC layers are grouped by the sub category named Economic land concession.  On the map catalogue, it is expected to display only the Economic Land concession that will point to data page to download all the layers of ELC.
