### ISSUE TITLE
Provide the option to show the announcement message on the header of site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#361]
It is very important option for each OD site to be able to announce any message to the user on top as below:
![screenshot_14](https://cloud.githubusercontent.com/assets/6613530/18191649/f5d420ac-70f6-11e6-86b0-8c94db0ddbaf.png)

**Comment by acorbi** [comment]
@Huyeng thanks for raising this. The part of the code outputing the message was unintentionally removed, needs to be re-added.
