### ISSUE TITLE
Profile page: Error with get_the_language_by_site()

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#362]
Warning: Missing argument 1 for Odm_Language_Manager::get_the_language_by_site(), called in /var/www/html/wp-content/plugins/wp-odm_profile_pages/post-types/profile-pages.php on line 127 and defined in /var/www/html/wp-content/themes/wp-odm_theme/inc/language-manager.php on line 48

![screenshot_15](https://cloud.githubusercontent.com/assets/6613530/18196079/80a86504-7119-11e6-8f36-4f2bd872e27c.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/commit/bf2710314e92fa831c1ebc607fe3ea78c8133a73
