### ISSUE TITLE
Vietnam Topics Almost all 404 Errors

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#368]
Only topic no a 404 is Environment and land
But it displays a LAND Subtopic:  https://vietnam.opendevelopmentmekong.net/topics/land/

The problem is there is also a topic called LAND listed on the Topic menu and that also displays a 404 even though https://vietnam.opendevelopmentmekong.net/topics/land/  exists....

**Comment by acorbi** [comment]
This is something for the @OpenDevelopmentMekong/editorial  team. Please check:

- The configuration of the Topics is correct: https://vietnam.opendevelopmentmekong.net/wp-admin/edit.php?post_type=topic
- The configuration of the menu item **topics** is consistent: https://vietnam.opendevelopmentmekong.net/wp-admin/nav-menus.php?action=edit&menu=9

**Comment by DBishton** [comment]
Topics shouldn't be being displayed at all, as with the exception of "Land", they are not ready for public viewing. I have removed the topics item and links to topic pages from the menu. Currently the land topic still displays in the homepage widget. I will discuss further configuration this afternoon as we have a call on editorial issues and launch readiness.

**Comment by acorbi** [comment]
Then we close this issue
