### ISSUE TITLE
Make column width wider on profiles table

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#369]
https://vietnam.opendevelopmentmekong.net/profiles/danh-sach-cac-thuy-dien-tai-viet-nam-tinh-den-thang-062016/

![screenshot from 2016-09-03 12-00-16](https://cloud.githubusercontent.com/assets/384894/18224192/1aaaba58-71ce-11e6-92af-2fe7abb9ff69.png)

This Title: Sản lượng điện trung bình hàng năm (triệu kWh) 

 is so long and narrow that on my laptop its impossible to see more than one row of data when scrolling. Either the title has to be shorter or the column wider so its reduced 

Why not just make the columns wider for this and these other long titles because they limit seeing the actual data 

	
Tổng vốn đầu tư (tỷ VND)
	
Năm khởi công
	
Năm (dự kiến) vận hành
	
Khu Bảo tồn Thiên nhiên bị ảnh hưởng
	
Số dân Tái định cư (hộ dân)

**Comment by acorbi** [comment]
Changing title to "Make column width wider on profiles table"
![screenshot from 2016-08-31 12-54-05](https://cloud.githubusercontent.com/assets/384894/18224191/01c83650-71ce-11e6-98ed-d3aa9a86fdb7.png)

**Comment by acorbi** [comment]
Closing, belongs to https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/issues/38
