### ISSUE TITLE
Enhance social media sharing

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#376]
When sharing the post on Facebook, some posts show information not correctly.
Suggestion: Add the Open Graph tags to determine what information to display:

    Title of post
    Description should be the content of post
    Image should be the feature of post

**Comment by Huyeng** [comment]
The Open Graph tags are already used on the old theme, but not new theme. I will copy and paste to new theme.

**Comment by acorbi** [comment]
thx @huyeng, please assign yourself the task then
--
Gesendet von der myMail-App für Android Montag, 05 September 2016, 09:18vorm. +02:00 von Huyeng  notifications@github.com :
