### ISSUE TITLE
call to undefined function on ODC Forest cover issue

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#383]
On https://cambodia.opendevelopmentmekong.net/issues/forest-cover/

![screenshot from 2016-09-05 17-59-11](https://cloud.githubusercontent.com/assets/384894/18253111/7aa9f1d8-7392-11e6-9442-60cba1612509.png)

Function ```wpckan_odm_get_related_datasets``` is not exposed by wpckan anymore. replace with proper exisiting call.

**Comment by Huyeng** [comment]
The error has gone after the code is released.
