### ISSUE TITLE
ODC Forest cover issue. Exposed somewhere?

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#384]
@Huyeng Currently, the ODC Forest cover issue code maintained under **Cambodia/** is not exposed anywhere on the site. What is the plan for this? Should it be added somewhere (i.e from the menu)? Currently, there are 2 issues related to them: https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/383 & https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/288

I know this is a legacy content type from ODC (created via Magic Fields), but what are the plans for the **Issues** (such as this forest cover issue). Mind the **/issues/** part of the URL: https://cambodia.opendevelopmentmekong.net/issues/forest-cover/

@DBishton please coordinate this with ODC's editorial team

**Comment by prustar** [comment]
@acorbi @Huyeng @DBishton --- I raised this issue back in January 2016. 

The Forest Cover content should be placed under the taxonomy FOREST, not really complicated at all.

**Comment by Huyeng** [comment]
Forest cover contains several sub-pages that is different from other topic pages.
After discussion with the team, ODC will add the forest cover under the profile page.
