### ISSUE TITLE
Draft layers showing on map explorer #370  - Couldn't reopen issue But problem Still Present

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#385]
https://myanmar.opendevelopmentmekong.net/map-explorer/

Please someone actually check issue to see if its resolved before closing... BTW I pressed CTRL+F5 before reporting

![capture](https://cloud.githubusercontent.com/assets/16559612/18253558/a3d0d7a4-7363-11e6-8319-4012cea95a4a.jpg)

**Comment by acorbi** [comment]
@jpeizer1 the Issue was fixed but only deployed on PP. Which is the environment we use to test bugfixes and/or feature request before staging them to PROD by tagging a release. In this case, the bugfix was not deployed yet into production, but now is... CLosing this issue

**Comment by acorbi** [comment]
For reference: You can find releases with changelog on https://github.com/OpenDevelopmentMekong/wp-odm_theme/releases
