### ISSUE TITLE
Search Result Formatting Issue 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#392]
This is a minor formatting issue but will make things look better -- can we put some white [background] space between the black background label (in this case TOPICS) and the title label immediately after it? It appears actually that the black background Label actually has an extra space after it but the problem is its in black as well rather than white. I think it would also look a bit better if the date immediately after it on the next line had a bit more space between it and the TOPIC label - not an entire line just a little more space between rows if its possible to do it in CSS by a small amount.
![capture](https://cloud.githubusercontent.com/assets/16559612/18281375/a9d942fe-742a-11e6-8817-de0f1122d3b3.jpg)

https://opendevelopmentmekong.net/?odm_advanced_nav=1&odm_filter_=1&odm_filter_s=land&odm_filter_post_type%5B%5D=profiles&odm_filter_post_type%5B%5D=topic&odm_filter_date_start=&odm_filter_date_end=

**Comment by acorbi** [comment]
@S-mardii you are good working with CSS, could you please implement this visual enhancement?

**Comment by S-mardii** [comment]
@acorbi I will check it out
