### ISSUE TITLE
Map Explorer: Info windows hidden by header 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#393]
![image](https://cloud.githubusercontent.com/assets/14996905/18287205/6f6e0e3c-7476-11e6-9e11-3f8b671ce185.png)

The close button is hidden by the header and I can't seem to scroll or move it to be able to close the info window.

**Comment by Huyeng** [comment]
@prustar - could you please check if the issue is fixed?

**Comment by acorbi** [comment]
@prustar, please check and close if fixed

**Comment by Huyeng** [comment]
I thought that the issue is no longer exist.
