### ISSUE TITLE
Enhance styling of 'On this category' widget

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#395]
Currently the 'On this category' widget displays items of the chosen content type and category in a list of URLs. 

![image](https://cloud.githubusercontent.com/assets/1206387/18300938/a4e9dc72-74f7-11e6-90da-cafd875d89b1.png)

Please enable styling options available on "ODM custom posts" widget -- grid or list layout, 1,2, 4 or 8 columns.

![image](https://cloud.githubusercontent.com/assets/1206387/18301087/e2c6d850-74f8-11e6-9c2d-802e1c81725c.png)
co

**Comment by DBishton** [comment]
Hi @acorbi, could you give an ETA for this one? Having access to these styling options is important for testing widget presentations and preparing the water governance material.

**Comment by acorbi** [comment]
Sure, this one should be easy. Let's say it will be ready by wednesday
