### ISSUE TITLE
Allow full width image/embed styling

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#397]
Please implement the functionality to allow embedding of items that occupy full screen width. Currently there are margins:

![image](https://cloud.githubusercontent.com/assets/1206387/18301606/04780808-74fd-11e6-80f6-fa4ac37e134e.png)

This formatting option should also be available for uploaded media (e.g. images). Ideal implementation would look similar to: 

![image](https://cloud.githubusercontent.com/assets/1206387/18301636/39fb8a68-74fd-11e6-88e6-a5c329a3e0c2.png)

**Comment by acorbi** [comment]
@DBishton you can add the **full-width** class to any <img> element added to a post content under the **text** view of the post's editor. I did so with an image I added on this test story on PP. https://pp.opendevelopmentmekong.net/stories/test-story/

![screenshot from 2016-09-15 18-45-25](https://cloud.githubusercontent.com/assets/384894/18558801/c51b335a-7b74-11e6-8b03-6f5ab1312b6f.png)

would this work?

**Comment by DBishton** [comment]
Hi @acorbi, 

This definitely sounds like it would work in the short term.

However, it appears to be constrained by the new text margins currently:

Screenshot from test story on pp: 

https://pp.opendevelopmentmekong.net/stories/test-story/

![image](https://cloud.githubusercontent.com/assets/1206387/19849820/bc5b8328-9f87-11e6-881e-80101905b484.png)

**Comment by acorbi** [comment]
@DBishton I have one idea, which might not fullfil your requirements completely but could be a good middle-ground solution without complex code re-structuration.

How about we tweak the template of the story pages so the **Featured image** associated with it, appears full-width on the top of the story. The rest of the images added to the contents of it would then NOT take the whole width as pictured in your screenshot above.

If this is enough for now, I could implement it pretty quickly.

**Comment by DBishton** [comment]
@acorbi My apologies, I didn't realise this one was in my court. Let's go ahead with this as an interim step, it will help assess if further enhancements are necessary.
