### ISSUE TITLE
display Errors of news

### ISSUE THREAD

**Issue by hailyodv** [OpenDevelopmentMekong/wp-odm_theme#401]
Hi everyone,
I found an errors with the news on the vietnamese site. Today is 7/09/2016. We have publish the news  since 6 hours ago 
![untitled2](https://cloud.githubusercontent.com/assets/21078816/18307594/618b7282-751b-11e6-90a6-c0f7e9eb6420.png)
 but on the website, the news displayed old news

![untitled1](https://cloud.githubusercontent.com/assets/21078816/18307645/77d34ce0-751b-11e6-9b0f-5b3e7f9a0105.png)
 Please check it to me ! 
Thank you very much!

**Comment by acorbi** [comment]
@hailyodv the reason for this is caching. On my side is showing up correctly:

![screenshot from 2016-09-07 11-59-42](https://cloud.githubusercontent.com/assets/384894/18307907/a80ae9c8-74f2-11e6-8c8c-670cf1c74c60.png)

For making sure that the contents you see are up-to-date, you can:

- make sure that you are logged in into Wordpress. Caching is disabled for logged users.
- Refresh the site  on your browser using CTRL+F5.

Im closing this issue.

**Comment by hailyodv** [comment]
ok thank you
