### ISSUE TITLE
Create left sidebar for Sub Page of Profile

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#403]
There will be several subpage of access to public server profile created that need different template from profile spreadsheet and its homepage (access to public profile), but it is similar to the topic template. 

Thus, the left sidebar is similar to present the related dataset, law, news and other on the pages.

**Comment by acorbi** [comment]
@Huyeng do you mean **right** sidebar? Our sidebars are always right....  For fixing this, we can create a template **Page with sidebar**  for those subpages which:

- either contains a new widget area that we define in functions.php
- or re-uses one existing widget area such as **general** (<?php dynamic_sidebar('general'); ?>)

**Comment by Huyeng** [comment]
Oh dear! Yes, it is the right sidebar. 
Yes,  we can create a new template with sidebar for the subpages, but I would like to make it flexible for Editor to manage those widgets. 

What are the related items exist in <?php dynamic_sidebar('general'); ?>? 

I think the sub profile page's widget may different from general.

**Comment by acorbi** [comment]
> What are the related items exist in <?php dynamic_sidebar('general'); ?>? 

Currently, I believe we are not using it. But yes, I also think we should have a separated one.
