### ISSUE TITLE
"References" of topic page on front-end of Khmer site

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#406]
The "References" of the topic page on front-end doesn't translate into Khmer words when I switch to Khmer site. It still show in English. Please help checking this!
Thanks.

**Comment by acorbi** [comment]
Hi @vatana92 I added the string "References" to the transifex project. Please translate along with the other pending strings: https://www.transifex.com/open-development-mekong/odm-wp-odm_theme/translate/#km/enpo/97086961?q=references

**Comment by Huyeng** [comment]
Moved to https://github.com/OpenDevelopmentMekong/odm-frontend/issues/68
