### ISSUE TITLE
Map explorer: Regional site

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#414]
Default setting for centering the map to the region is not set correctly and every time I try to centre the map it defaults to a position which cuts off Myanmar: 

![image](https://cloud.githubusercontent.com/assets/14996905/18546508/a0962ae8-7b3e-11e6-8668-d56847cfaea8.png)

**Comment by acorbi** [comment]
@prustar, this is a configuration Issue. please follow indications on https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0#setting_default_configuration_for_maps for correcting this. closing....
