### ISSUE TITLE
Topic pages font size

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wp-odm_theme#421]
2-Font size in the photos caption is not consisitant.
![screencapture-opendevelopmentcambodia-net-1474014475668](https://cloud.githubusercontent.com/assets/10953792/18579969/f3fe8eac-7c22-11e6-8070-db5845dc4a23.png)

**Comment by S-mardii** [comment]
I am fixing the font size

**Comment by acorbi** [comment]
@ChandaraKhun @S-mardii please separate these two "problems" into 2 different issues so they can be addressed on different code branches

**Comment by acorbi** [comment]
@ChandaraKhun I splitted this issue into 2 different ones. See https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/425

**Comment by S-mardii** [comment]
@acorbi Thanks for this. By the way, the code i pushed was only on font side. I will work on Language translating problem on another branch.

**Comment by acorbi** [comment]
Fixed
