### ISSUE TITLE
Topic archive: it does not show grids of topics when switch to khmer site

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#422]
![screenshot](https://cloud.githubusercontent.com/assets/18528756/18582124/c905610c-7c2d-11e6-9be3-e9a41e2e5eaa.png)

**Comment by acorbi** [comment]
@S-mardii @Huyeng this one is critical, we should assign it high priority. @S-mardii can you take a look and try to fix it?

**Comment by S-mardii** [comment]
@acorbi I will check it.

**Comment by S-mardii** [comment]
@acorbi  I will check it.

**Comment by acorbi** [comment]
@S-mardii @Huyeng I have checked the vietnamese site and the cambodia pre-production site and the issue cannot be reproduced. this indicates that the issue is not necessarily  related to the code but the way the content is stored.

**Comment by Huyeng** [comment]
@acorbi, can we close this issue?

**Comment by acorbi** [comment]
@huyeng sure! closing...
