### ISSUE TITLE
Wrong language on categories in topic pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#425]
1-function of bilingual version does not work with the Category.
![screencapture-opendevelopmentcambodia-net-1474014475668](https://cloud.githubusercontent.com/assets/10953792/18579969/f3fe8eac-7c22-11e6-8070-db5845dc4a23.png)

**Comment by Huyeng** [comment]
On homepage also.
![error](https://cloud.githubusercontent.com/assets/6613530/18704329/ba00147e-8013-11e6-9876-96b956e85e36.jpg)

**Comment by acorbi** [comment]
@ChandaraKhun cannot reproduce this issue anymore. I will consider it fixed, please re-open if you can still reproduce it.
