### ISSUE TITLE
Improve word wrapping for english on firefox

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#428]
There is still an issue under Firefox though which is not critical but it is not nice. Currently words in english are being chopped after any character:
![screenshot from 2016-09-19 16-53-44](https://cloud.githubusercontent.com/assets/384894/18636972/1f570434-7e8b-11e6-9771-6ddeeda3b4a0.png)

The relevant LESS code is currently under **/less/_layout.less**

**Comment by Huyeng** [comment]
The chopped texts occurred because of using the word break in css.
