### ISSUE TITLE
Style custom post list items

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#43]
The ODM Custom posts widget gives editors the possibility of choosing between **grid** and **list** layout for displaying the results.

The **list** layout will be mostly used on the submenu for news, stories or profiles and need to be adapted visually to comply to the style guide.

![screenshot from 2016-07-05 23-28-24](https://cloud.githubusercontent.com/assets/384894/16615952/57c84586-437a-11e6-9ee7-a66088680bd6.png)
![screenshot from 2016-07-06 13-05-23](https://cloud.githubusercontent.com/assets/384894/16615953/57f450b8-437a-11e6-9566-653165da02e3.png)

For doing, please modify the code of:

    inc/templates/post-list-single.php (reused across the site)
    less/_layout.less (post-list-item-small and post-list-item classes)

**Comment by DragonVirus** [comment]
Fixed via pull #52

**Comment by acorbi** [comment]
@DragonVirus #52 improved the layout considerable. However, there are still some improvements to be done.

Two screenshots from pp.opendevelopmentmekong.net

![screenshot from 2016-07-12 09-16-02](https://cloud.githubusercontent.com/assets/384894/16758405/8db8c288-4811-11e6-8e12-6c3ca4e81880.png)
![screenshot from 2016-07-12 09-17-13](https://cloud.githubusercontent.com/assets/384894/16758406/8eed0402-4811-11e6-8fa5-01d92c7f0bbd.png)

**Comment by acorbi** [comment]
@DragonVirus Also, part of this tasks should be to improve the **grid** layout of the output of the  custom posts widget.

On homescreen: https://pp.opendevelopmentmekong.net/
![screenshot from 2016-07-12 12-53-59](https://cloud.githubusercontent.com/assets/384894/16764685/e5ab52b2-482f-11e6-9827-e25f8ca345d4.png)

On news archive page: https://pp.opendevelopmentmekong.net/news-article
![screenshot from 2016-07-12 12-54-41](https://cloud.githubusercontent.com/assets/384894/16764703/01dac184-4830-11e6-9365-43378a62b458.png)

- [ ] if post does not have categories or tags, the icon should not be shown
- [ ] Find a solution for those posts with many categories (see news archive page)

**Comment by DragonVirus** [comment]
i think it's better not to show the categories in grid view since the current old design also didn't show categories in list view.

**Comment by acorbi** [comment]
@DragonVirus Agreed, I believe laying out those big number of categories on the grid elements would be tricky.

**Comment by acorbi** [comment]
This can be consider fixed. See https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/90 for related issue

closing
