### ISSUE TITLE
Footer Menu: Circle list style on Footer Menu Item

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#443]
I have just noticed that there are some circle indicating the list on the Footer menu items which need to be removed. It is just CSS.

![screenshot 2](https://cloud.githubusercontent.com/assets/18528756/18739014/c0f5aad4-80ca-11e6-9504-3589c72a6a2f.png)

**Comment by acorbi** [comment]
@S-mardii hehehe just now I have fixed that Issue, see #442

**Comment by S-mardii** [comment]
@acorbi  Awesome. That's pretty quick.
