### ISSUE TITLE
Topic archive: Topic classification do not translated

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#447]
While other words were transliterated, the classification of the topic does not.

![screenshot 2](https://cloud.githubusercontent.com/assets/18528756/18742877/a1c3cf54-80e0-11e6-80c2-ddbd214dc897.png)

**Comment by acorbi** [comment]
@S-mardii this string is not translated on https://www.transifex.com/open-development-mekong/odm-wp-odm_theme/language/km/ yet @gimmemochi can you please coordinate the translation of the Khmer strings on transifex? 

![screenshot from 2016-09-22 19-44-49](https://cloud.githubusercontent.com/assets/384894/18759510/0cf85972-80fd-11e6-879d-d8826262d43c.png)

**Comment by gimmemochi** [comment]
@ChandaraKhun there are 285 strings needed to be translated into Khmer on this package. Please coordinate the translation with your team. For questions or concerns, let us know. Once you're done, please inform Alex to implement the translation.
