### ISSUE TITLE
Map Explorer // Base layer incorrect display

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#451]
Don't know what's happening here? 

![image](https://cloud.githubusercontent.com/assets/14996905/18769438/6f14ec30-812d-11e6-97e7-59b96b813cbe.png)

Any thoughts @Huyeng?

**Comment by Huyeng** [comment]
Which website, send me the link pls?

**Comment by Huyeng** [comment]
That's because of zooming level to the world view. Fixed it now.

**Comment by prustar** [comment]
Thanks @Huyeng - I need to add the mask to the file so that it white's out the black but in the background can you leave the original base map? I added hydropower to this map as an example and although the landsat doesn't cover beyond the region it would be nice to see the other countries in the background. 

![image](https://cloud.githubusercontent.com/assets/14996905/18781959/4f85471e-8184-11e6-982e-24c2317ce44c.png)

**Comment by Huyeng** [comment]
Ok. It was zoomed  smaller.
