### ISSUE TITLE
Change logo to Khmer language on Khmer site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#452]
The Khmer name of Open Development Cambodia: ទិន្នន័យអំពីការអភិវឌ្ឍ
![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/18774929/1b53a66c-8188-11e6-9a4d-a4462db4a713.jpg)

**Comment by acorbi** [comment]
@Huyeng This needs to be discussed first. it could cause some branding issues. 

Also, it breaks the responsiveness of the layout on mobile

reopening...
