### ISSUE TITLE
Publishing layers in Map Explorer not displaying

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#457]
https://opendevelopmentmekong.net/wp-admin/post.php?post=2863161&action=edit
https://opendevelopmentmekong.net/wp-admin/post.php?post=2863161&action=edit

After testing in PP and working I transfered to PROD but the layers aren't displayed in the Category Box so I can't see these layers at all?

**Comment by acorbi** [comment]
I believe the problem is that currently, the map explorer lists a maximum of 10 layers for each category. Im checking this....

**Comment by acorbi** [comment]
@Huyeng I believe that the map-explorer/thematic-maps code might be just pulling a maximum of 10 layers per category. Could you please check the code and make sure the code pulls ALL available layers for a certain category?

Also, I have identified some inconsistencies on the code in **mapping.php**

1. Parameter **num** not passed on calls to **query_get_layer_posts**

Line 200 https://github.com/OpenDevelopmentMekong/wp-odm_theme/blob/master/inc/utils/mapping.php#L200
Line 243 https://github.com/OpenDevelopmentMekong/wp-odm_theme/blob/master/inc/utils/mapping.php#L243

**Comment by Huyeng** [comment]
I don't think it caused by the numbers of posts. I will check it. 
The two functions are using for different purpose, but their name is a bit confuse. I will name them clearly.
