### ISSUE TITLE
Map explorer //  white line

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#458]
![image](https://cloud.githubusercontent.com/assets/14996905/18809494/434439de-827d-11e6-915d-775444b92e03.png)

**Comment by Huyeng** [comment]
@prustar, please provide us some information related the browser that produce this error such as the name and the version of the browser as well as Mac or Window.

**Comment by acorbi** [comment]
@prustar can this issue still be reproduced? can we close it?

**Comment by prustar** [comment]
Tried again on Chrome and Firefox and seems to be ok now. Closing. 
![image](https://cloud.githubusercontent.com/assets/14996905/22092447/b7ae39ac-de51-11e6-9347-302af1351333.png)
