### ISSUE TITLE
Implement functionality for exposing and embedding single layers

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#470]
# Exposing

Enhance the **single view of the layers** (single-layer.php) (example: https://pp.opendevelopmentcambodia.net/layers/aqueduct-atlas-consumptive-use/) so it presents an embedded interactive map besides the thumbnail and the description of the layer.

# Embedding

@prustar has requested the possibility of embedding **single** layers as we currently can embed **thematic maps**, see https://wiki.opendevelopmentmekong.net/partners:thematic-maps#how_to_embed_a_thematic_map_on_a_page

Current JEO set of features does not include embedding single layer, correct @Huyeng?

We should think about the cost of implementing this and whether is possible within required timelines. Alternativelly, individual layers could be added to individual maps and be presented as a single layer thematic map.

**Comment by Huyeng** [comment]
Embedding single layer has not set yet.  
Yes, time is required to implement this.

**Comment by acorbi** [comment]
OK, we will then estimate this **feature request** separately, let's focus on the more critical map issues by now

**Comment by acorbi** [comment]
@Huyeng Im already estimating the implementation of milestone 2.1.0 and this task is part of the working plan. Could you please estimate how many hours would you need to implement this functionality?

Basically, we should implement a way of being able to embed a single map layer via a code similar to:

```
<iframe src="https://opendevelopmentmekong.net/embed/?map_id=MAP_ID&width=100%&height=500" width="100%" height="500" frameborder="0"></iframe>
```

But instead of using the ?map_id attribute we would tweak the code to use anew attribute ?layer_id

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/707
