### ISSUE TITLE
Curating related resources overwrites other widgets

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#471]
Topic pages are currently configured to display related resources via wpckan based on selected taxonomy topic:

![image](https://cloud.githubusercontent.com/assets/1206387/18835495/885e60c2-8425-11e6-8bd4-0bb5f89dea52.png)

Currently, adding a selected resource via the topic page editor seems to 'overwrite' these widgets, meaning that three segregated display boxes of datasets, laws and library records now only displays the one selected item:

https://pp.opendevelopmentmekong.net/topics/water-resources/

![image](https://cloud.githubusercontent.com/assets/1206387/18835443/514d859a-8425-11e6-8e31-4170526f593f.png)

![image](https://cloud.githubusercontent.com/assets/1206387/18835453/5c6d6ae4-8425-11e6-99cd-d1fc82037265.png)

**Comment by acorbi** [comment]
> Topic pages are currently configured to display related resources via wpckan based on selected taxonomy topic:

That is not correct. The **WPCKAN Related datasets'' widget lists those datasets which have been added using the **Add related CKAN content** metabox. The widget which lists related CKAN content using the post's category is called **WPCKAN Query resources by post\'s category**

In the example you are posting, the configuration produces an expected output. You have added 1 related CKAN dataset which is a **library_record** and this is being listed on the **Related library records** widget.

**Comment by DBishton** [comment]
Hi @acorbi, thanks for the clarification. 

Is it intended behaviour that adding one related dataset (library_record) in the example above removes the 3 widget panels that were there previously? Before I added that record, the topic sidebar presented like this:

![image](https://cloud.githubusercontent.com/assets/1206387/18861454/82e4723c-84af-11e6-919e-e12a3ef6b6ee.png)

**Comment by acorbi** [comment]
@DBishton I would say that that previous state ( 3 widgets which list related contents even though no related datasets have been added to the topic) was wrong... After adding that related record we get now the expected result. So the question would be:

- Can you reproduce that behaviour on another topic page? We should fix it if so...

**Comment by acorbi** [comment]
Creating related issue on WPCKAN https://github.com/OpenDevelopmentMekong/wpckan/issues/178

@DBishton closing this Issue, please re-open (or add new ones) if you find any other problem while playing around with widgets on PP.
