### ISSUE TITLE
Thematic map layers are missing some of the functionality exposed on map-explorer

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#472]
All thematic map layers should have the same options as the existing map explorer. This includes the categories, legends, info windows and download options.

Maps will be separated into these thematic areas so the map explorer won't exist shortly.

**Comment by acorbi** [comment]
@Huyeng Can you confirm which options are available on the thematic maps and which are not?

**Comment by prustar** [comment]
Problem with over lay functions between category layers and base layers: Base layers should only be available on the top left and not present in the layer category box. 

![image](https://cloud.githubusercontent.com/assets/14996905/18850100/4e8307e8-8436-11e6-91a5-ce44ed559072.png)

https://pp.opendevelopmentmekong.net/maps/water-resources/#!/story=post-2248035&loc=11.907666089671903,104.66537475585938,9

This Water Resource thematic map should allow you to toggle the base layer for the water mask and the two water and land layers with the option to switch on the landsat base layer behind the the water mask if desired. 

Currently if both the base layers are set then the landsat covers the water mask layer - how can we fix this so that the water mask is always on top of the landsat. 

![image](https://cloud.githubusercontent.com/assets/14996905/18850175/abf75816-8436-11e6-88b7-2926cb12afc1.png)

**Comment by prustar** [comment]
Uploaded into PROD - https://opendevelopmentmekong.net/wp-admin/post.php?post=2895005&action=edit

Behaviour is different to PP.

**Comment by acorbi** [comment]
Legends, download link will appear once the CKAN URL is specified on the maps config.

Problems with layers order will be fixed once the both base layers are combined and https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/483 is fixed.

Closing this issue now.
