### ISSUE TITLE
Map Explorer // Default info window 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#473]
Don't know if this can be controlled but when you have a polygon layer that covers a smaller line layer such as in the rivers and hydrobasin overlay (example below) you can't select the river layer to display the name of the river. 

![image](https://cloud.githubusercontent.com/assets/14996905/18852856/aa171732-8442-11e6-813d-ab89c5a60377.png)

Link: https://opendevelopmentmekong.net/maps/rivers-and-hydrobasins/?preview_id=2894475&preview_nonce=798492dd2a&preview=true#!/story=post-2884577&loc=14.498508149446216,102.24700927734375,8

**Comment by Huyeng** [comment]
@prustar, I would like to suggest to add the stroke in geoserver or Cartodb instead.
Fixing by code can affect to other map layers.

**Comment by acorbi** [comment]
@Huyeng @prustar what is the status of this issue? Can it still be reproduced? can we close it?

**Comment by Huyeng** [comment]
Close it now. 
You can reopen if the issue is still existing.
