### ISSUE TITLE
Responsive | Header: OD country selector and language selector nav on the same row.

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#474]
![screenshot 2](https://cloud.githubusercontent.com/assets/18528756/18859704/e18b5e90-84a0-11e6-9b00-e754831a35e8.png)

**Comment by acorbi** [comment]
Fixed via 550064460add8280b8710d2e37e809dc4e63aa26

**Comment by S-mardii** [comment]
@acorbi  @Huyeng  I would like to reopen this issue because the fix has not yet applied to some particular screen sizes.

**Comment by acorbi** [comment]
@S-mardii please do. We can close it once we merge your upcoming PR

**Comment by S-mardii** [comment]
@acorbi there is no Reopen button. I can only comment here.

**Comment by acorbi** [comment]
@S-mardii reopened

**Comment by acorbi** [comment]
Fixed via cdf23c28fb9431bbe997f883f700a6855408b565
