### ISSUE TITLE
Responsive | Header: Reduce space of logo and Social nav. screen size: 320-370px

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#476]
![screenshot 2](https://cloud.githubusercontent.com/assets/18528756/18860085/17c29d90-84a4-11e6-93e6-d2805893485c.png)

**Comment by acorbi** [comment]
Fixed via e2a026bdfa52c30c5e826510c1b737f4a16fb950
