### ISSUE TITLE
[Reopen] Issue: #474

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#481]
@acorbi the code to fix this issue (https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/474) has already merged. However, because I made changes on the same files from different branches, this part of code was deleted. Therefore, I just wanna make the pull request of the same code again.

**Comment by acorbi** [comment]
Fixed via 3a097ef099897e14393fa7e147afaa0a7e53cfac
