### ISSUE TITLE
Hide news icons not working properly on thematic maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#485]
The **hide news icons** functionality is not working as expected.

To reproduce the error.

1. Go to thematic map https://pp.opendevelopmentmekong.net/maps/water-resources/#!/story=post-2248035&loc=11.907666089671903,104.66537475585938,9
2. Check the **hide news icons** checkbox and news icons disapear.
3. Now zoom out. Some other icons appear again.
4. Now uncheck the **hide news icons** and other icons will appear.

![screenshot from 2016-09-27 11-08-46](https://cloud.githubusercontent.com/assets/384894/18867450/8caf422a-84a4-11e6-8dc4-efde4847d1e6.png)

**Comment by Huyeng** [comment]
This issue will be fixed during working on this issue https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/465

**Comment by prustar** [comment]
@Huyeng @acorbi -- when I loaded into PP the water resource map and toggle the baselayers - the news items come up still: 

![image](https://cloud.githubusercontent.com/assets/14996905/18953453/d1313fce-864e-11e6-88d7-9d37a03729a0.png)
![image](https://cloud.githubusercontent.com/assets/14996905/18953468/e576d7a0-864e-11e6-9316-29d6ef9a4903.png)

I decided not to combine the base layers as there is benefit to having the separately.

**Comment by acorbi** [comment]
@prustar I cannot reproduce it on my machine. have you re-loaded the site with CTRL+F5?
@Huyeng can you reproduce it?

**Comment by Huyeng** [comment]
I can't reproduce either. Technically, the new i cons is the separated marker layer, it won't be combined with other. The error may cause by the catch, please clear the catch.

**Comment by acorbi** [comment]
Closing this, please re-open if still being reproduced.
