### ISSUE TITLE
Popup "ghosts" on thematic maps when WMS base layer is loaded

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#493]
Allthough the **news icons** are disabled by default, once enabled, although they are not visible. they are clicable and therefore a popup "ghost" appears as seen in the screenshot:

![screenshot from 2016-09-28 11-56-47](https://cloud.githubusercontent.com/assets/384894/18909457/fae4bb9c-8573-11e6-8273-c5d3a08c97b4.png)

Steps to reproduce:
1. go to thematic map, example: https://pp.opendevelopmentmekong.net/maps/water-resources/#!/story=post-2248035&loc=11.556725775618903,105.31082153320312,10
2. Load **landsat** base layer
3. Check **Show news on map**, icons will appear. Pay attention to the position where one of those icons are shown.
4. Uncheck **Show news on map**, icons will disappear.
5. Click on the position where one of those icons where shown. Pop-up ghost appears.

**Comment by Huyeng** [comment]
It is not caused show news function, but because of the landsat base layer. 
If landsat is not enable, the info-window won't appear that because landsat is not the title layer, but wms layer.

**Comment by acorbi** [comment]
@Huyeng ok, understood! Indeed the issue can be reproduced by just:

1. go to thematic map, example: https://pp.opendevelopmentmekong.net/maps/water-resources/#!/story=post-2248035&loc=11.556725775618903,105.31082153320312,10
2. Load landsat base layer
3. Click on any position on the map. pop-up ghost appears

**Comment by Huyeng** [comment]
@pyrou, does it require to have popup info for the raster layer? 
@alex, It seems to me that pop-up is working fine with the vector layer that content the feature information. 
I would like to suggest to create the baselayer as tile instead of the wms.

**Comment by Huyeng** [comment]
@Pyrou, please be inform that the Landsat layer was changed to tile format on PROD now, and the error has gone. If you would like to use the wms, it can fix after holiday because I have to join the training for full day, and then holiday.

**Comment by acorbi** [comment]
@Huyeng good workaround. :+1: Let's keep this Issue open for fixing it at a later point. thanks huyeng

**Comment by Huyeng** [comment]
I would like to close it right now. Please reopen or log the new one if needs.
