### ISSUE TITLE
Group layers by categories on thematic maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#499]
In order to allow a better UX on the thematic maps, the code should be adapted so the exposed layers are grouped by categories (Maps > Layer categories) as they are on the map explorer.

**Comment by Huyeng** [comment]
Exposing the layers and grouped them by layer categories as map explorer can't apply directly to all the thematic map.  Some embedded thematic map contain only 1-2 layers, grouping does  not need.  
I would like to suggest to provide an option to set it if the thematic map is required to category.

**Comment by acorbi** [comment]
> Exposing the layers and grouped them by layer categories as map explorer can't apply directly to all the thematic map. 
> I would like to suggest to provide an option to set it if the thematic map is required to category.

@Huyeng , I agree with your proposal.

**NOTE** that I have added the **discussion needed** and **feature request** labels to this Issue, let's agree on this before implementing anything.
