### ISSUE TITLE
Centering Tableau embeds

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#501]
Hi @Huyeng and @acorbi ,

@davidmhill  and I are having a lot of trouble in trying to center-align embedded Tableau visualisations on topic pages.

An example of typical embed code is below:

`<div id="viz1475212616933" class="tableauPlaceholder" style="position: relative;"><noscript><a href='#'><img alt='Dashboard 1 ' src='https://public.tableau.com/static/images/FA/FAOSTATS-WaterDependencyRates/Dashboard1/1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="100%" height="600"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /><param name="site_root" value="" /><param name="name" value="FAOSTATS-WaterDependencyRates/Dashboard1" /><param name="tabs" value="no" /><param name="toolbar" value="yes" /><param name="static_image" value="https://public.tableau.com/static/images/FA/FAOSTATS-WaterDependencyRates/Dashboard1/1.png" /><param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /></object></div>`

This is from this topic page, currently in draft: https://opendevelopmentmekong.net/wp-admin/post.php?post=2914898&action=edit

Can you investigate? This is high priority as we have a set of topic pages that we want to publish ASAP. Many thanks.

**Comment by acorbi** [comment]
@DBishton @davidmhill 

The origin of this problem (and probably the one for the height being set automatically, @DBishton please log issue) is that the embedded code contains javascript logic which makes sure that the tableau embed adapts its size when the page is resized but needs to be slightly tweaked:

This is the complete embed code:

```
<div id="viz1475212616933" class="tableauPlaceholder" style="position: relative; margin: 0px auto;"><noscript><a href='#'><img alt='Dashboard 1 ' src='https://public.tableau.com/static/images/FA/FAOSTATS-WaterDependencyRates/Dashboard1/1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="100%" height="600"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /><param name="site_root" value="" /><param name="name" value="FAOSTATS-WaterDependencyRates/Dashboard1" /><param name="tabs" value="no" /><param name="toolbar" value="yes" /><param name="static_image" value="https://public.tableau.com/static/images/FA/FAOSTATS-WaterDependencyRates/Dashboard1/1.png" /><param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /></object></div>
<p><script type="text/javascript">// <![CDATA[
var divElement = document.getElementById('viz1475212616933');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.minWidth='424px';vizElement.style.maxWidth='654px';vizElement.style.width='100%';vizElement.style.minHeight='629px';vizElement.style.maxHeight='929px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);
// ]]></script></p>
```

Now pay attention to the following peace of code:

```
vizElement.style.maxWidth='654px'
```

That sets the maximum width of the whole embeded viz. In order to fix the Issue, you need to adapt the code and increase the value to something like:

```
vizElement.style.maxWidth='900px'
```

@DBishton @davidmhill can that value be configured on the tableau side before generating the embed code?

Im closing this Issue since it cannot be fixed with the theme's code
