### ISSUE TITLE
Tableau visualizations not showing up on firefox

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#504]
While browsing pages with embedded Tableau content with firefox (version 49.0), I noticed that those embedded contents are not showing up. They do while browsing the site on Chrome.

![screenshot from 2016-10-04 13-08-41](https://cloud.githubusercontent.com/assets/384894/19072165/02c01234-8a34-11e6-921c-46cd42cf56f8.png)

As the screenshot reflects, it could be a javascript Issue.

**Comment by acorbi** [comment]
@DBishton @davidmhill can you see the visualizations on Firefox yourselves?

**Comment by DBishton** [comment]
Thanks for logging this @acorbi --

I have tested and can confirm that Tableau visualisations show up for at least one page in Firefox:
![image](https://cloud.githubusercontent.com/assets/1206387/19106556/2bbfb8c2-8b12-11e6-84c3-4905114ed7d4.png)

Though I note that they take considerably more time than other elements to render on initial page load.

**Comment by acorbi** [comment]
OK, if they show up for one page, then they should do for all. I'm closing this Issue. Let's re-open or log a new one in case other issues are reproduced around embedded tableau content.
