### ISSUE TITLE
Responsive: Screen width: 320 and 360 should presented Logo in the same line 

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_theme#507]
(1) Resize Font and Spacing of Logo
(2) Resize social nav logo

Before changing:
![capture](https://cloud.githubusercontent.com/assets/18528756/19105036/183557ec-8b0a-11e6-84c0-e9c38982a117.PNG)

After changing:
![social](https://cloud.githubusercontent.com/assets/18528756/19105211/0824c18e-8b0b-11e6-9884-98701666a4e0.PNG)

**Comment by acorbi** [comment]
Fixed via a5ea82d1f194a570a774c6267ff368fac0ccb3e6
