### ISSUE TITLE
Unify slider for multiple torque layers on thematic maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#508]
The control for the fire map layers are overlapping therefore you can only switch and control one layer. Also the bar is slightly longer than the scale box. This was taken from the map preview view.  

![image](https://cloud.githubusercontent.com/assets/14996905/19005411/cd38ff58-875a-11e6-9a1e-53078c722f26.png)

Unfortunately when the menu is enabled the time controls are not available: 
![image](https://cloud.githubusercontent.com/assets/14996905/19005639/e9b96432-875b-11e6-97cd-ae695b2c4297.png)

**Comment by acorbi** [comment]
@prustar 

> Unfortunately when the menu is enabled the time controls are not available

Which menu you mean?

Can you provide a link?

**Comment by Huyeng** [comment]
@acorbi, it is the layer menu. 

I will check and fix it.
