### ISSUE TITLE
WATER// Hyperlinks not working

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#510]
@DBishton - on Water resource page link to subsequent pages aren't working both at top and bottom.
![image](https://cloud.githubusercontent.com/assets/14996905/19133027/9ac4840c-8b56-11e6-90fd-2a95fd97e557.png)

**Comment by prustar** [comment]
@DBishton -- on Surface water page link to Rivers and Lakes not working: 
![image](https://cloud.githubusercontent.com/assets/14996905/19134085/1be69e26-8b5c-11e6-9b91-c8b7dd39b3e9.png)

**Comment by Huyeng** [comment]
Hyperlinks are updated.
