### ISSUE TITLE
Laws page's format errors with Chrom browser

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#516]
![law page](https://cloud.githubusercontent.com/assets/19201022/19144192/69b5591e-8bd2-11e6-934f-1036b5ba8e54.JPG)

**Comment by acorbi** [comment]
@vatana92 I tried but cannot reproduce this issue on my machine. Im using Ubuntu Linux, with chrome 45.0.2454.101.

![screenshot from 2016-10-06 12-56-46](https://cloud.githubusercontent.com/assets/384894/19149897/74b3a4aa-8bc4-11e6-936a-9d18602ad890.png)

Can you please provide more details of your setup? Also, please try to refresh the site with CTRL+F5

**Comment by acorbi** [comment]
@OpenDevelopmentMekong/tech anybody can reproduce this?

**Comment by vatana92** [comment]
That format or the style of Law page viewed on Firefox is fine. But when it viewed on Chrome, it looks like the picture I sent you. It happened on both Khmer and English sites.

**Comment by acorbi** [comment]
@vatana92 can you please tell me which Chrome version you are using.

did you try to refresh the site with CTRL+F5?

**Comment by Huyeng** [comment]
Checking with my chrome browser, i got the same error as @vatana92. 
Its Version 53.0.2785.143 m

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/19150661/3146be40-8bf2-11e6-8f74-dc6d21f8bb17.jpg)

**Comment by vatana92** [comment]
Mine is Version 53.0.2785.116 m

**Comment by Huyeng** [comment]
Moved to https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/issues/13
