### ISSUE TITLE
error on https://opendevelopmentmyanmar.net/maps/

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#561]
https://opendevelopmentmyanmar.net/maps/

![screenshot from 2016-10-19 07-21-12](https://cloud.githubusercontent.com/assets/384894/19517012/be1b28a4-95cc-11e6-9650-8ac2ffe510d2.png)

**Comment by Huyeng** [comment]
There is no need to assign the template for the map post. Fixed it now, after updating the template to default.
