### ISSUE TITLE
Implement metabox for adding related content to posts

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#566]
This approach consists on coding a metabox through which the editors should be able to enter the metadata for each post. 

Editors need to be able to add a LIST of URLs to a certain post ( news, topic, etc..)
A Metabox (similar to WPCKAN Add related datasets metabox) will be available on new/edit post screen on WP and offer the possibility to add related links:
### Metabox’ UI elements:
- **text input** for inputting the **URL** of a related content. 
- **dropdown box** for selecting the **TYPE** field of a related content (the options will be preset in order to ensure consistency, new requirements for data interoperability would imply new options to be added). See Filtering mechanisms on widget ODM list related content below for possible values.
- **add button** for adding the entered related content
- **delete button** for deleting entered related contents

![screenshot from 2016-10-20 15-50-21](https://cloud.githubusercontent.com/assets/384894/19575531/ef78ca4e-96dc-11e6-8dfa-619897846723.png)

When post is saved (see save_post action hook), the logic will take that list of URLs and store it in the post’s custom fields. The values would be stored as a combination of TYPE field and URL in an appended form, separated by pipe “|” character.

Example: odm_drafting_agency|https://pp.opendevelopmentcambodia.net/profiles/economic-land-concessions/?map_id=elc_gdc_177
library_record|https://opendevelopmentmekong.net/dataset/?id=chu-prong-hydropower

**Comment by Huyeng** [comment]
@acorbi - it was requested to have the  optional text box for hyperlink's label for customization. It will be useful for adding the out source url as well. What do you think?

**Comment by acorbi** [comment]
@Huyeng OK, adding label would be a possible functionality. However I would do this **optional**, if editors do not specify any label, the title of the related content will be shown per default. This could vary depending on the type of content and the template. 

 Please plan and implement accordingly.

**Comment by Huyeng** [comment]
The related content should be a new plugin. I will create a new plugin for this, what do you think?

**Comment by acorbi** [comment]
@Huyeng agreed. which name should we choose? wp-odm_related? wp-odm_metadata?

**Comment by Huyeng** [comment]
wp-odm_related, it is not quite clear. What do you think if we name it as wp-odm_related_content?

**Comment by acorbi** [comment]
@Huyeng I prefer the name to be shorter, otherwise we are going to be typing long names all the time  wp-odm_related is my favourite but feel free to suggest others...

**Comment by Huyeng** [comment]
Short name is fine.

**Comment by acorbi** [comment]
moved to https://github.com/OpenDevelopmentMekong/wp-odm_related/issues/4
