### ISSUE TITLE
Implement  ODM list related content widget 

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#567]
A widget ODM list related content will be exposed by the theme which gives the editor (under **Appearance > Widgets** ) the possibility to place a widget on the UI and configure it with following options:

**Title** (example: Related library records)
**Filtering by type**: In order to only present related contents with the same type value. Present a list of checkboxes or **multi-select dropdown** (make possible to select multiple options) with list of possible options. The possible values could be:
1.  metadata fields used on CKAN records as listed on https://wiki.opendevelopmentmekong.net/public:metadata
2. a dataset type (dataset, library_record, laws_record)
3. the slug of a WP content type (topic, profile, map, layer) 

or other keys that we might come up with in the future.

**Representation template**: A drop-down box for editors to select available templates which will determine how the related contents would be displayed.  Depending on the value selected, additional configuration fields would be shown. Following possible options:
- **List of links (default)**: Basically a `<ul><li><li><ul>` HTML structure which will present links to the related contents. Parameters: Limit.
- **Html contents**: Basically outputs the body of the related contents, in HTML 
- **Thumbnail**: Outputs the featured image of the post, using **odm_get_thumbnail** function
- **Grid box**: Shows that (black) grid box such as those used on the map catalogue
- **Type’s specific**: This representation template would depend on the type of the related resource. This option helps to implement UC5 (charts).
- **Timeline of CKAN records**: Using a javascript library for creating timelines or programming the visualization ourselves, links would be presented in a chronological order. In order to sort the resources, the widget would provide an additional input field where editors need to specify which CKAN metadata field would be used for sorting, this field should have type date.

**Example of List of links**

![screenshot from 2016-10-20 16-06-02](https://cloud.githubusercontent.com/assets/384894/19576192/0f1d450c-96e0-11e6-8975-3a862e2a96f7.png)

**Example of timeline**

![screenshot from 2016-10-20 16-19-04](https://cloud.githubusercontent.com/assets/384894/19576418/f24ddee0-96e0-11e6-92da-e2744ad9bba9.png)

**Example of html content**

![screenshot from 2016-10-20 16-19-44](https://cloud.githubusercontent.com/assets/384894/19576448/0a9ddc8e-96e1-11e6-8e35-927f12b1f3e8.png)

**Example of type specific**

![screenshot from 2016-10-20 16-21-02](https://cloud.githubusercontent.com/assets/384894/19576503/3c88b4d0-96e1-11e6-8ef0-687b02347b23.png)

**Example of checkbox selection instead of drop-down box selection**

![screenshot from 2016-10-20 16-21-40](https://cloud.githubusercontent.com/assets/384894/19576518/4e2ae4ba-96e1-11e6-9770-11650632ac3b.png)

**Comment by Huyeng** [comment]
Which template that can show the thumbnail of map or layer with link to dataset/map page?
If it has not yet, please add a new template for it.

**Comment by acorbi** [comment]
@Huyeng thanks for pointing this out. I've added to the list of template above

**Comment by Huyeng** [comment]
The related content should be a new plugin. I will create a new plugin for this, what do you think?

**Comment by acorbi** [comment]
moved to https://github.com/OpenDevelopmentMekong/wp-odm_related/issues/5
