### ISSUE TITLE
No "Related publications" & "Related laws and regulations" on Khmer site

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#572]
On profile page "Access to public service" not showing "Related publications" & "Related laws and regulations" on Khmer site.
![eng](https://cloud.githubusercontent.com/assets/19201022/19719104/a13250ac-9b92-11e6-9754-809ccee35615.png)
![khmer](https://cloud.githubusercontent.com/assets/19201022/19719105/a13af950-9b92-11e6-9f50-0b7a016c6a49.png)

**Comment by acorbi** [comment]
@vatana92 will take a look at this. thanks for reporting!

**Comment by acorbi** [comment]
this issue belongs to https://github.com/OpenDevelopmentMekong/wpckan/issues/189
