### ISSUE TITLE
Per-post widget changes: not all widget areas visible on PP

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#573]
When choosing widgets on a per-post basis on pre-production, only the topic sidebar area is presented as an option:

https://pp.opendevelopmentmekong.net/wp-admin/post.php?post=2256062&action=edit

![image](https://cloud.githubusercontent.com/assets/1206387/19851304/d188a2f0-9f8f-11e6-9d7f-80ea2276432a.png)

On production, more widget areas appear to be displayed:

https://opendevelopmentmekong.net/wp-admin/post.php?post=2796229&action=edit

![image](https://cloud.githubusercontent.com/assets/1206387/19851352/0e074e3e-9f90-11e6-93b5-ea566cff7d77.png)

**Comment by acorbi** [comment]
@DBishton take a look at https:/pp/opendevelopmentmekong.net/wp-admin/admin.php?page=pw-settings, there, you are able to specify which widget areas are available. 

On PROD, more widget areas are available.

Closing this, please re-open if it is not working somehow.
