### ISSUE TITLE
ODC: Opening up Profile links to Archive site in a new window/tab instead of same window

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#603]
Would like to suggest that Navigation menu's for links going to the old archive site like census data open up a new window/tab to show this information rather than opening up in the same window as they do for the pages on the site. When you open the old site in the same window the navigation back to the new site is a bit confusing

http://archive.opendevelopmentcambodia.net/census-data/

**Comment by acorbi** [comment]
@Huyeng @ChandaraKhun @DBishton this should be done under **Appearance > Menu**. Would you agree on doing this change? if so, please do and close this issue

**Comment by acorbi** [comment]
@Huyeng @ChandaraKhun @DBishton ping

**Comment by Huyeng** [comment]
Done!
