### ISSUE TITLE
Print a map function in map explorer

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/wp-odm_theme#621]
Print a map function to enable users to export 1) a single map layer (2) layers that are over-layed to each other - in jpg/png formats.

**Comment by prustar** [comment]
@thetaung2 @acorbi -- This is a very old outstanding request since before the launch of ODM -- raised by users and ODC previously -- We need to implement now and stop delaying.

**Comment by prustar** [comment]
@acorbi -- I found all of these old issues which relate to this feature request: 

#86 https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/86 Opened 7 May 2015. Also https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/36 Opened 30 March 2015 which is linked to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/119. 

Additionally - https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/102 which would allow a user to print a topic page in a readable format.

**Comment by acorbi** [comment]
@prustar many thanks! Referencing those issues will help. Those are in the old repository for the theme, that is why we were not finding them.

**Comment by prustar** [comment]
@acorbi -- don't think there needs to be discussion -- these are such old issues (almost 2 years) which were raised due to user feedback and partner requests back then. It's still being raised now so I think it's about time we set steps in motion to implemented them.

**Comment by acorbi** [comment]
Agreed, I will estimate the cost of implementing this after I finish setting up the testing environment for WPSOLR, the plugin I am proposing to adopt to enhance the search. You do agree that fixing the search has higher priority than the print-a-map functionality , don't you?

**Comment by acorbi** [comment]
@thetaung2 @prustar **Print a map** functionality implemented and deployed on PP, please do some testing and provide feedback here:

https://pp.opendevelopmentmekong.net/maps/water-resources/
https://pp.opendevelopmentmekong.net/map-explorer

**Comment by prustar** [comment]
@acorbi --Tested the first page and it doesn't work: 
The map display: 
![image](https://cloud.githubusercontent.com/assets/14996905/22728405/0d4b6a1a-edde-11e6-9c0b-53ac7febb33b.png)
 The Print display: 
![image](https://cloud.githubusercontent.com/assets/14996905/22728397/f09bd1c0-eddd-11e6-96fa-da7cda2ef757.png)

Second site: 
The map display: 

![Uploading image.png…]()

The Print display is same as above: 
![image](https://cloud.githubusercontent.com/assets/14996905/22728446/468a3090-edde-11e6-812d-0e5c4e45d250.png)

**Comment by acorbi** [comment]
@prustar can you please be more specific and not just say "it does not work"?

We have several things here:

1. The map are added to the output PDF is not complete -> Please try setting **landscape** as layout, the whole map should be included now.

2. Would you include the layers or leave them out?

Any other **concrete** feedback for improving this?

**Comment by prustar** [comment]
@acorbi -- when I test something I do the basic things a user would do. I selected layers I wanted to display and hit print. The output wasn't what is expected, I'm being a lazy user who doesn't want to think about it. You've lost me as a user when I get this result. 

I will try to adjust the display and get back to you.

**Comment by prustar** [comment]
Only option is to change from portrait to landscape: 
![printmap eg 1](https://cloud.githubusercontent.com/assets/14996905/22730350/f9174560-ede6-11e6-9509-48c4362c886c.JPG)

To get to this print: 
![printmap eg 2](https://cloud.githubusercontent.com/assets/14996905/22730363/02fb874e-ede7-11e6-93bb-7b08216a9a29.JPG)
Also please note that the legend doesn't display the colours. 

I had to readjust the zoom and re position the map randomly to fit: 
![printmap eg 3](https://cloud.githubusercontent.com/assets/14996905/22730378/10ccbb54-ede7-11e6-9067-ce83619a8f56.JPG)

Basic requirements for a print a map function: 
- The selected display is centred and displayed on the print output without having to adjust it (use the standard bounding box for the region as a default for a start)
- All layers visible, legend is open and all colours displayed correctly
- No need to display the catalogue box (legend should be displayed)
- Scale displayed (*not yet implemented on ME)
- Standard disclaimer and citation text should appear: "Printed from [ODM/C/V/MM/T/L URL exact] [date] [brief disclaimer text].

**Comment by thetaung2** [comment]
Thanks for this @acorbi . We're almost there! In addition to @prustar comments, it'd be great to have all the texts on the legend are displayed when printing.

**Comment by acorbi** [comment]
@Huyeng Can you please update on the status of the implementation of the **print map** functionality? Last time we spoke it was pretty close to completion. Do you need any help with this?

**Comment by Huyeng** [comment]
Here is printing map looks like when the print button on map is click: 
Feature: 
- Can add the title 
- Can add the description

Things need to fix: 
- Missing image and not supporting Khmer Unicode yet
![screenshot_11](https://cloud.githubusercontent.com/assets/6613530/25946165/2f44bb42-3674-11e7-8cee-13ed2bf8ded6.jpg)

Result after print: 

![download_map 1](https://cloud.githubusercontent.com/assets/6613530/25946218/5e25b092-3674-11e7-9527-bb99689819ed.png)

**Comment by acorbi** [comment]
> Missing image

@Huyeng With this you mean the logo of the organization on the bottom-left corner of the produced result, correct?

**Comment by acorbi** [comment]
Some addtional tasks after reviewing the implementation:

- [ ] Make the SAVEMAP_UPLOAD_DIR configurable under **Appearance > Open development**

**Comment by prustar** [comment]
@Huyeng -- I like this. Having the OD logo would be nice as well. 
I would also make the legend visible on the print which is something that is hard at the moment because the box is so small. Users need to scroll to be able to read the entire legend.

**Comment by acorbi** [comment]
> I would also make the legend visible on the print which is something that is hard at the moment because the box is so small. Users need to scroll to be able to read the entire legend.

According to the current implementation, legend can be placed on the **left**, **right** or be hidden **(none)**.

@Huyeng See my latest commit on this branch.

**Comment by Huyeng** [comment]
@acorbi  I will merge the last commit with mine. 

I have improved the mapping functionality to work well with the logo and Khmer unicode now. 
Here is the result that tested on Localhost: It looks fine now, I will push the code soon.
![downloaded_map 26](https://cloud.githubusercontent.com/assets/6613530/26351902/908b6d6a-3fe3-11e7-8fa0-34d4e2e21ead.png)

**Comment by acorbi** [comment]
sounds good! you can merge master into your branch and then open the PR
--
Gesendet von der myMail-App für Android Dienstag, 23 Mai 2017, 01:14nachm. +02:00 von Huy Eng  notifications@github.com :

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/943

@Huyeng amazing work! I have been reviewing the code and I could not find the part where the temporary image was stored in the file system. does it mean that now the code generates the **downloaded_map.png** file on the fly?

**Comment by Huyeng** [comment]
You are right, Alex. 
Previously, I coded to store the exported images on our server, but now it was updated to save the diskspace on the server.  It means that the downloaded_map. png won't be stored it on the server.

**Comment by Huyeng** [comment]
You are right, Alex. 
Previously, I coded to store the exported images on our server, but now it was updated to save the diskspace on the server.  It means that the downloaded_map. png won't be stored it on the server.
