### ISSUE TITLE
Public announcement on Home page

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#630]
There is an error on text content on Public announcement both English & Khmer on Home page. 
![pub an](https://cloud.githubusercontent.com/assets/19201022/20879312/bef7323c-bb05-11e6-96e7-dc5ff1a8bd3f.png)
![public ann](https://cloud.githubusercontent.com/assets/19201022/20879313/befbc464-bb05-11e6-8c84-8b11e885a575.png)

**Comment by vatana92** [comment]
And it happened to all announcement on Home page.
![ann](https://cloud.githubusercontent.com/assets/19201022/20879413/469c574e-bb06-11e6-9b8e-b2129ab4fb5d.png)

**Comment by acorbi** [comment]
Thanks @vatana92 , I will focus on this one today.

**Comment by acorbi** [comment]
@Huyeng can you please give a quick look at this Issue. I have been researching for the possible origin of the problem but could not find anything...

**Comment by Huyeng** [comment]
Ok. I will have a look and fix it.

**Comment by Huyeng** [comment]
@acorbi, the problem caused by the get_the_except function that query the content by post ID from the POST post type. If not result, it will get the latest one of POST post type.
