### ISSUE TITLE
The translated dataset/publication are not appeared on the Khmer page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#634]
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/20920059/18fc165a-bbd1-11e6-8820-d1ac2c6f45f4.jpg)

**Comment by acorbi** [comment]
@Huyeng please ALWAYS provide links to the sites where the issues are reproduced, I cannot know which profile this is so I need to spend unnecessary time looking for it :arrow_right: https://wiki.opendevelopmentmekong.net/public:bug_reporting

**Comment by acorbi** [comment]
Closing, this belongs to https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/634
