### ISSUE TITLE
Present labels and not ids on dataset detail page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#636]
On datasets detail pages like https://opendevelopmentcambodia.net/dataset/?id=eb5380de-ce88-45b3-96a8-6bb9fbe99d30, ids instead of labels are appearing for those fields where we do not store free-text ( document type, language )

![screenshot from 2016-12-06 16-38-00](https://cloud.githubusercontent.com/assets/384894/20931738/5d85b03c-bbd2-11e6-8d1c-be9dc42b6866.png)

**Comment by Huyeng** [comment]
How about the resource title?
The resource's title is translated, but the translated texts are displayed. 
WP: 
https://opendevelopmentcambodia.net/km/dataset/?id=documentation-on-how-to-record-civil-registration-chapter-ii-birth-registration

Datahub: 
https://data.opendevelopmentmekong.net/km/library_record/documentation-on-how-to-record-civil-registration-chapter-i-overview

**Comment by acorbi** [comment]
this belongs to https://github.com/OpenDevelopmentMekong/wpckan/issues/205, closing
