### ISSUE TITLE
Which graphs should be presented on ODC's law's page?

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#638]
@tthy has raised following on today's SC Meeting:

> ODC don’t want to show visualization “Number of records by topic” since it doesn’t show good picture of ODC. “Number of records by language” chat should be better to show on Mekong site.

![screenshot from 2016-12-08 09-51-35](https://cloud.githubusercontent.com/assets/384894/21003490/ed8deeec-bd2b-11e6-9622-54fd6fe9fe7d.png)

@prustar @tthy which graphs should we then present for ODC? should we present any at all?

**Comment by acorbi** [comment]
@tthy @prustar FYI: Currently the "number of records by language" graph of the  laws page on ODC http://opendevelopmentcambodia.net/tabular/laws-profiles-and-agreements/ only presents **English** and **Khmer** as per Try's suggestion.

@tthy @prustar Should we keep those graphs? Reduce their prominency by putting them below the table of results? Remove them at all? Your comments are welcome.

**Comment by prustar** [comment]
@acorbi -- left up to designer now once we have them on board. Closing.
