### ISSUE TITLE
No link to parent profile page

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#652]
![screenshot_7](https://cloud.githubusercontent.com/assets/19201022/21179542/1928b74e-c227-11e6-8851-9189accd8d9b.png)

**Comment by acorbi** [comment]
thanks @vatana92 .

@Huyeng can you implement this one? you have more experience with the breadcrumbs.

**Comment by Huyeng** [comment]
Sure.

**Comment by Huyeng** [comment]
@vatana92, hope this is what you are expected. 
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/21304153/cea4b7e0-c5f5-11e6-8cf5-4e7575cb93a8.jpg)
