### ISSUE TITLE
Disclaimer X button doesn't work in ODC

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#654]
X Button doesn't work 

![capture](https://cloud.githubusercontent.com/assets/16559612/21179653/01646400-c1c3-11e6-9e99-f037dbadc0f0.JPG)

In https://opendevelopmentcambodia.net/topics there is no X entirely

![capture1](https://cloud.githubusercontent.com/assets/16559612/21179664/0a33613a-c1c3-11e6-82ff-137768bb77f0.JPG)

**Comment by acorbi** [comment]
hi @jpeizer1 I could reproduce the issue but then it went away by refreshing with CTRL+F5. could be a caching issue.

Would you please try refreshing the site, then it should be fine again:

![screenshot from 2016-12-14 12-29-58](https://cloud.githubusercontent.com/assets/384894/21180402/13ebd4a6-c1f9-11e6-9666-2ec2cd3730f1.png)
![screenshot from 2016-12-14 12-30-11](https://cloud.githubusercontent.com/assets/384894/21180401/13eb1534-c1f9-11e6-8464-f9d8efb99ed8.png)

**Comment by jpeizer1** [comment]
Yes thanks CTRL F5 worked and I'd strongly suggest keeping the background white. that works best to keep the whole message more in the background.

**Comment by acorbi** [comment]
@jpeizer1 the background stays as it is now. closing this
