### ISSUE TITLE
[Interactive map] Enable English placenames on the interactive map when users are on EN pages on country sites 

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#656]
@Huyeng @acorbi Is it possible to enable placenames in English on EN pages of country sites? This is especially important since we do not have province, district, commune boundaries available as a layer (we used to have them n ODC old site. I'm aware that we have Census 2008 data on the map, which presented as choropleth map). 

This issue came up when I demo the site to small donor group in the U.S. who are interested in looking at development trends and zooming into their grantee projects in Cambodia.

cc: @prustar I'm not sure if this been has raised before. If you agree that this is important, can we ask for a feature request for future implementation?

ODC
<img width="1437" alt="screen shot 2016-12-15 at 6 30 07 am" src="https://cloud.githubusercontent.com/assets/6489398/21205956/9e24dd8c-c291-11e6-9d6d-f206d5a78585.png">

ODMm
<img width="1440" alt="screen shot 2016-12-15 at 6 31 18 am" src="https://cloud.githubusercontent.com/assets/6489398/21205941/89371f0c-c291-11e6-88b8-41703f52494c.png">

**Comment by Huyeng** [comment]
The standard tile server of OSM tries to display labels in the local language. The tiles already contain the labels, so you can't remove them afterwards.  Unless, there is a different tile server which displays English labels to use. Then, we can switch the different tires of map for different sites. @prustar, do you know if there is tires of OSM that available for both English and localization?

**Comment by acorbi** [comment]
@gimmemochi @Huyeng @prustar Here some details about the topic of the issue:

http://stackoverflow.com/questions/18589621/setting-map-language-to-english-in-openstreetmap-with-leafletjs

I would suggest to add a "neutral" layer to the list of selectable base layers which could be selected on those demo situations

**Comment by prustar** [comment]
@gimmemochi we need to find a layer that suits everyone.  Boundary data is contentious and was the reason why they were removed.  There is an existing layer available that is being used on Vietnam now which we could use as a standard across the platform.  All country partners can select it on the backend if they  want. 

I'm not sure if the features are available for a different base layer on the different languages sites. @acorbi it may not make sense to change this, relies on user demand.

**Comment by Huyeng** [comment]
Before the no-label of OSM is used as the base map, however, since the HTTPS is required, it doesn't work.

**Comment by acorbi** [comment]
> I'm not sure if the features are available for a different base layer on the different languages sites. @acorbi it may not make sense to change this, relies on user demand.

Each country site can select a different **default** base layer. 

At this point I see 2 options for this:

1. We set the default base layer to **Nextgis** on all sites. This layer contains only english names
![screenshot from 2017-03-22 10-03-34](https://cloud.githubusercontent.com/assets/384894/24189852/e492ce54-0ee6-11e7-9b9f-ed8e8cb7cb9a.png)
 
2. We look for the URL of an OSM tile server that provides a better alternative

**Comment by prustar** [comment]
@gimmemochi - Can you please define the requirement for each of the maps. i.e. you want an English language map for the English side and a local language for the local side? 

I'm not sure if we can set these base layers separately for the different languages? @acorbi @Huyeng can you help clarify then we can look for the appropriate maps. It's hard to please everyone and perhaps we need to explore creating a specific map.

**Comment by gimmemochi** [comment]
@prustar Correct. The user group I spoke to would like to have an English language map for the English site and a local language for the local site.

**Comment by prustar** [comment]
I reset the ODM map to the NextGIS map. We still need to find another map for the national sites that is suitable to both English and local language user.

**Comment by prustar** [comment]
Open layers by ESRI - https://livingatlas.arcgis.com/en/#s=0&type=layers&md=basemap:1111
Please try the following and if all available then lets add them as options regardless: 

World Imagery - https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9
World Topgraphic Map - https://www.arcgis.com/home/item.html?id=86d5ed4b6dc741de9dad5f0fbe09ae95
National Geographic World Map - https://www.arcgis.com/home/item.html?id=b9b1b422198944fbbd5250b3241691b6
World boundaries and places - https://www.arcgis.com/home/item.html?id=7270fa65d81a4076a2afea1fba18c18d - This layer should contain access to all ESRI place names in various languages and triggered by user browser. The above layers might use these attributes for the names but I'm not sure.

**Comment by acorbi** [comment]
Hi @prustar thanks for doing the research. I will be taking a look at how to integrate once (or several) of these on the front-end.

**Comment by acorbi** [comment]
@prustar I could add the 4 layers you proposed. Please test current implementation on PP:

- go to wordpress dashboard and select new layers under **Appearance > Open development**
- Save settings and open map explorer

![screenshot from 2017-04-20 16-41-32](https://cloud.githubusercontent.com/assets/384894/25236637/a584ae80-25e8-11e7-8322-4fb3c66125b2.png)

One thing that we should still test would be whether the tiles are actually served localized while browsing the map explorer from a computer which language is different than English and or location is in the region. 

@Huyeng Could you please go to https://pp.opendevelopmentcambodia.net/km/map-explorer from a "Cambodian" computer and paste a screenshot here on how it looks?
