### ISSUE TITLE
Dataset Detail: Reduce size of tags and category in dataset detail page to be consistent

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#657]
The font size of tags and category on dataset detail is too large, it is requested to reduce size to be consistent as other pages eg. https://opendevelopmentcambodia.net/news/cooperation-agreement-with-china/#!/story=post-100573

![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/21210619/271672b4-c2af-11e6-87db-5f0bfb3954b2.jpg)

**Comment by acorbi** [comment]
Implemented and deplyoed. closing...
