### ISSUE TITLE
The Filter of post type on Advance search box is not translated

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#694]
See here: https://opendevelopmentcambodia.net/km/?odm_advanced_nav=1&odm_filter_=1&odm_filter_s=តំបន់ការពារធម្មជាតិ&odm_filter_date_start=&odm_filter_date_end=
<img width="1155" alt="screenshot at dec 25 21-07-32" src="https://cloud.githubusercontent.com/assets/6613530/21471458/9ab99068-cae6-11e6-80c9-bfcab3ae23ef.png">

**Comment by acorbi** [comment]
Basically, you need to translate the strings on https://www.transifex.com/open-development-mekong/odm-wp-odm_theme/translate/#km/enpo/95085025 and deploy the changes

**Comment by Huyeng** [comment]
On the Transifex, the words such as the "Profiles" is already translated (see the screenshot below), but it doesn't translated as the screenshot above. 

 ![screenshot_23](https://cloud.githubusercontent.com/assets/6613530/21535700/33dd96e2-cdab-11e6-9854-6d3d19a72562.jpg)

**Comment by Huyeng** [comment]
No worry, @acorbi. I'm back, so I can fix it myself.

**Comment by acorbi** [comment]
Fixed now
