### ISSUE TITLE
Change base map for map explorer and thematic maps to layers which do not contain conflictive data

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#695]
@hailyodv commented on gitter:

> our vietnamese audiences have the opinions on our base map on the site development mekong. There are Chinese language on the conflicting islands. Can you change the base map, please? We can use the google base map. The labels display in english. I think it's easy for all people to reach our informations on the site too.

@prustar ping

**Comment by prustar** [comment]
@Huyeng -- I remember you found an alternative for this previously and I did remember seeing it deployed. Is the option still available on the WP back end for selection?

**Comment by prustar** [comment]
@acorbi @Huyeng -- please add these to the options for basemaps in WP basemap settings: 

1. https://qms.nextgis.com/geoservices/1001/: TMS - URL: http://a.tiles.mapbox.com/v4/openstreetmap.map-inh7ifmo/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJncjlmd0t3In0.DmZsIeOW-3x-C5eX-wAqTw 

2. https://qms.nextgis.com/geoservices/510/: TMS - URL: https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x} 

3. https://qms.nextgis.com/geoservices/493/: TMS - URL: http://a.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png  


The second one might be a good one for the standards map and the other two could be good to also offer the user as base layers.

**Comment by acorbi** [comment]
@prustar @hailyodv @Huyeng @DragonVirus FYI: I have added number 2 (nextgis) base layer to the list of default ones available on the theme options. You can change it under **Appearance > Open Development** as pictured below:

![screenshot from 2017-02-07 15-22-40](https://cloud.githubusercontent.com/assets/384894/22695096/d147ae00-ed49-11e6-81a3-4deb15e47516.png)
