### ISSUE TITLE
The layer menu on Map explorer is hidden when the notification is appeared

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#705]
A few menu was hidden, the users can see them unless the notification is closed.
![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/21756766/122009da-d658-11e6-9576-08eea5c55b9c.jpg)

Closed the notification:
![screenshot_11](https://cloud.githubusercontent.com/assets/6613530/21756776/458453bc-d658-11e6-8162-05c82ed5c3ae.jpg)

**Comment by Huyeng** [comment]
@acorbi - Per discussion with you, you suggested to keep the notification and enable scroll bar for this page. However, back to the beginning of the designing idea, everyone (OD team) would like to keep the map explorer fix to one screen. Until now the idea has not changed for ODC team, they still suggest to remove or hide the notification on Map explorer as before. I knew that the idea to display notification on this page is to make it be consistent as the other page. Anyways, the page has still not been consistent as the other pages because there is no footer on this page. 

Please let me know if you have any comment on that, enable the scroll bar or hide the notification?

**Comment by acorbi** [comment]
@prustar @DBishton @gimmemochi any comments on this?

**Comment by prustar** [comment]
@acorbi @Huyeng -- I raised before when ODC will be removing the box? It's been a while now. This would be the simplest solution.

**Comment by Huyeng** [comment]
@prustar -  Removing the notification can solve the current problem, but it is not the problem solving. Let thing, if there is other notification besides this, the problem will be happened again.

@prustar - do you prefer to fix the map to the screen?
