### ISSUE TITLE
Suggest to update the link of read more on widget link to the category instead of post type page if have.

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#706]
https://opendevelopmentcambodia.net/profiles/access-to-public-service/

![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/21757299/297eddac-d65f-11e6-972a-244b0843093d.jpg)

**Comment by acorbi** [comment]
as discussed, decide to which category page the user will be taken if the post/profile/news article/etc... has several categories.

**Comment by Huyeng** [comment]
Discussed with the editors, they suggested that when click more, it will bring to the category page, but they also suggested to improve the category page to make it looks better. 
eg
https://opendevelopmentcambodia.net/category/agriculture-and-fishing/agriculture/agricultural-commodities-processing-and-products/crop-products-and-commodities/sugarcane-taxonomy/?queried_post_type=news-article

**Comment by acorbi** [comment]
Related: https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/721

**Comment by prustar** [comment]
@Huyeng @acorbi  -- Interesting didn't know this category page existed. 

But it doesn't allow for users to down the taxonomy tree just up? This could be useful to implement and display the results for data? Just thought.
