### ISSUE TITLE
Should we add a filter box to news, map catalogue and other pages which do not have it?

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#716]
ODC team suggested to offer a filtering box to users on:

- Map catalogue: https://pp.opendevelopmentcambodia.net/layers
- News archive: https://pp.opendevelopmentcambodia.net/news

Although the users should be encouraged to use the main search function, it would be positive to give the users the possibility to filter out results presented on these pages. Possible filters might be:

- Textual search
- Taxonomy

@prustar @ChandaraKhun @DBishton @gimmemochi Please add your comments here.

**Comment by prustar** [comment]
@acorbi in the original spec for the data page, the cover page would direct people to geospatial datasets and other locations for finding data. The map catalogue when fully developed should have search and filter options. We can implement a basic version for the ODC map catalogue page in the interim till we have a fully functional catalogue as ultimately it does make sense. 

Not sure how or what a filter option would look like on news. @DBishton

**Comment by acorbi** [comment]
@Huyeng thanks for your feedback, I will do a test implementation for the filters on archive pages for news, topics, etc... and deploy it on PP for us all to review.

**Comment by Huyeng** [comment]
This issue should be closed since it already deployed on PROD, right?

**Comment by acorbi** [comment]
Correct, let's close it
