### ISSUE TITLE
Should we rename Taxonomy to Category

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#717]
ODC suggested that taxonomy is a bit confusing and users would understand better if we use the word Category across the whole front-end (filters, etc...)

@prustar @ChandaraKhun @DBishton @gimmemochi please add your comments

**Comment by prustar** [comment]
@acorbi -- this was raised by user testing as well, I'm compiling these results for implementation now. English speakers raised this to me recently as well. 

We should use topic as this is what we use on the main menu and actually quite clear about what we are talking about. I don't think there's a need to change the terminology on the back end just everywhere it appears on the front end. 

This also is a good example of how topic/taxonomy distinguishes itself from the use of keywords which we don't currently implement.

**Comment by gimmemochi** [comment]
@acorbi -- I agree with ODC's proposed idea. We made that changed on ODC
Gen I prior to migrating to Gen II.
ᐧ

*Penhleak (Pinkie) Chan* | Regional Network and Partnership Support Manager
| Open Development Initiative, East-West Management Institute | 43 Street
208, Phnom Penh | m: +855 17 340 088 | t: @penhleakchan | s: pinkie_b612 |
opendevmekong.net | OD Mekong Twitter <https://twitter.com/opendevmekong> | OD
Mekong Facebook <https://www.facebook.com/opendevmekong>

**Comment by acorbi** [comment]
Thanks @gimmemochi and @prustar for your comments. I believe we have agreement here. @thetaung2 @yanoak what are your thoughts on this?

> I'm compiling these results for implementation now.
@prustar Please share with me once done and I will coordinate its implementation

**Comment by thetaung2** [comment]
@acorbi -- We agree with ODC's idea as awell. we should use the same word category across the front end.

**Comment by acorbi** [comment]
thanks everyone for feedback. We will then rename **Taxonomy** to **Topics** on the front-end

**Comment by acorbi** [comment]
just renamed Taxonomy to Topic on the front-end. please translate the word "Topic" on following projects on transifex:
https://www.transifex.com/open-development-mekong/odm-wp-odm_theme/
https://www.transifex.com/open-development-mekong/odm-wp-laws-pages
