### ISSUE TITLE
Law Judiciary Link Incorrect on Home Page Slider ODMEKONG

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#727]
Read More... Link Should be: https://opendevelopmentmekong.net/topics/law-and-judiciary/
(all the other topics like Science, Social, Infrastructure on slider go to their related topic link)

Instead it goes to Map-explorer (its neighbor on the slider)

![law-jud](https://cloud.githubusercontent.com/assets/16559612/22268047/feed798a-e253-11e6-9d4e-ee427becf62b.JPG)

**Comment by acorbi** [comment]
@DBishton can you please correct?
