### ISSUE TITLE
Improve data detail page styling

### ISSUE THREAD

**Issue by DragonVirus** [OpenDevelopmentMekong/wp-odm_theme#73]

**Comment by prustar** [comment]
This page has not been styled or developed yet. Please see comments and feedback on issue #50 
![image](https://cloud.githubusercontent.com/assets/14996905/16839377/085d96ee-49cf-11e6-89fe-34ce3904e45f.png)

**Comment by prustar** [comment]
Additionally on the specific dataset page (extracted from CKAN) could we add the location searcher or a visual of the data as CKAN displays it in the resource section? There is a lot of white space to the right where this could be included. 

![dataset](https://cloud.githubusercontent.com/assets/14996905/16839589/2ca73b44-49d0-11e6-81a6-3fae81570981.JPG)

The additional information at the bottom should follow comments listed in issue #961. 
![dataset2](https://cloud.githubusercontent.com/assets/14996905/16839597/37b22422-49d0-11e6-96b1-aa3097d43c30.JPG)

**Comment by acorbi** [comment]
@DragonVirus, as @prustar suggest lets use #50 for discussing the data page http://pp.opendevelopmentmekong.net/data/

This issue will be used to discuss the **dataset detail page** e.g https://pp.opendevelopmentmekong.net/dataset/?id=draft-law-on-environment-impact-assessment-3rd-revision. Prustar paste the relevant feedback from that issue #961 ( that issue number does not belong to this repository).

Also, the issues you raised here are now fixed:

![Uploading Screenshot from 2016-07-17 18-33-55.png…]()

**Comment by prustar** [comment]
@acorbi  @DragonVirus - The following CKAN metadata fields should be presented on wordpress in the following order. This order should be standardised across the platform for profiles, map explorer and catalogue.

Description (This is currently being duplicated in some records) 
Source
Date Created
Temporal Range
Process
Logical consistency
Completeness
Access use and Constraints
Copyright
License
Attributes

Duplicate descriptions on this record: 

![image](https://cloud.githubusercontent.com/assets/14996905/16908993/c726f586-4ccf-11e6-9737-77d4155c819e.png)

![image](https://cloud.githubusercontent.com/assets/14996905/16909000/d596d51e-4ccf-11e6-8037-467126a3bbd7.png)

**Comment by gimmemochi** [comment]
@acorbi @prustar, in the dataset details page, under **organization**, can we simply the string? Currently it shows unique IDs, which I don't think front-end users need. See screenshot. Link: https://pp.opendevelopmentmekong.net/dataset/?id=fao-regional-rice-strategy-asia-and-the-pacific 

<img width="1262" alt="screen shot 2016-07-18 at 4 00 22 pm" src="https://cloud.githubusercontent.com/assets/6489398/16910151/45a41958-4d01-11e6-8306-44ffc9ff4b08.png">

**Comment by gimmemochi** [comment]
@acorbi could we increase space btw the metadata info, under **Additional info**, and the *Latest datasets** and **Latest library records** ? They are running into each other (see pink boxes)

<img width="670" alt="screen shot 2016-07-18 at 4 07 14 pm" src="https://cloud.githubusercontent.com/assets/6489398/16910280/060b7e34-4d02-11e6-8641-6d0188d20c03.png">

**Comment by prustar** [comment]
@gimmemochi - please read comments above. 
@acorbi - when you get a chance could you please implement the metadata exposure to that specified so that we can reduce further comments on this issue, then we can actually assess if these fields and order work well.

**Comment by acorbi** [comment]
This issue has been splitted in others
