### ISSUE TITLE
Add a filter box to map catalogue

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#735]
Add the filter box to map catalogue as the news archive:

![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/22319278/ca4be976-e3b3-11e6-88e2-ec6188c427c5.jpg)

**Comment by gimmemochi** [comment]
@Huyeng Could you provide a quick mockup of how this would look on the Map Catalog?

**Comment by Huyeng** [comment]
@gimmemochi  Here is the mockup, https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/734.
