### ISSUE TITLE
ELC description for adjustment classification

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#738]
Users have raised issue that the categories aren't clear. Perhaps we could also add the '?' explanation to the map category box so users can find this description here as well. 

![image](https://cloud.githubusercontent.com/assets/14996905/22505281/e7d28d4e-e87a-11e6-8875-b828b695c756.png)

Although the description makes sense the category 'adjustment after revocation' is still confusing for some users. This is not a reflection of ODC but the way the government is handling ELC's perhaps we can think of a better classification method to integrate these 4 concessions under the 3 categories. 

@Huyeng @ChandaraKhun @samean @punwath @tthy

**Comment by Huyeng** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/22578388/0a420b94-e9fb-11e6-9544-b1fa4064ef71.jpg)

**Comment by Huyeng** [comment]
@prustar can we close the issue now?

**Comment by prustar** [comment]
@Huyeng -- thanks for doing this.
