### ISSUE TITLE
Add clear search filters on filter box

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#740]
On the newly added filter boxes on archive pages, it would be nice to have a button to clear the filters specified by the user, so the full list of results is shown.

@Huyeng what do you think?

**Comment by Huyeng** [comment]
Yes, I agree with adding the clear filters option. 
What do you think if we just add the link as below:
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/22634006/835e712a-ec58-11e6-9d6a-d5bf965e56ac.jpg)

**Comment by acorbi** [comment]
@Huyeng yes, that would be enough
