### ISSUE TITLE
Should we add a topics option to the main menu on Laos and Thailand?

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#752]
so people can find the land pages we published?

@DBishton this one is editorial, I'm assigning it to you

**Comment by acorbi** [comment]
I would do that. Otherwise that piece of content is currently not accessible for users since we disabled the “horizontal navigation”

**Comment by acorbi** [comment]
@prustar @gimmemochi  @tthy @Huyeng  ping

**Comment by jpeizer1** [comment]
The question I would ask is: What is the benefit of moving data to the country site and then making the topic difficult to find by having no navigation link to it? Having recommended to put the land pages on the related country sites and being able to navigate to each about 5-6 months ago -- I still see more of a downside to not showing information on these sites. With each passing month I think the issue becomes more acute.

**Comment by DBishton** [comment]
'Topics' has been added as a menu item to ODT and ODL. Land topic pages are available under this menu item.
