### ISSUE TITLE
Search function filter doesn't work in Search Result Page

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#766]
The function search on the main menu is working; However, when I get to the  search result page, I cannot use the search box to filter the topic of the search result. 
![image](https://cloud.githubusercontent.com/assets/18112596/23641466/735203e8-0326-11e7-8c42-3c5538286908.png)

After click filter, there is nothing appear.
![image](https://cloud.githubusercontent.com/assets/18112596/23641472/88345a36-0326-11e7-8ff6-a32f5a2e1133.png)

But If I fill the content type like this.
![image](https://cloud.githubusercontent.com/assets/18112596/23641491/aacdddf6-0326-11e7-8424-524e58c1ff00.png)
It is working fine.
![image](https://cloud.githubusercontent.com/assets/18112596/23641522/fc4e62fe-0326-11e7-8b81-20c2ae5586df.png)

**Comment by acorbi** [comment]
Thanks for the detail description @punwath . I'm adding this to the current milestone 2.2.0

**Comment by Huyeng** [comment]
@acorbi - I just saw the new result page in PP 
https://pp.opendevelopmentcambodia.net/?s=family
I would like to suggest to the template as below, what do you think?
Other, I think the part should be improved to be better looks.
contry: ["kh"] language: ["en"] topics: ["Human rights NGOs", "Land", "NGOs", "Human rights associations", "Land policy and administration", "Land and housing rights and evictions", "Human rights"] keywords: 

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/24034968/10834896-0b26-11e7-86fc-3e959263b6a8.jpg)

**Comment by acorbi** [comment]
@Huyeng from your answer, I understand that you have not seen the mockups for the new search page. Please see the designs on https://drive.google.com/drive/u/1/folders/0BymS3LWpLYfoNVFfTlZ5OEFnRkE and provide feedback on the following document https://drive.google.com/open?id=1FigLqgf79glxlwRZH68Cjaq1VzGzLIdrE0uUZNvXdvE

**Comment by Huyeng** [comment]
Thanks Alex. I will give some comments on that.

**Comment by acorbi** [comment]
Fixed now
