### ISSUE TITLE
Topics -- need Better Context Dates

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#77]
Related to the topics boxes its unclear what the dates actually mean in terms of conveying updates - Shouldn't it say "UPDATE Yada Yada" I mean you have this entire page thats linked to with data -- how am I supposed to know what's been updated.

![topicscontext](https://cloud.githubusercontent.com/assets/16559612/16831165/6d909448-4971-11e6-9042-10436d8bd8e8.JPG)

**Comment by prustar** [comment]
I agree with JP here. Are the dates relevant at all in this case? The top topic pages don't get updated that regularly so it might actually point out that we are not updating as often as we should. Font and style of the titles should be bolder and potentially larger.
