### ISSUE TITLE
Use flags to indicate the languages records relate to, countries should be written in plain text

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#770]
On the new data page's layout (https://pp.opendevelopmentmekong.net/data-2/?taxonomy=all&country=all&language=all&license=all&query=forest&page=1), the countries the records relates to are presented for each of the results. Currently, this is done with the site's logo.

![screenshot from 2017-03-09 15-13-09](https://cloud.githubusercontent.com/assets/384894/23753824/2798f5ea-04db-11e7-9ce7-60098d093563.png)

Instead of using the site's logo, we should use country flags based on @DragonVirus mockups

**Comment by Huyeng** [comment]
I would like to suggest to use the country flags instead of the language code. No one know what is vi or km for a common user. 
I know that we are using the iso language code, However, as you are aware, in Cambodia, if you use kh, most  people know that it refers to Khmer, for km, it is always be questioned. 
Thus, all the language code should use the flag icon to name instead of the code.

**Comment by Huyeng** [comment]
One more thing, the the Country logo under the dataset should only displays on the Mekong site, but not the country sites because they are on the country site why the country logo is still added to the records.

**Comment by acorbi** [comment]
Thanks for your comment @Huyeng. Actually, we are using flags to determine languages across the site:

1. on the language selector of the top menu

![screenshot from 2017-03-14 08-32-35](https://cloud.githubusercontent.com/assets/384894/23890193/f3cd187c-0890-11e7-8211-32fe8b415d97.png)

2. On the download column of the laws page

![screenshot from 2017-03-14 08-33-16](https://cloud.githubusercontent.com/assets/384894/23890197/f7a15878-0890-11e7-8413-2ca03038dc31.png)

Then your suggestion makes actually sense. We could then just use the country names to indicate the countries the record relates to (ex: Laos, Thailand).  I am going to change the title of this issue to reflect the correct approach. @prustar @DragonVirus any input?

**Comment by DragonVirus** [comment]
Ya .. agree. I think that way would be better cuz datasets from mekong belong to almost all Geographic area. Showing with the flags might be a bit confusing. I'm now editing it on mock up.
