### ISSUE TITLE
New map doesn't appear on Download Map page

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#774]
I recently published a layer but it doesn't appear on the download map page. Here is the link to the layer: https://opendevelopmentcambodia.net/wp-admin/post.php?post=102607&action=edit.

**Comment by acorbi** [comment]
@Huyeng ping

**Comment by acorbi** [comment]
@punwath I removed the category **Map catalogue** from the layer and now it appears on the download map page: https://opendevelopmentcambodia.net/layers?odm_advanced_nav=1&filter_=1&filter_post_type%5B%5D=map-layer&filter_s=Cambodian+population+and+poverty+rate+2015&filter_date_start=&filter_date_end=

@Huyeng Is this behaviour expected? Shouldn't it be the other way around? What is that category then used for? Can we then remove it if it is not being used? 

Closing this Issue but please comment.

**Comment by Huyeng** [comment]
Nope it is the expected behavior.  Let me check it...
