### ISSUE TITLE
Too many Rows of Space between title and text

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#78]
This is probably an easy CSS issue to resolve since looking at all these links its the same issue the number of rows of Blank Space between Title like "Disclaimer" and where the text starts is excessive. Maybe cut it by a couple of lines of space. 

Please also note contact email is crossed out in Disclaimer page example provided (contact@ewmi-odi.org)

![title-toomanyrows](https://cloud.githubusercontent.com/assets/16559612/16831259/fbffdd9c-4971-11e6-8d55-de10743aeb15.JPG)

![links](https://cloud.githubusercontent.com/assets/16559612/16831265/047a45de-4972-11e6-8599-490d198b35f5.JPG)

**Comment by acorbi** [comment]
this should be fixed now
