### ISSUE TITLE
Data Searches still need to be consistent

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#788]
Did this search on the data page: Community Forest - it brought up 3 results
![image](https://cloud.githubusercontent.com/assets/14996905/24099224/69c54554-0d6e-11e7-8ea9-94f0bf6060ee.png)

On the main search it only brings up 2 datasets: 
![image](https://cloud.githubusercontent.com/assets/14996905/24099271/90219f4a-0d6e-11e7-89cc-3a071e38b54b.png)
![image](https://cloud.githubusercontent.com/assets/14996905/24099280/9d37c09c-0d6e-11e7-9ac4-49af407d09ad.png)

The search omits the 'community fisheries' dataset because it's not an exact match. Would be good to make this logic consistent and I would advocate for more results as outlined - 1. exact match terms 2. 'and' for multiple terms and then 3. 'or' for only one term present in the results.

**Comment by acorbi** [comment]
Thanks @prustar I'm adding this to https://docs.google.com/document/d/1S4OtAdeqBDOwCkLN0fEqEemIS2OcBGUq605Igx57swk/edit#heading=h.f2w3o29hlrlu. See task WP1.14

it is important to note that the data page does not yet use the same searching mechanism as the search page. Once it does, the search should be consistant.

**Comment by acorbi** [comment]
Fixed now since the new data page uses the same mechanisms as search
