### ISSUE TITLE
Search behaviour

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#794]
@acorbi Can't remember if you said that the data pages had the final search function allocated to them but I wanted to highlight this result that I found. I inputted LAND in the search and it produced 42 results however the first two are not tagged with LAND and by reading the title and description I don't see the term LAND in them? What in these records are triggering them to appear first on the list for such a search when clearly they are not the most relevant datasets? 

![image](https://cloud.githubusercontent.com/assets/14996905/24203768/e8785e5a-0f16-11e7-871a-a26126f9349b.png)

**Comment by acorbi** [comment]
@prustar data pages does NOT have the same search logic as search pages yet. I am going to add this Issue as related to that task on https://docs.google.com/document/d/1S4OtAdeqBDOwCkLN0fEqEemIS2OcBGUq605Igx57swk/edit#

**Comment by acorbi** [comment]
Closing, this is implemented now.
