### ISSUE TITLE
Cambodia Green Color Theme - Too light?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#80]
I recommend going a shade or two darker on the Cambodian Green theme as the white on green does not provide enough contrast.

**Comment by prustar** [comment]
The white ribbon get's washed out when on a page with also too much white. 

Suggestion: relating to comments in issue #82, re top ribbons, for country pages expand the theme colour background and conform the text to the same style as the header, for consistency.   

![science1](https://cloud.githubusercontent.com/assets/14996905/16838454/76b25590-49c9-11e6-85d7-8f0723e0eac3.JPG)

**Comment by acorbi** [comment]
@jpeizer1 https://cambodia.pp.opendevelopmentmekong.net seems to feature a darker colour for links now. Would you say this issue is fixed?

**Comment by jpeizer1** [comment]
Best to confer with Huy Eng -- Terry complained multiple times that it was tough to see on a projector. The only way to know for sure is if Huy Eng projects it onto a wall and users can see it clearly. if she says thats the case then its fine. It certainly looks darker to me.

**Comment by acorbi** [comment]
@Huyeng Are we happy with the current green colour? If so, let's please close this issue

**Comment by acorbi** [comment]
@Huyeng Are we happy with the current green colour? If so, let's please close this issue

**Comment by Huyeng** [comment]
We are fine with that.
