### ISSUE TITLE
Speed issues ODC

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#81]
Moving to Cambodia from Mekong and between ODC pages takes incredibly long. I also got three gateway timeouts. Almost impossible to troubleshoot given the wait between clicking link and anything showing (when you dont get a timeout)

**Comment by prustar** [comment]
I also experienced this. I'm using Chrome.

**Comment by acorbi** [comment]
@jpeizer1 @prustar can you try logging out of wordpress (or using incognito mode alternatively)? The caching mechanisms only apply for non-logged users

**Comment by prustar** [comment]
@acorbi - I wasn't logged in at the time.

**Comment by acorbi** [comment]
@prustar is it faster if you try with incognito mode? CTRL+SHIFT+P on firefox

**Comment by prustar** [comment]
@acorbi ODM site better but ODC site still relatively slow.

**Comment by acorbi** [comment]
@prustar thx, Im checking with proteus

**Comment by acorbi** [comment]
Should be fixed. @jpeizer1 @prustar @DBishton please reopen if performance issues happen again
