### ISSUE TITLE
MAP EXPLORER: carto legend

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#817]
![image](https://cloud.githubusercontent.com/assets/14996905/24455835/5106f65a-1491-11e7-9d99-b9b025c9eb9d.png)

Both the category and bubble legend seem to be overlapping. 

The link to carto site is here: https://odm.carto.com/viz/08a5510e-1397-11e7-9780-0e3ff518bd15/map

**Comment by Huyeng** [comment]
Some things wrong with your html legend, please check it again. 
It looks fine for Hydrow dam on ODC map explorer:
![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/24491026/87ae450a-154f-11e7-971f-23a3c09bbf46.jpg)

**Comment by prustar** [comment]
Ok will do thanks @Huyeng

**Comment by prustar** [comment]
@Huyeng -- made this work: 

![image](https://cloud.githubusercontent.com/assets/14996905/24651517/466a66d4-1958-11e7-9a4e-46257a9c2452.png)
See code: 
[odmDAM.txt](https://github.com/OpenDevelopmentMekong/wp-odm_theme/files/892689/odmDAM.txt)

**Comment by Huyeng** [comment]
There are some html format error:
[Html-legend.txt](https://github.com/OpenDevelopmentMekong/wp-odm_theme/files/895455/Html-legend.txt)

Could you confirm that if the Class name of the bold text below if "bubble" or "bubbles"?
`<ul>
	<li>89,000</li>
	<li class="graph" style="background: rgb(221, 221, 221);">
		**<div class="bubbles"></div>**	
	</li>
	<li>
	10,000,000,000
	</li>
</ul>`

**Comment by Huyeng** [comment]
@prustar - can the issue close?

**Comment by prustar** [comment]
@Huyeng - Thanks! I've corrected it now but the legend box seems to cut off the last figure: 

![image](https://cloud.githubusercontent.com/assets/14996905/25428345/dbee3fb8-2a75-11e7-9735-5ec73636af72.png)

Can you increase the size or do I need to reduce spacing in the legend?

**Comment by acorbi** [comment]
@prustar @Huyeng is this now fixed? if so, please close issue
