### ISSUE TITLE
Home Page general comments

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#82]
![home1](https://cloud.githubusercontent.com/assets/14996905/16837715/4b0faa68-49c5-11e6-9855-cbd5b5ac4d37.JPG)

The top ribbon bar is comprised of 3 components and they are all different colours and styles. 
1. The top ribbon with the countries is white and the font and style could be bolder to standout more. When you are on a topic page this header stays present for navigation but often get's washed out with the white of the page. 
2. The topic bar is grey and also not very bold. 

Suggestion: integrate all the three ribbons into the same Mekong Blue background and use the same font and style as the word 'Mekong' uses. 

3. Perhaps it's only my screen but the red lines indicate the white space. This coupled with the full width of the top banner yet not full width of topic areas is not geometric to me. 

Suggestion: reduce the width of the banner to coincide with the margin of topic boxes or visa versa add a topic box to fit the width of the screen.  

4. 'Topic' header needs to be styled and bolder. 

5. I generally dislike the greyed out picture boxes - it makes it difficult to read the text and visually on the pages makes it look overall dark and washed out. There's nothing striking about any of these boxes that makes me want to click on them. 

Suggestion: Replace these grey boxes with ODM designed symbols unique to us. This then could contribute to branding when people see these symbols and associate them with topics on our site. Similar to SDG and predecessor MDG who's symbols are recognised globally.

**Comment by acorbi** [comment]
@prustar implemented your suggestions in regards to menu and slider.

For the greyed out pictures, let's continue the conversation on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/90
