### ISSUE TITLE
Link to manage the data page on search directs to CKAN PP? 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#829]
![image](https://cloud.githubusercontent.com/assets/14996905/24649602/dbcf85b2-1951-11e7-94e5-500cb7d650a2.png)

Found this resource: https://pp.opendevelopmentmekong.net/dataset/?id=5d638fc9-3f09-4ccd-96dd-9f1301d0f321

Hit the manage button (which I like by the way) and it took me to PP instead of Prod. Shouldn't it be Prod or did you do this as an example for now?

**Comment by acorbi** [comment]
@prustar it took you to PP because... you are in PP. the same button on PRod should take you to PROD. Closing this, please re-open if you consider.
