### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#83]
![image](https://cloud.githubusercontent.com/assets/14996905/16838102/c0504a1a-49c7-11e6-8d5d-8c2c72ddf9ee.png)

I gather that there is some more work to be done in styling headings etc. There is far to much white space between the title of the news page and the map. Should the map also already have some news points on it?

**Comment by gimmemochi** [comment]
@acorbi @prustar There's also a lot of while space above the map on the *Profiles* section. See: https://cambodia.pp.opendevelopmentmekong.net/profiles/economic-land-concessions/

<img width="1265" alt="screen shot 2016-07-18 at 5 03 48 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911643/daae7040-4d09-11e6-9f82-56907f54d936.png">

**Comment by gimmemochi** [comment]
@acorbi @prustar also a lot of white spaces in the table containing concession projects. See "Huot Sambat Co. Ltd." https://cambodia.pp.opendevelopmentmekong.net/profiles/economic-land-concessions/

<img width="1265" alt="screen shot 2016-07-18 at 5 03 48 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911702/3b20b898-4d0a-11e6-9767-6c8f5b8fa908.png">

**Comment by gimmemochi** [comment]
@acorbi Also a lot of white spaces in the table containing lists of ELCs project. See "Huot Sambath Co. Ltd." for example: https://cambodia.pp.opendevelopmentmekong.net/profiles/economic-land-concessions/

<img width="1266" alt="screen shot 2016-07-18 at 5 07 03 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911830/f02439fe-4d0a-11e6-9a2a-880895b45f21.png">

A solution might be to collapse the references section by listing only 2 or 3 reference docs with "Read more" or "Show more".
<img width="1270" alt="screen shot 2016-07-18 at 5 10 11 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911833/f8476066-4d0a-11e6-91ca-f74253eaa330.png">
