### ISSUE TITLE
Related links

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#85]
Please hyperlink text and remove file types as in current production instance. Should take user to Dataset record where the file types are available for downloading. 

![relatedlinks](https://cloud.githubusercontent.com/assets/14996905/16841672/90694154-49da-11e6-94cf-decabfbcb886.JPG)

**Comment by acorbi** [comment]
Fixed. @DBishton @prustar FYI: in the wpckan widgets now there is an option to configure which fields are outputted, both for datasets and resources. In this example, to hide the resources' formats, I just set the **output fields for resources**  to blank on the widget config:

![screenshot from 2016-07-15 14-50-39](https://cloud.githubusercontent.com/assets/384894/16874804/b412760e-4a9b-11e6-97cc-96ea19855720.png)
