### ISSUE TITLE
Editors should be able to manually curate the posts shown via ODM Custom posts widget

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#857]
Currently, the **ODM Custom posts** widget pulls the latest posts from a certain post type and sorts them by:
- creation date
- modification date

It would be useful to let them specify manually the list of posts and their which will be displayed

![screenshot from 2017-04-24 18-09-36](https://cloud.githubusercontent.com/assets/384894/25346901/6c2556ce-2919-11e7-89b2-e7a046719fec.png)

I would implement this by adding a field where editors should be able to add a comma-separated list of post ids to be displayed.

**Comment by prustar** [comment]
@acorbi -- suggestions for this specification as noted in my email: 

1. Provide sort function to the user to allow them to view by date (published and modified), taxonomic category (which would be the tree) and most viewed/popular. 

2. Allow for an "Editors Pick" function which would highlight the most relevant agenda topic of that week with related briefings, profiles, datasets and news. (This would need some thought on how to present and design).

**Comment by acorbi** [comment]
@DBishton @prustar   this is now implemented on PP:

Now you can enter a **comma-separated list of post slugs** to hand-pick posts to show on the widget hence overriding the **Order by:** parameter:

![screenshot from 2017-04-27 14-00-10](https://cloud.githubusercontent.com/assets/384894/25482695/25a606ee-2b53-11e7-9662-a557bc0e04d3.png)
