### ISSUE TITLE
Search Enhancement requirement

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#866]
@acorbi -- a specific search requirement came up during our discussion today with ODC and is one of the major complaints from users. This relates to the company profiles. 

As you know the ELC profile and others have a list of specific company pages that list the details for example: https://pp.opendevelopmentcambodia.net/profiles/economic-land-concessions/?feature_id=elc_gdc_10 

When a user does a search for this company GG World Group nothing relevant comes up. We tested this on PP to see if the new search function would improve this. 
![image](https://cloud.githubusercontent.com/assets/14996905/25481304/d9e3df98-2b4c-11e7-9790-bbd4ece048da.png)

So I thought I would test the keyword field to see if we added the company name as a key word in one of the related references if this would allow it to search for the law and bring it up upon the search. This is the dataset: https://pp.opendevelopmentcambodia.net/dataset/?id=35-09-01-2015 and in CKAN with the tag added: https://data.pp.opendevelopmentmekong.net/laws_record/35-09-01-2015

When we do the search again nothing comes up still. 

This is a major issue as the profile repository is the most visited of all of the content on ODC and researchers go to it to find information on concession allocation and companies. 

The requirement would be to improve the search so that indeed the keyword field is searched and bringing back hits when entered and also that each company profile page is searchable and displayed as a result when searched.

**Comment by acorbi** [comment]
@prustar thanks for raising this. There was indeed a bug on the "old" template which caused the CKAN results not to be returned correctly. Now that record appears on the top of the list of data results ( right column)

https://pp.opendevelopmentcambodia.net/?s=GG+World+Group&type=all&taxonomy=all&language=all&license=all

Closing this

**Comment by Huyeng** [comment]
It would be great if the result of the search content this url to the individual profile like the google:
https://pp.opendevelopmentcambodia.net/profiles/economic-land-concessions/?feature_id=elc_gdc_10

![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/25522347/c663a044-2c2c-11e7-942a-a96314352e19.jpg)

**Comment by acorbi** [comment]
Hi @Huyeng, can you please raise this in a different issue? thanks

**Comment by Huyeng** [comment]
No problem. I commented here because I think that it is what Pyrou referred to. 
Moved to issue: #874
