### ISSUE TITLE
Search content on profile page's spreadsheet

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#874]
It would be great if the result of the search content this url to the individual profile like the google:
https://pp.opendevelopmentcambodia.net/profiles/economic-land-concessions/?feature_id=elc_gdc_10

![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/25522347/c663a044-2c2c-11e7-942a-a96314352e19.jpg)

**Comment by acorbi** [comment]
Good idea @Huyeng . Actually we can index the individual profile items. I will take a look at how to do this asap.

**Comment by acorbi** [comment]
The steps to complete are:
- [ ] Download CSV files for each profile both in EN and KM
- [ ] Write python script on http://github.com/OpenDevelopmentMekong/data which goes through the entries and indexes documents with following attributes: content, permalink, title, excerpt, id (?), country_site, blogdomain, odm_spatial_range, license_id, type (profile_item?), blogid, odm_language

**Comment by acorbi** [comment]
Moving to https://github.com/OpenDevelopmentMekong/data/issues/13
