### ISSUE TITLE
Uniform style for accordion contents

### ISSUE THREAD

**Issue by DragonVirus** [OpenDevelopmentMekong/wp-odm_theme#887]
**Example**
https://pp.opendevelopmentmekong.net/why-become-a-data-contributor-to-open-development-mekong/
<img width="535" alt="screen shot 2017-05-03 at 5 02 34 pm" src="https://cloud.githubusercontent.com/assets/1311765/25657179/8bdcf732-3022-11e7-93fb-a37c6f663347.png">

**Comment by acorbi** [comment]
Closing this, accordion menus currently present the same look-and-feel across the whole site
