### ISSUE TITLE
Geo tagged news on the map should be shown in Khmer Site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#891]
Currently, the pop-up news on the map doesn't support in multiple language.
<img width="1246" alt="screenshot at may 04 12-44-13" src="https://cloud.githubusercontent.com/assets/6613530/25691681/7881e2c4-30c7-11e7-9682-47b9208d7767.png">

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/907
