### ISSUE TITLE
odm_excerpt function should not return HTML content, just plain text

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#894]
A post's excerpt should just contain plain text and no HTML elements. Otherwise this type of layout issues appear:

![screenshot from 2017-05-04 16-17-25](https://cloud.githubusercontent.com/assets/384894/25707920/45c68eca-30e5-11e7-830f-ee0ece80de65.png)

**Comment by Huyeng** [comment]
I would like to suggest to fix it by adding the new parameter to show the paint text or html.

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/950
