### ISSUE TITLE
Define and implement look and feel for grid boxes

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#90]
![screenshot from 2016-07-15 17-59-11](https://cloud.githubusercontent.com/assets/384894/16880509/dbd2b572-4ab5-11e6-9599-ac858fa5d537.png)

Inspiration:
http://tympanus.net/Development/HoverEffectIdeas/index2.html
http://datausa.io/

**Comment by prustar** [comment]
Other inspiration: 
http://www.bbc.com/
