### ISSUE TITLE
Custom post widget date display option

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#908]
Hi @acorbi ,

I am requesting the ability to display 'last updated' date rather than created date on thumbnails for custom post widgets:

![image](https://cloud.githubusercontent.com/assets/1206387/25883931/b34ae724-3578-11e7-9333-1f6961019f04.png)

This should ideally be an option as we can't assume all partners will want to do this

**Comment by acorbi** [comment]
Hi @DBishton that option is already available (since several months actually) as indicated on https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0#odm_custom_posts_widget_in_detail

closing
