### ISSUE TITLE
Duplicate categories need to be removed 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#912]
@acorbi 
![image](https://cloud.githubusercontent.com/assets/14996905/25899753/0c5c2754-35b7-11e7-836a-b94cdfd6543b.png)

The list of results is duplicated and the main page needs to be removed. It should display the first resource type list of results which is 'Datasets' and this should be highlighted. Note that when you do click on 'Dataset' it isn't highlighted. 

![image](https://cloud.githubusercontent.com/assets/14996905/25899857/80a31ee2-35b7-11e7-9b7a-43c6d98387db.png)

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/54
