### ISSUE TITLE
Data page category box

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#913]
@acorbi -- for consistency with the search would it be useful to also add the category breakdown box on the top right for users to be able to easily distinguish between the resource types? This is a question as that perhaps we need to test with users, as there is a filter option available but the nice thing about the box in the search is that it displays clearly the number of records found for that data type: 

![image](https://cloud.githubusercontent.com/assets/14996905/25933850/3cfa984e-3640-11e7-8a6a-730895e254e3.png)

![image](https://cloud.githubusercontent.com/assets/14996905/25933862/5bd191c8-3640-11e7-8395-6fa88d8943d3.png)

**Comment by acorbi** [comment]
@prustar agreed, will add to my todo list, it is a quick one

**Comment by acorbi** [comment]
Implemented
