### ISSUE TITLE
Prevent 'contact us' form rendering in iframes

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#918]
Currently the orange 'contact us' tab appears in iframes, duplicating its presence on pages:

![image](https://cloud.githubusercontent.com/assets/1206387/25943054/d124fca8-3668-11e7-9d5d-92d61f4dc5f3.png)

Please hide.

**Comment by acorbi** [comment]
@DBishton im working on this now. just one comment at the moment, please ALWAYS add URLs to the pages where the Issue can be reproduced.
