### ISSUE TITLE
Add call for partners text to OD Vietnam Landing page for Land

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#927]
@acorbi Now that PanNature is no longer a country partner, we should put up the call for partnership text to OD Vietnam site, too. See this for example: https://laos.opendevelopmentmekong.net/

<img width="1216" alt="screen shot 2017-05-18 at 5 50 25 pm" src="https://cloud.githubusercontent.com/assets/6489398/26199163/33564dd4-3bf3-11e7-9c28-db28f5bcb7ab.png">

Text:
Open Development Initiative supports a network of organizations co-managing a common open data and knowledge platform to illuminate development trends in the Lower Mekong region at country and regional levels. Would you like to join efforts with us in building a data and information ecosystem to support transparent sharing of development data and inform constructive dialogue and decision making for sustainable development in Vietnam? We are looking for national partners to contribute to establishing Open Development Vietnam. Learn about how you may participate here <hyperlink to https://opendevelopmentmekong.net/contact/>.

Is this something that I can do or you can do easily?

**Comment by acorbi** [comment]
@gimmemochi done.

For your reference, you can set the message under **Appearance > Open Development > Notice Message appear above the slider"**
