### ISSUE TITLE
Fix layout of bullets and numbering - maybe a stylesheet issue

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#929]
This issue concerns the Terms of Use page: https://opendevelopmentmekong.net/terms-of-use/
@DBishton @acorbi I couldn't add "indentation" to push the bullet points further to the left. The page appears like this on the front end:
<img width="662" alt="screen shot 2017-05-19 at 4 09 09 pm" src="https://cloud.githubusercontent.com/assets/6489398/26241153/dd58dc06-3cad-11e7-8323-2be6e7c8c1c6.png">

On the back end, this is what the editor menu: 
<img width="643" alt="screen shot 2017-05-19 at 4 06 53 pm" src="https://cloud.githubusercontent.com/assets/6489398/26241347/88b80112-3cae-11e7-95ad-4f84705f47a5.png">

**Comment by acorbi** [comment]
Fixed
