### ISSUE TITLE
Present related resources (datasets, publications) sorted by publication date 'newest to oldest'

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#930]
@acorbi @DBishton This is how the related resources widget are presenting. We need to present the most recent (publication date) on top. For example see Land page: https://opendevelopmentmekong.net/topics/land/

<img width="347" alt="screen shot 2017-05-19 at 5 15 55 pm" src="https://cloud.githubusercontent.com/assets/6489398/26243729/156a9ed2-3cb7-11e7-8989-3cd58143144e.png">

Is it possible to present the newest first?

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wpckan/issues/280
