### ISSUE TITLE
Showing Chinese financial aid map layer by default on Aid and development page, remove "Contact us"

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#931]
@DBishton  Is it possible to show the Chinese financial aid project by default? Right now user would have to click. It doesn't make sense because there's only one layer. And there's a "contact us" box on the map which we should remove (maybe the latter is for @acorbi to look into).

Aid and development assistance page: https://opendevelopmentmekong.net/topics/aid-and-development-assistance/

![screen shot 2017-05-19 at 6 30 37 pm](https://cloud.githubusercontent.com/assets/6489398/26246154/db6c6066-3cc1-11e7-807d-6adca00bc763.png)

**Comment by acorbi** [comment]
@Huyeng you developed this functionality. can embedded layers be activated by default? I do not see instructions on how to do it on https://wiki.opendevelopmentmekong.net/partners:thematic-maps#how_to_embed_only_single_layer_on_a_page_without_creating_map

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/jeo/commit/9ef1414c0d6c7c279689376d8ba77a0fa6bb11ac

**Comment by Huyeng** [comment]
> can embedded layers be activated by default? 

If the layer is embedded using the layer id as below, it will automatically activated by default. 
`<iframe src="https://OD_WEBSITE/embed/?layer=LAYER_ID&width=100%&height=500" width="100%" height="500" frameborder="0"></iframe>`

However, it the embedded the map through the map ID, you can set Enable or Disable layer in by using the layer option  on edit page of map. 

FYI: the wiki is updated now.

**Comment by acorbi** [comment]
Thanks @huyeng, as you can see in the comment above, there was an js issue on JEO theme which i fixed.

thabks for updating the wiki

**Comment by gimmemochi** [comment]
@acorbi @Huyeng I followed the guide. I think this is a bug because the map layers previously works  on the water pages. 
See this as example: 
https://opendevelopmentmekong.net/topics/water-governance/ 
https://opendevelopmentmekong.net/topics/human-demands-and-implications/

Now they don't work.

**Comment by acorbi** [comment]
@gimmemochi it should be a caching issue since it is working for me both on Chrome and Firefox

**Comment by Huyeng** [comment]
It also works for me too. @gimmemochi
