### ISSUE TITLE
[LOD] Expose a link to navigate more content on Land from the Land portal

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#932]
@acorbi Currently we are only showing 10 records from the Land Portal. Is it possible to add a link that would read "More ..." at the bottom of the widget? See screenshot below.
https://opendevelopmentmekong.net/topics/land/
<img width="941" alt="screen shot 2017-05-21 at 4 23 48 pm" src="https://cloud.githubusercontent.com/assets/6489398/26282806/b675ba1e-3e42-11e7-89b2-5fac560c3b58.png">

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wp-odm_dash/issues/78

**Comment by acorbi** [comment]
@gimmemochi why did you reopen this? Can you please provide details?

**Comment by gimmemochi** [comment]
@acorbi Thanks for the fix, but could we align the "More ..." to the right hand corner? See how we present that on other widgets below:

<img width="356" alt="screen shot 2017-05-22 at 8 55 19 pm" src="https://cloud.githubusercontent.com/assets/6489398/26312449/cfcee234-3f31-11e7-968e-f3f4e1b7c46f.png">
<img width="300" alt="screen shot 2017-05-22 at 9 00 53 pm" src="https://cloud.githubusercontent.com/assets/6489398/26312450/d13755ac-3f31-11e7-9a6d-3dccb9b42b7e.png">

**Comment by acorbi** [comment]
@gimmemochi same issue, you need to refresh the site without loading the cahce. please use CMD + SHIFT + R and should appear properly aligned
