### ISSUE TITLE
Add "Laos" to country filter option on SEARCH page

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#934]
@acorbi This is a bug. Please fix :)
https://opendevelopmentmekong.net/?s=land
<img width="1197" alt="screen shot 2017-05-22 at 1 38 39 pm" src="https://cloud.githubusercontent.com/assets/6489398/26295573/bab4fc72-3ef4-11e7-924d-9b1aa203b601.png">

**Comment by acorbi** [comment]
This belongs to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/67
