### ISSUE TITLE
Implement new design template for SEARCH and DATA page on vacant country sites

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#935]
@acorbi Is it possible to implement the new search design and data page design on OD Laos, Thailand, and Vietnam?

<img width="1208" alt="screen shot 2017-05-22 at 1 45 50 pm" src="https://cloud.githubusercontent.com/assets/6489398/26295643/11960216-3ef5-11e7-95f8-0acb8a64e22d.png">

**Comment by acorbi** [comment]
Done
