### ISSUE TITLE
Change timestamp on topic page to reflect 'content update' date

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#938]
@acorbi Can we please change the visible date (timestamp) to the actual date when content is updated?
I understand that WordPress records two types of dates: 1) created date, 2) updated date

This updated date will change when an editor go into a page and actual update the content or simply fix a typo. We do not want to update the 'visible date' unless we actually update the content. The way we are doing it now is to make visible this automatic updated date. Is it possible to create a field where the editor can input or pick which date to make visible on the site?

Current implementation:
https://opendevelopmentmekong.net/
https://opendevelopmentmekong.net/topics

<img width="1148" alt="screen shot 2017-05-22 at 2 50 51 pm" src="https://cloud.githubusercontent.com/assets/6489398/26297723/52939568-3efe-11e7-86bc-af28dcc15ba4.png">

<img width="1187" alt="screen shot 2017-05-22 at 2 53 04 pm" src="https://cloud.githubusercontent.com/assets/6489398/26297766/875fbfe2-3efe-11e7-8709-b99ff2f6aee1.png">

**Comment by acorbi** [comment]
@gimmemochi Editors can specify which date to show on those widgets by configuring them (See https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0#odm_custom_posts_widget_in_detail). As you guess **created date** or **modification date** can be selected.

In my opinion, fixing a typo IS updating the content and should reflected the way it is now. Adding a field so editors specify the date to be shown would increase the complexity of the editorial workflow and I would rather not encourage to do that.
