### ISSUE TITLE
Duplicated "Land: Laos/thailand" contents between ODM and ODL/ODT

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#940]
@DBishton Currently we have both a **Land: Laos** topic page on ODM https://opendevelopmentmekong.net/?post_type=topic&p=1779366 and the corresponding site on ODL https://laos.opendevelopmentmekong.net/topics/land/

This is a content duplication which appears on the search results: https://opendevelopmentmekong.net/?s=land&type=topic

Same happens for Thailand.

I believe the Land: Laos and Land:Thailand pages should be deleted from ODM. Or is there a reason for them to still be there after we copied them over to the corresponding country pages?

**Comment by acorbi** [comment]
@DBishton I see those contents are stored as drafts. I will make sure no **drafts** are indexed and exposed on the search but, can we remove those topics from the regional site anyway? or do we need them for anything

**Comment by jpeizer1** [comment]
@DBishton @acorbi Since this data was moved to the related country sites it's not clear why they would remain on the regional site. If similar data for Myanmar, Cambodia, Vietnam only exist on the country site, I'd think the other countries sites now with this data would follow the same standard.

**Comment by acorbi** [comment]
@DBishton can you please confirm that those records can be deleted from the regional siteß

**Comment by DBishton** [comment]
@acorbi @jpeizer1 These can be removed. I believe they were put back into draft status after publishing on ODT and ODL.

**Comment by acorbi** [comment]
@DBishton @jpeizer1 ok, Ill delete them. closing this
