### ISSUE TITLE
'Resource not found' 404

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#942]
Hi @acorbi,

Our new intern Lauren recently discovered a 404 when trying to download a dataset, the record being:
https://opendevelopmentmekong.net/dataset/?id=ba1a946b-524c-41c1-a6f3-f920f6ce6894

When attempting to download the dataset, this error was thrown:
https://opendevelopmentmekong.net/dataset/?id=ba1a946b-524c-41c1-a6f3-f920f6ce6894

Are you able to look into whether it is an issue with this specific file or something else?

Many thanks,
Dan

**Comment by DBishton** [comment]
Hi @acorbi,

I just tested this again and have the same issue. Steps are:

1. click 'log in'
2. click 'Forgot your password?'
3. Enter Username: "DBishton"
4. click 'Request reset'

**Comment by acorbi** [comment]
@DBishton I looked into the resource and indeed the PDF file is missing. I have been checking whether other old records are missing resources but could not find any other. This might be an isolated case, and actually the PDF should be reuploaded, but we should definitely keep an eye on this kind of issue.

@ChandaraKhun can you please try to re-upload the file and use the oportunity to update the metadata? https://data.opendevelopmentmekong.net/dataset/ba1a946b-524c-41c1-a6f3-f920f6ce6894

I'm closing this by the moment, please re-open if you reproduce again.
