### ISSUE TITLE
Search-- Just did this search

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#948]
I did an exact search for a title of a paper "An Overview of Large-Scale Investments in the Mekong Region" the search page showed this initially: 

![image](https://cloud.githubusercontent.com/assets/14996905/26433956/db847f76-412f-11e7-8fe7-da517946070e.png)

I loaded this resource so I knew it was there. I didn't notice that on the left it did actually find it and so had to figure it out - and I know the default - so is there something we can do when there is an exact match and only one record available to make it so that this document is displayed by default instead of the currently default for dataset? 

ie - Only one library record found. 
![image](https://cloud.githubusercontent.com/assets/14996905/26433986/1bb12a86-4130-11e7-9ac8-9a98ab115d79.png)

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/71
