### ISSUE TITLE
The single page of news is loading very slow when the category list is added

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#951]
Suggest to improve the page.
https://opendevelopmentcambodia.net/news/livelihood-incentive-for-workers-as-industrial-park-enters-jv/

**Comment by acorbi** [comment]
@Huyeng probably the bottleneck is on the taxonomy widget on the sidebar. Loading a single article should not take long

**Comment by Huyeng** [comment]
The issue was fixed with this commit.  https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/954/commits/066993c646613c5df9cea05d9965e5c48a0fc723
I added a line of function to replace your php script.
