### ISSUE TITLE
Contact button overlays print-a-map button on map explorer

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#953]
Should be moved somewhere else where it does not disturb so much.

![screenshot from 2017-05-25 11-07-19](https://cloud.githubusercontent.com/assets/384894/26443907/8b9a302c-413a-11e7-865c-78b21607b281.png)

**Comment by acorbi** [comment]
@Huyeng @gimmemochi @prustar @DBishton @DragonVirus I personally would rather move the contact button to another place where it does not disturb. Here some mockups/suggestions:

### Presenting "conversation" symbol on header

My personal preference would be to integrate this button on the main header, which is the element always visible and where other "communication" links are provided.

![mock_up_contact_4](https://cloud.githubusercontent.com/assets/384894/26447089/37ae5c2e-4147-11e7-91a9-13d4022d6fd5.png)

### Presenting the button horizontally on header

In the same direction but using the existing button and no symbol.

![mock_up_contact](https://cloud.githubusercontent.com/assets/384894/26447125/552d841e-4147-11e7-9abf-1dc4c84fe9d6.png)

### Bottom-left corner

Here it should not disturb any element either

![mock_up_contact_2](https://cloud.githubusercontent.com/assets/384894/26447145/6a6eb5fa-4147-11e7-87ae-f50ee9b23f76.png)

### Just moving it a bit downwards

![mock_up_contact_3](https://cloud.githubusercontent.com/assets/384894/26447159/7cc4701e-4147-11e7-8a0e-f0e69cd8c90e.png)

@gimmemochi this one needs discussion I guess, can you please coordinate? Thanks

**Comment by Huyeng** [comment]
If you move it down, it will overlay with the legend of the map. 
I would like to suggest to resize the box to be smaller, and move the leaflet tools bar to right abit. 
Like this, what do you think? 
![screenshot_11](https://cloud.githubusercontent.com/assets/6613530/26447520/11fe929c-4173-11e7-8966-a6818c37463a.jpg)

**Comment by acorbi** [comment]
@Huyeng In general, I do not think it is a good idea to have that button there. It is going to conflict with some contents sooner or later. I advocate to implement my first suggestion, we can think about using tooltips or any mechanism (i.e adding a link on the footer) to make the user aware of that feature

**Comment by DragonVirus** [comment]
How about just having it as menu item in navigation ? 
![screenshot](https://cloud.githubusercontent.com/assets/1311765/26447597/30739eb0-416f-11e7-84ea-e705cbd5a530.png)

Between i think the envelope icon which is linked to the contact page (https://opendevelopmentmekong.net/contact/) and this contact button will make the users a bit confusing. @acorbi Don't you think ?

**Comment by acorbi** [comment]
thanks @DragonVirus , your suggestion would be also a consistent solution.

Actually, there is some duplication on those 2 elements:
- pop-up window with feedback options opened when clicked the orange button
- contact page opened from the envelope icon on the header.

my suggestion is to unify both. either by integrating the options provided by the popup on the contact page (https://pp.opendevelopmentmekong.net/contact/) or by adding the possibilities to sign-up for the newsletter on the pop-up window

**Comment by DBishton** [comment]
@acorbi @DragonVirus We already have a contact icon in the top right hand corner (email icon beside Facebook and Twitter icons). These shouldn't be duplicated -- can we use that pre-existing icon?

**Comment by acorbi** [comment]
@DBishton jup, we could re-use that button as well.

@gimmemochi @prustar @ChandaraKhun can we please have your thoughts?

**Comment by thetaung2** [comment]
Agree with @DBishton to re-use that button.

**Comment by acorbi** [comment]
@gimmemochi @prustar @ChandaraKhun can we please have your thoughts?

**Comment by gimmemochi** [comment]
@acorbi I support implementing @DragonVirus design, but suggest we consolidate info on the orange pop-up box with the subscribe to OD Newsletters/updates.  

As of now only 3 people has signed up for newsletter via the **envelope** icon next to the Twitter and Facebook icon. If we consolidate, we should remove this icon.

**Comment by prustar** [comment]
Comment still stands. Don't see issue with either option. Which is easier and more obvious user. Do we have stats on current usage of contact button or email symbol on top? Moving a button can be irritable to regular users.

**Comment by Huyeng** [comment]
On ODC site, there is no enough space to place the Contact us button on the main navigation because we are going to add one more button (data/library).  See this screen:
![screenshot_2](https://user-images.githubusercontent.com/6613530/27113166-891a7edc-50e5-11e7-9e95-179063d063c7.jpg)

Moreover, some of ODC users has been familiar button and use it to contact us, moving to other place may not easy to find for them when they would like to ask some questions. 

I will improve this a bit to automatically collapse in a few second after loading. Any comments to enhance this button will update further more.

**Comment by gimmemochi** [comment]
@acorbi Can we break this into 1 issue and 1 enhancement request? 
Issue: Move the Contact us box down a little bit as Huy Eng described. This should be fixed ASAP.
Request: To consolidate "Contact us" so that they contains the same message/instruction. We can do this on another date.

**Comment by acorbi** [comment]
@gimmemochi good suggestion.

The issue has now being closed since the contact button now auto-collapses after a couple of seconds.
and I opened a new Issue for the feature request: https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1038
