### ISSUE TITLE
Needs the text box to custom the popup information of WMS layer

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#956]
Currently, the pop-up information of WMS layer on the map explorer doesn't look interesting and hard to read. Suggests to add the textbox like the profile page that allow the mapper to list some attributes that would like to appear on window popup.
Sample:
![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/26447202/97a08088-4171-11e7-939d-865023ec3f42.jpg)

**Comment by Huyeng** [comment]
Setting of infowindow:
<img width="765" alt="screenshot at may 29 14-30-52" src="https://cloud.githubusercontent.com/assets/6613530/26540336/1f22891e-447b-11e7-8e2f-a77c3a8f48c4.png">

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/969/commits/badddda2e4d3f6c793c1ceab803b443ec3fb4332
