### ISSUE TITLE
Enhancing social media sharing buttons

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#958]
@acorbi Our social media icons are not aligned well on Chrome (See 1). On Safari, they don't appear at all.

<img width="1440" alt="screen shot 2017-05-26 at 9 02 18 am" src="https://cloud.githubusercontent.com/assets/6489398/26477830/8ab80b80-41f2-11e7-81cf-424b15ad4dd2.png">
<img width="1278" alt="screen shot 2017-05-26 at 9 10 07 am" src="https://cloud.githubusercontent.com/assets/6489398/26478141/6384720e-41f4-11e7-9e06-455c77a6b7ea.png">

One way we can track social media sharing as part of our citation tracking and M&E and would like to propose that we implement @opendevmekong instead of "Open Development Mekong" in the suggested text for Twitter sharing. (see 2, and an example from Quartz)
<img width="1271" alt="screen shot 2017-05-26 at 9 08 09 am" src="https://cloud.githubusercontent.com/assets/6489398/26478155/7500d338-41f4-11e7-965e-65d8e6917085.png">

Question: 
1. Do you know how we can track sharing on Facebook of the pages on the site?
2. In terms of options for social sharing, do we have any idea how these have been used? Can we add an e-mail sharing button on the page? (I think we had this previously). Also LinkedIn is probably more popular than Google +

**Comment by acorbi** [comment]
thanks for raising this improvement suggestions @gimmemochi , will add them to my list of things to check.
