### ISSUE TITLE
Taxonomic terms and Keywords should not overlap

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#966]
@acorbi - This was a requirement for the Keyword field and I notice that the Keywords field in CKAN still allows for taxonomic terms to be used. This could end up being an issue due to duplication and inconsistency in the logic for search. Could you please estimate when this will be implemented? I couldn't find the original issue in Github.

**Comment by acorbi** [comment]
original issue on https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/420 , closing this one since its duplicated.

@prustar will estimate
