### ISSUE TITLE
Search for Synonyms not working

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#967]
Example: EITI, Extractive Industries Transparency Initiative

Brings up different results: 
https://opendevelopmentmekong.net/?type=news-article&taxonomy=all&sorting=score&s=EITI

https://opendevelopmentmekong.net/?s=Extractive+Industries+Transparency+Initiative&type=dataset&page=0

The results should be the same.

**Comment by acorbi** [comment]
This is related to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/48 . Currently, due to a bug on search engine we use, multi-valued synonyms are currently not functioning. Closing this one.
