### ISSUE TITLE
Data HTML and KML Downloads giving errors when clicked

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#99]
I noticed consistently when I clicked a data set and tried either HTML or KML I got errors

https://pp.opendevelopmentmekong.net/dataset/?id=mapkit-protected-areas-kh

![kml-html-error](https://cloud.githubusercontent.com/assets/16559612/16899254/6850bfb0-4bcb-11e6-801c-77ae911beded.JPG)

![error1](https://cloud.githubusercontent.com/assets/16559612/16899255/6b2ca334-4bcb-11e6-9cad-8b847d22b56b.JPG)

![error2](https://cloud.githubusercontent.com/assets/16559612/16899256/6f1fb332-4bcb-11e6-971e-374595a765e8.JPG)

**Comment by acorbi** [comment]
@jpeizer1 @prustar the mapping data linked from geoserver seems to not be available anymore. please check.

**Comment by Huyeng** [comment]
Dataset was deleted.
